### ISSUE TITLE
Dason's website

### ISSUE THREAD

**Issue by yihui** [rbind/support#1]
Hi @Dasonk, do you want to move your website here? You don't have to use blogdown. Jekyll is fine, but I suggest you use Netlify, which is better than Github pages IMO.

**Comment by Dasonk** [comment]
Interesting.  I have been thinking about getting back into blogging recently but probably won't for another week or two.  When I get some time I'll look into what it takes to switch everything over and see if I have the time.  Thanks for pinging me with the idea.

**Comment by road2stat** [comment]
Closing this for now as there doesn't seem to be actionable items that need support efforts. Please reopen or create a new issue if this changes in the future.
