### ISSUE TITLE
New subdomain request

### ISSUE THREAD

**Issue by proto4426** [rbind/support#101]
My current Netlify website address :
https://pissoorta.netlify.com/    (in its early days of deployment)

My preferred rbind.io subdomain
https://pissoorta.rbind.io/

Do I have to transfer my [repo](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) to do that, as proposed [here](https://support.rbind.io/about/) ?

Many thanks in advance.

**Comment by yihui** [comment]
You don't have to transfer your repo, but you are welcome to.

One @rbind/matrix member should help you later.

**Comment by road2stat** [comment]
@proto4426 - thanks for sending the request. I have configured the rbind subdomain you requested.

**Comment by proto4426** [comment]
Fast and easy !
Thank you very much.
