### ISSUE TITLE
subdomain request

### ISSUE THREAD

**Issue by jarvmiller** [rbind/support#102]
### Netlify website address

jarvismiller.netlify.com

### Preferred rbind.io subdomain

https://jarvis.rbind.io

Thank you!

**Comment by road2stat** [comment]
@jarvmiller I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!

**Comment by jarvmiller** [comment]
I have clicked 'set a custom domain' and entered `jarvis.rbind.io`. then clicked the https enabler button. Now I have the following results
<img width="677" alt="screen shot 2017-10-20 at 7 08 26 pm" src="https://user-images.githubusercontent.com/16932929/31845004-9ed83fc6-b5ca-11e7-8660-27cd44bfce27.png">
<img width="469" alt="screen shot 2017-10-20 at 7 08 43 pm" src="https://user-images.githubusercontent.com/16932929/31845005-9ef099b8-b5ca-11e7-9a3e-cd8ee7d3b643.png">

I'm sure I've done something wrong

**Comment by road2stat** [comment]
Looks good to me and the subdomain is working for me here. @yihui - could you please double check if everything's ok?

**Comment by jarvmiller** [comment]
It actually works now! I guess it may have just taken longer? I tried it immediately and got an error saying it couldn't reach the site but now everything seems to be ok. Thanks!

**Comment by jarvmiller** [comment]
Sorry, just noticed a small issue. I transferred my repo to rbind and now the url is https://github.com/rbind/netlify_site

however, when I try to use this for CI w/ netlify I get the following error: 
`Error: We couldn’t set up continuous deployment for this repository. This typically happens when you don’t have admin rights to the repository`

**Comment by yihui** [comment]
@jarvmiller Just keep your previous site on Netlify. You don't need to create a new site from the repo you transferred. The old repo will be automatically redirected to the new one by Github. In other words, there is nothing you need to do on Netlify. BTW, you'd better rename your repo (`netlify_site` is a too general name here, but it is up to you).

@road2stat Please make @jarvmiller admin of his repo.

**Comment by road2stat** [comment]
-- thanks @yihui, @jarvmiller is now admin of the transferred repo.
