### ISSUE TITLE
subdomain request

### ISSUE THREAD

**Issue by aloy** [rbind/support#103]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

aloy.netlify.com

### Preferred rbind.io subdomain

aloy.rbind.io

**Comment by yihui** [comment]
No problem. An rbind admin @rbind/matrix will help you later.

**Comment by road2stat** [comment]
-- thanks @aloy for sending the request. I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)
