### ISSUE TITLE
Subdomain request

### ISSUE THREAD

**Issue by nataliegnelson** [rbind/support#104]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

nelson.netlify.com

### Preferred rbind.io subdomain

nelson.rbind.io

**Comment by road2stat** [comment]
@nataliegnelson I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!
