### ISSUE TITLE
Subdomain request for my netlify

### ISSUE THREAD

**Issue by sharathdhamodaran** [rbind/support#105]
Hi,
I am requesting a subdomain for my website at https://sharathdhamodaran.netlify.com/ to be hosted at sharathdhamodaran.rbind.io

Kindly let me know if you need further information

Thanks,
Sharath

**Comment by road2stat** [comment]
@sharathdhamodaran I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!
