### ISSUE TITLE
requesting an rbind subdomain

### ISSUE THREAD

**Issue by sn248** [rbind/support#106]
Dear admin

Could you please configure an rbind subdomain for my netlify website. The relevant informatin is provided below. Thank you!

### Netlify website address

sn248.netlify.com

### Preferred rbind.io subdomain

sn248.rbind.io

**Comment by road2stat** [comment]
@sn248 - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!
