### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by martinolmos** [rbind/support#107]
Hi, 
I would like to request an rbind.io subdomain.
Thanks!

### Netlify website address

https://cameraman-parrot-62240.netlify.com

### Preferred rbind.io subdomain

r2website.rbind.io

**Comment by road2stat** [comment]
@martinolmos - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!
