### ISSUE TITLE
New subdomain request

### ISSUE THREAD

**Issue by adam-gruer** [rbind/support#108]
Hi , I'd linke to request a rbind.io subdomain please.
 Thank you!

### Netlify website address

trader-chimpanzee-34787.netlify.com

### Preferred rbind.io subdomain

adamgruer.rbind.io

**Comment by road2stat** [comment]
@adam-gruer - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!
