### ISSUE TITLE
New subdomain request

### ISSUE THREAD

**Issue by fmgarciadiaz** [rbind/support#109]
Hi,
I would like to request an rbind.io subdomain.
Thanks!

Netlify website address

https://operator-albert-36287.netlify.com

Preferred rbind.io subdomain
fergd.rbind.io

**Comment by road2stat** [comment]
@fmgarciadiaz - I have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!

**Comment by fmgarciadiaz** [comment]
=) thanks!!
