### ISSUE TITLE
Need a new domain

### ISSUE THREAD

**Issue by bnaras** [rbind/support#110]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

I don't have one. You can see the preview at:

https://web.stanford.edu/~naras/cvxr

for now although the source is at https://github.com/bnaras/cvxr_docs

I am using the Hugo alabaster theme.  The package is due to be released to cran in a few days and so this in preparation for that release

### Preferred rbind.io subdomain

cvxr.rbind.io

**Comment by road2stat** [comment]
@yihui - I guess we might need the original website's address to be under a top or sub domain without additional paths to directories? Not sure if this is possible...

**Comment by yihui** [comment]
@bnaras Since the source is in a Github repo, I recommend you to publish it via Netlify: https://bookdown.org/yihui/blogdown/deployment.html (Section 3.1). After you have got the Netlify subdomain, we can configure the rbind.io subdomain for you.

**Comment by bnaras** [comment]
Thanks @yihui . I got cvxr-netly.netlify.com

**Comment by road2stat** [comment]
@bnaras - thanks! I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)
