### ISSUE TITLE
*.rbind.io domain names

### ISSUE THREAD

**Issue by NanaAkwasiAbayieBoateng** [rbind/support#111]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address
https://nanaboateng.Netlify.com

example.netlify.com

### Preferred rbind.io subdomain

https://nanaboateng.rbind.io

**Comment by road2stat** [comment]
@NanaAkwasiAbayieBoateng - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!

**Comment by NanaAkwasiAbayieBoateng** [comment]
Thank you
