### ISSUE TITLE
I would love to have my personal rbind.io. subdomain! Thank you so much!

### ISSUE THREAD

**Issue by mingrisch** [rbind/support#113]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

mingrisch.netlify.com

### Preferred rbind.io subdomain

mingrisch.rbind.io

**Comment by yihui** [comment]
Just briefly read your blog post on line-lengths and loved it! It is also something I was interested in but didn't have the time to analyze.

Anyway, one @rbind/matrix member should help you set up your subdomain later.

**Comment by road2stat** [comment]
@mingrisch I'll second Yihui's comment on the line-length post. Great story!  👏 

Also, I have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!
