### ISSUE TITLE
Security with rbind host

### ISSUE THREAD

**Issue by davidjohnbaker1** [rbind/support#114]
Hello--

When other users try to access my website davidjohnbaker.rbind.io they report that the connection is not secure and thus think they are unable access it. This happens more often when directed to specific posts ( https://davidjohnbaker.rbind.io/post/calculating-imultisets-in-r/ ) and am not exactly sure how to deal with this. My usual browsers (Chrome 61.0.3163.100 or Firefox 57.0) normally display the sites just fine (with exceptions here or there). 

Is there something I need to change in my configuration file so the connection to the site is secure?

--Dave

**Comment by yihui** [comment]
Screenshots please. I don't see any warnings about non-secure connections with Chrome 62 or Firefox 57.

**Comment by davidjohnbaker1** [comment]
I spent the morning reading about it since posting and think I fixed the problem. I do not think I had my Security Certificate enabled via Netlify. I haven't been able to reproduce the problem since.
