### ISSUE TITLE
*rbind.io subdomain request

### ISSUE THREAD

**Issue by tmastny** [rbind/support#115]
Hi, I'd like to request an rbind.io subdomain.

### Netlify website address

timmastny.netlify.com

### Preferred rbind.io subdomain

timmastny.rbind.io

**Comment by road2stat** [comment]
@tmastny - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!
