### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by Dehong1** [rbind/support#116]
Hi, I'd like to request an rbind.io subdomain.
### Netlify website address
https://dehongblog.netlify.com
### Preferred rbind.io subdomain
DeHong.rbind.io

**Comment by road2stat** [comment]
@Dehong1 - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!

**Comment by Dehong1** [comment]
Thank you again!

**Comment by Dehong1** [comment]
Please tell me is there anything I will do except setting the custom domain ?
![default](https://user-images.githubusercontent.com/33835267/33197692-f640313e-d121-11e7-8bba-518b6242deaf.png)

**Comment by Dehong1** [comment]
![Uploading 图片.png…]()

**Comment by Dehong1** [comment]
![default](https://user-images.githubusercontent.com/33835267/33197753-4919302c-d122-11e7-899e-ec433abd82d1.png)

**Comment by Dehong1** [comment]
Thank you

**Comment by Dehong1** [comment]
When I run the custom domain,the screen shows  Not Found,I want to know what I should do next.
![default](https://user-images.githubusercontent.com/33835267/33206581-a8ab57c2-d145-11e7-80f6-af48f18c1120.png)

**Comment by Dehong1** [comment]
@road2stat

**Comment by road2stat** [comment]
Not sure what's going on here, just double-checked the settings on our side and it looks good. Maybe @yihui could shine some light on this?

**Comment by yihui** [comment]
No, I have no idea. Please contact Netlify support.

**Comment by yihui** [comment]
Actually the reason _might_ be that the subdomain configuration on Netlify is case-sensitive. We can only give you dehong.rbind.io and not DeHong.rbind.io. Anyway, please contact Netlify if the lower-case version does not work.

**Comment by Dehong1** [comment]
dehong.rbind.io is right,thank you !
