### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by marcosci** [rbind/support#117]
### Netlify website address

marcosci.netlify.com

### Preferred rbind.io subdomain

marcosci.rbind.io

Thank you!

**Comment by road2stat** [comment]
@marcosci - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!

**Comment by marcosci** [comment]
thanks @road2stat :) worked like a charme
