### ISSUE TITLE
Requesting new rbind.io subdomain

### ISSUE THREAD

**Issue by sophieb** [rbind/support#120]
Hi,

I would like to request a new rbind.io subdomain.

### Netlify website address

stt4230.netlify.com

### Preferred rbind.io subdomain

stt4230.rbind.io

Thanks

**Comment by road2stat** [comment]
@sophieb - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!

**Comment by sophieb** [comment]
Thank you!
