### ISSUE TITLE
Request subdomain

### ISSUE THREAD

**Issue by ozagordi** [rbind/support#122]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

ozagordi.netlify.com

### Preferred rbind.io subdomain

ozagordi.rbind.io

**Comment by road2stat** [comment]
@ozagordi - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!

**Comment by ozagordi** [comment]
Thanks!
