### ISSUE TITLE
Request subdomain

### ISSUE THREAD

**Issue by aosmith16** [rbind/support#123]
### Netlify website address

aomsith.netlify.com

### Preferred rbind.io subdomain

aosmith.rbind.io

Thanks!

**Comment by road2stat** [comment]
@aosmith16 - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!
