### ISSUE TITLE
Requesting subdomain for Netlify 

### ISSUE THREAD

**Issue by JiayiJi** [rbind/support#126]
Hi, my Netlify website address is

https://agitated-jepsen-e08ce5.netlify.com/

My preferred rbind.io subdomain is

jiayi.rbind.io

Thanks!

**Comment by road2stat** [comment]
@JiayiJi - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!

**Comment by JiayiJi** [comment]
Thanks! I've set the rbind subdomain in my Netlify account and update the baseurl in my config.toml file to reflect my new rbind subdomain name (so mine is baseurl = "https://jiayi.rbind.io/"). Now I can use my rbind subdomain. However, when I go to a new page in my website, I will always encounter "Your connection is not private" notification indicating the site I am visiting is not secure. Do you happen to know the solution? Thank you again!

![screen shot 2017-12-28 at 12 15 10](https://user-images.githubusercontent.com/26682045/34417867-cb3d4f0a-ebc8-11e7-8c23-eb6b8541e825.png)

**Comment by road2stat** [comment]
@JiayiJi - good question, I saw similar issues before. Just guessing... is there a switch or some options about SSL/https for the rbind.io subdomain you could flip on Netlify? Sorry for asking this because I'm not a Netlify user yet...

**Comment by JiayiJi** [comment]
Thank you for your hint! I solved the problem myself. I have to enable automatic TLS certificates on Netlify. Thanks again for your quick response
![screen shot 2017-12-28 at 13 28 05](https://user-images.githubusercontent.com/26682045/34419652-100e878e-ebd3-11e7-88a9-c2fe03efbd02.png)
