### ISSUE TITLE
New rbind.io request.

### ISSUE THREAD

**Issue by softloud** [rbind/support#127]
Hi there,
I'm setting up a blog and came across this: https://support.rbind.io/2017/05/29/romain-francois-s-site-with-blogdown-hugo-rbind/ This sounds like the perfect workflow for me. 

Don't know if it's too broad for your group, but I plan to blog about stats, R, tidyverse, productivity for data science, mathematics, and just a little musical theory. 
Best, \C

### Netlify website address

example.netlify.com

I could do with some help setting this up, if you're amenable. I'm unsure of what to put into the fields <build command> and <publish directory>. I'm teaching myself with this: https://bookdown.org/yihui/blogdown

### Preferred rbind.io subdomain

cantabile.rbind.io

**Comment by road2stat** [comment]
@softloud - welcome! We're happy to have you in the rbind family. The setup process is simple. The first step would be creating a blogdown website locally, and push it to a GitHub repo.

The next step would be logging into Netlify, click the button "New site from Git", click the GitHub button, authorize Netlify to access your GitHub repos. Select your blogdown website repo in the repo list. Then the screenshots [here](https://bookdown.org/yihui/blogdown/netlify.html) will be helpful for filling out the necessary values. The current `HUGO_VERSION` is `0.31.1`.

After finishing this configuration, you could see that your Netlify site is assigned a random subdomain (like `aaa-bbb-ccc.netlify.com`). You are free to change it to your preferred subdomains such as `cantabile.netlify.com` or keep it that way. Note that now your website should be live at that address.

Please let us know that Netlify subdomain, so we could point the `cantabile.rbind.io` to that address. We will let you the following step.

Hope this helps.
-Nan

**Comment by softloud** [comment]
Thanks, Nan - the rstats community just keeps surprising me with how wonderfully supportive it is. 

How did I miss those screenshots in the Netlify section? Thanks for putting me onto that. Really appreciate the support.

Before I forget, I'm using Hugo and the `spf13/hyde` theme. 

I selected the repo, and followed along with the screen shots and set my build command to hugo and my publish directory to public. 

Since I get this:
```
blogdown::hugo_version()
[1] ‘0.32’
```

I created a variable HUGO_VERSION and set it to 0.32. 

But my site isn't live at that address  😞  Troubleshooting now.

**Comment by orchid00** [comment]
I think it should be 0.32.1 without quotes

**Comment by road2stat** [comment]
Hi @softloud -just noticed [on twitter](https://twitter.com/cantabile/status/1002471340606087168) that you've got the blogdown site up and running! (gifted-boyd-95f3c3.netlify.com). Let us know if you want us to assign the rbind subdomain you requested (cantabile.rbind.io) to this Netlify address.

**Comment by softloud** [comment]
Hello again!
Okay, things have gone much better this time. I followed along with Alison Hill's [wonderful post](https://alison.rbind.io/post/up-and-running-with-blogdown/#in-github) about getting started :)  

I have no idea what I did wrong last time, but this time it's going much better and I have the [site](https://measured.netlify.com/post/) up. I changed the netlify site name to **measured**. w00t!  

--- and that's what I wrote last night but didn't finish, thanks for getting in touch in the meantime! 

Assign away!

**Comment by road2stat** [comment]
@softloud -glad to see it works this time! We have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by softloud** [comment]
w00t! I'm an rbind-er! Thanks for the assistance - I learnt a lot from this.

**Comment by road2stat** [comment]
-great! Let us know if you got any other questions. Closing the issue for now.
