### ISSUE TITLE
New rbind.io request

### ISSUE THREAD

**Issue by andkov** [rbind/support#128]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address
andriy.netlify.com

### Preferred rbind.io subdomain

andriy.rbind.io

Thank you!

**Comment by road2stat** [comment]
@andkov - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by andkov** [comment]
Thank you, @road2stat, for such a short turn around.  Happy new year!

**Comment by andkov** [comment]
@road2stat , could you please add me to the rbind org so I can transfer the source for my blog? Thank you.

**Comment by road2stat** [comment]
@andkov - that's done. Please check the email invitation.

**Comment by andkov** [comment]
Thank you, @road2stat. I have just submitted the transfer request.

Unfortunately, I cannot complete the domain change.  When following the [instructions ](https://support.rbind.io/about/) I do change the name on my netlify account 
![image](https://user-images.githubusercontent.com/2608073/34484722-9eef5644-ef7b-11e7-9b4e-811fa05fd972.png)

When following the prompt to "Check DNS configuration" , however, I do not understand the following instructions:
![image](https://user-images.githubusercontent.com/2608073/34484704-847cfd20-ef7b-11e7-96e3-437155ae2c7a.png)

It's not clear from the instructions WHERE I am supposed to log in.  I'm sure it's something obvious, but not for me. 

WHen following the link for "Set up Netlify DNS for rbind.io"  , the second step does not yield any visible results:
![image](https://user-images.githubusercontent.com/2608073/34485016-3f4554f8-ef7d-11e7-9e3d-560f5ad7962e.png)
If I blindly agree to proceed to the next step, those fields do not become visible:
![image](https://user-images.githubusercontent.com/2608073/34485046-5aaa52b6-ef7d-11e7-9fac-667c7fc3c9cf.png)
I followed the prompt anyway, but to now avail:
![image](https://user-images.githubusercontent.com/2608073/34485093-96508ede-ef7d-11e7-9acb-4d3711c8b100.png)

However, I did change the url in my config.toml:
![image](https://user-images.githubusercontent.com/2608073/34484739-bde195ee-ef7b-11e7-96fc-38eca537d3ac.png)

Any hints what I might did wrong?

**Comment by road2stat** [comment]
@andkov - please remove the `www.`, and just use `andriy.rbind.io` as your custom domain name (I'd recommend delete the previously added record and start fresh). Then you should be able to enable HTTPS for this custom domain.

**Comment by andkov** [comment]
@road2stat, yes, that was it. Site is now available from [andriy.rbind.io](http://andriy.rbind.io/)

Thanks for your help!
