### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by jpreszler** [rbind/support#129]
### Netlify website address

jpreszler.netlify.com

### Preferred rbind.io subdomain

jpreszler.rbind.io

Thanks,
Jason

**Comment by road2stat** [comment]
@jpreszler - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by jpreszler** [comment]
Thanks for the quick response, @road2stat !
