### ISSUE TITLE
New rbind.io subdomain request

### ISSUE THREAD

**Issue by orchid00** [rbind/support#130]
Hi, just started using hugo themes -academic
here is my request please. Let me know how can I further help with this and if I am able to do modifications from github directly that will render in the new URL.
Thanks!

### Netlify website address

https://paulaandrea.netlify.com/

### Preferred rbind.io subdomain

paulaandrea.rbind.io

**Comment by road2stat** [comment]
Hi @orchid00 - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by orchid00** [comment]
I think it is working [https://paulaandrea.rbind.io/](https://paulaandrea.rbind.io/)

please let me know if I need or if I could do something else, I am truly grateful!

**Comment by road2stat** [comment]
-yes, it's working! :)

![](https://media.giphy.com/media/9K2nFglCAQClO/giphy.gif)
