### ISSUE TITLE
New rbind.io subdomain request

### ISSUE THREAD

**Issue by shhuang1** [rbind/support#131]
Hello,
I'd like to request a subdomain for my lab at NYU.

### Netlify website address

huanglab.netlify.com

### Preferred rbind.io subdomain

huanglab.rbind.io

Thanks,
Carol Huang

**Comment by road2stat** [comment]
@shhuang1 - nice website! Congrats on your new lab and we are thrilled to include you in the rbind family. I have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by shhuang1** [comment]
This is working great!  Thanks a lot.

-Carol
