### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by aniruhil** [rbind/support#132]
Hi there;

I've been tinkering with blogdown and want to switch my site to rbind.io. I teach stats with R and also use it in my work and with all you folks are doing for the stats community now is the time to start writing more! 

The netlify website address: milo.netlify.com 

preferred rbind.io subdomain: ani.rbind.io

If that is not permissible then: aniruhil.rbind.io

I will be using the Hugo-academic theme (customized a bit) and eventually using a custom domain name: aniruhil.org that has been setup and is working through netlify. 

thanks, and happy 2018!

Ani

**Comment by road2stat** [comment]
@aniruhil - looks great! I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by aniruhil** [comment]
thanks @road2stat. I'll be in touch if something goes wrong.

**Comment by aniruhil** [comment]
@road2stat, I believe I have to wait for an invite to bind before moving an existing GitHub repo OR creating a new blogdown site that is pushed to ani.rbind.io? 

HTTPS is enabled on netlify and the subdomain set as well.

**Comment by road2stat** [comment]
@aniruhil - that's correct and I have sent the invitation, please check your email. Thanks!
