### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by WangDing666** [rbind/support#133]
### Netlify website address

jiajun.netlify.com
 Preferred rbind.io subdomain

jiajun.rbind.io

thanks, and happy 2018!

**Comment by road2stat** [comment]
@WangDing666 - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by WangDing666** [comment]
Thank you very much.
