### ISSUE TITLE
Subdomain request, thank you!

### ISSUE THREAD

**Issue by timraiswell** [rbind/support#134]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

timraiswell.netlify.com

### Preferred rbind.io subdomain

raiswell.rbind.io

**Comment by road2stat** [comment]
@timraiswell - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
