### ISSUE TITLE
subdomain request

### ISSUE THREAD

**Issue by TiagoVentura** [rbind/support#136]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

tiagoventura.netlify.com/

### Preferred rbind.io subdomain

tiagoventura.rbind.io

Thank you!

**Comment by TiagoVentura** [comment]
Thank you! Already working.

http://tiagoventura.rbind.io/

**Comment by road2stat** [comment]
-great! Beautiful website! I'll close the ticket for now. Please just let us know if you got more questions.
