### ISSUE TITLE
New .rbind.io domain request

### ISSUE THREAD

**Issue by andkov** [rbind/support#137]
Hi @road2stat, I have another domain name I would like to request you to rename. Thank you!

### Netlify website address

dss-ialh.netlify.com

### Preferred rbind.io subdomain

dss-ialh.rbind.io

**Comment by road2stat** [comment]
Hi @andkov, thank you for submitting the domain request. We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by andkov** [comment]
thank you, @road2stat . everything works.
