### ISSUE TITLE
New site subdomain request

### ISSUE THREAD

**Issue by apreshill** [rbind/support#14]
Hi,

I would like to use blogdown to create a new site with the subdomain "apreshill.rbind.io" using the Hugo academic theme. I have created a Netlify account linked to my Github. Please let me know the next steps.

Thanks for such amazing support and documentation thus far!
Alison

**Comment by yihui** [comment]
Please let us know your Netlify subdomain, and we will assign apreshill.rbind.io to you.

BTW, please also let us know if you want to create the Github repo under rbind. We are always looking forward to more examples here to inspire more people. Thanks!

**Comment by apreshill** [comment]
Hi Yihui,

My very unfortunate Netlify subdomain is "garbage-collector-janice-16154". I'm happy to transfer the repo to rbind to help other new users! Just let me know how to do so.

Alison

**Comment by yihui** [comment]
I have bound the domain apreshill.rbind.io to your Netlify subdomain, so you just need to apply the custom domain on Netlify.

Please read https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/ or https://support.rbind.io/about/ on how to transfer your repo. Thanks!

**Comment by thercast** [comment]
@apreshill Just checking to see if you have any issues with getting your repository transferred?  I'm glad to help if you need further assistance.

**Comment by apreshill** [comment]
@thercast Hi Eric- thank you! I'm to point where it is asking about team access- vectors and matrix. Is there a correct choice here?

**Comment by yihui** [comment]
Either should be fine. It should not matter.

**Comment by apreshill** [comment]
Great thanks- I transferred it.
