### ISSUE TITLE
rbind domain request

### ISSUE THREAD

**Issue by dshahnazian** [rbind/support#144]
Hello,

How can I join rbind and transfer ownership? I've already built and deployed my website (content is WIP), I'd just like to have the repo listed under github.com/rbind if possible. 

### Netlify website address
priceless-booth-5a624c.netlify.com

### Preferred rbind.io subdomain

daneshshahnazian.rbind.io

**Comment by road2stat** [comment]
@dshahnazian - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

We also invited you to the rbind GitHub organization, please check your email to confirm.

Thanks!
