### ISSUE TITLE
*.rbind.io request

### ISSUE THREAD

**Issue by tyluRp** [rbind/support#146]
Hi all, would like to join the rbind community.

### Netlify website address

tylurp.netlify.com

### Preferred rbind.io subdomain

tylurp.rbind.io

Please let me know if I missed anything, and thank you.

**Comment by road2stat** [comment]
@tyluRp - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by tyluRp** [comment]
Thanks so much!
