### ISSUE TITLE
Requesting *.rbind.io

### ISSUE THREAD

**Issue by suzanbaert** [rbind/support#147]
Hi,
I would also love to join the rbind club :)

### Netlify website address
https://suzanbaert.netlify.com/

### Preferred rbind.io subdomain
suzan.rbind.io

I'm using the hugo-tranquilpeak-theme right now.

Thank you
suzan

**Comment by road2stat** [comment]
@suzanbaert - welcome to the club! We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by suzanbaert** [comment]
That was incredibly fast! Thank you very much! 

One more question, though all the rbind.io addresses seem to work fine, if I click a link from within the main page it is still referring to *.netlify.com. 

Apparently some people had issues with opening a netlify link to a tutorial at work, so I would prefer to have everything covered under *.rbind. 
How do I made that change?  Is that in my config file, or do I have to get a repo here?

I'm sure it is somewhere in the help files already, but i could not find it easily in the support website 😞

**Comment by road2stat** [comment]
@suzanbaert 

In https://github.com/suzanbaert/BlogFiles/blob/master/config.toml#L15

Let's change 

```
baseURL = "https://suzanbaert.netlify.com/"
```

to

```
baseURL = "https://suzan.rbind.io/"
```

**Comment by suzanbaert** [comment]
So it is on my end.
Thanks for the help, works brilliantly!
