### ISSUE TITLE
yet another .rbind.io request

### ISSUE THREAD

**Issue by tonyelhabr** [rbind/support#148]
Hi. I would like to request a subdomain.

### Netlify website address

tonyelhabr.netlify.com

### Preferred rbind.io subdomain

tonyelhabr.rbind.io

Thanks in advance!

**Comment by road2stat** [comment]
@tonyelhabr - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by tonyelhabr** [comment]
Seems like everything is working!
