### ISSUE TITLE
Domain request

### ISSUE THREAD

**Issue by gd6** [rbind/support#149]
### Netlify website address

https://kind-carson-39b265.netlify.com

### Preferred rbind.io subdomain

sep.rbind.io

### Additional Comment

Thank you all for your work! SEP (the Student Empowerment Project) is a student organization interested in fostering open cooperation, and we have been making a lot of use of Bookdown to develop [study guides](https://open-cuny.appspot.com) (including a few statistics ones!) for courses at our University. Our site would be a blog with information on our various projects, including how to assess their effectiveness using R packages.

If you are all alright with our site being hosted via Rbind, I was wondering whether we would be able to change this subdomain to a different repo later. Currently the repo for the site is at https://github.com/gd6/casper-blogdown-site . I'd like it to be on an organization's GitHub: https://github.com/sepqc . I was also wondering if it could have subdomains itself (e.g. blog.sep.rbind.io).

**Comment by road2stat** [comment]
@gd6 - cool website! We're happy to have you folks in the rbind family. I have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

For moving the repo to another place -- I guess you could just configure the website on Netlify and point the source to the new GitHub repo?

For another level of rbind.io subdomains, I'm not really sure if that's possible -- maybe @yihui could offer some inputs here.

**Comment by gd6** [comment]
Thanks a lot! It looks like GitHub repos can't be pointed to even if you're collaborators on them unless you've forked them? That is, I seem to be unable to point the site to this repo as a source: https://github.com/sepqc/sep-blog

But in any case it's working great! Thanks so much for letting us aboard! I'd love to be able to ask y'all some questions regarding Blogdown's capabilities for embedding animations as Bookdown seems a bit limited for this.

**Comment by yihui** [comment]
@road2stat To my knowledge, there are no such a thing as "sub-sub-domains" -- `blog.sep.rbind.io` and `sep.rbind.io` are both subdomains, and the dot in `blog.sep` has no special meaning (technically), so yes, you can assign `blog.sep.rbind.io` to @gd6 if desired.

**Comment by road2stat** [comment]
@yihui -cool! I thought each level added by the dot is semantic and should be relevant to DNS server settings or something... So @gd6 please feel free to let us know where you want to point the subdomain names to if there are multiple (it was a little bit unclear about the `blog.sep` one).

**Comment by gd6** [comment]
Dear Road2stat and Yihui Xie, 

I'm sorry on the huge delay on this. For now, since we don't have a main website live apart from our blog yet, just this domain will be fine! Will take you up on that offer later I hope though. Thanks again for your work

**Comment by road2stat** [comment]
@gd6 -cool! No worries at all. Please just let us know the other preferred subdomain names and the original website addresses so we can set them up for you.
