### ISSUE TITLE
subdomain romain.rbind.io

### ISSUE THREAD

**Issue by romainfrancois** [rbind/support#15]
I've started to exhume some content from old blogs to the `rbind/romain` repo. 

All seems to work fine with netlify: https://juggler-graph-86721.netlify.com

Can I have `romain.rbind.io` please.

**Comment by yihui** [comment]
Sure. I have set the CNAME record for you, and you need to set it up on your side, too (hit the button "Set up domain" on Netlify).

**Comment by romainfrancois** [comment]
Done. Thanks a lot.

**Comment by yihui** [comment]
No problem. You can actually redirect the Netlify subdomain to your own domain, e.g. https://github.com/rbind/yihui/blob/master/static/_redirects#L8-L9
