### ISSUE TITLE
Requesting rbind.io subdomain

### ISSUE THREAD

**Issue by fengfengyuyu** [rbind/support#150]
Hello!

I am a useR and I am studying to build my own blog.  Blogdown is cool, let me join rbind.io family ^-^

### Github website address
fengfengyuyu.github.io

### Preferred rbind.io subdomain
honebay.rbind.io

Thank you very much! AND HAPPY Spring Festival!

Fengyu

**Comment by road2stat** [comment]
@fengfengyuyu - welcome to rbind, and happy spring festival!

We have configured the rbind subdomain you requested. To make it work, please put a CNAME file in your repo: https://github.com/rbind/support/issues/139

**Comment by fengfengyuyu** [comment]
@road2stat - thank lots!

I have some trouble in setting netlify. and it sounds like be a problem about the version of [hugo](https://d.cosx.org/d/419791-blogdown-netlify-non-zero-exist-code-255/4) .my hugo is `blogdown::hugo_version()
[1] ‘0.36.1’`. my repo is [repo address](https://github.com/fengfengyuyu/honebay.rbind.io)

**Comment by road2stat** [comment]
@fengfengyuyu 

- the content of your `CNAME` file should be

```
honebay.rbind.io
```

**Comment by fengfengyuyu** [comment]
@road2stat 

I revised my `CNAME` file ( content - `honebay.rbind.io` ), but the problem ( 404 ) is not solved.

The process that I added `honebay.rbind.io` domain is as follow:

![default](https://user-images.githubusercontent.com/11608887/36404071-b5bd0488-1623-11e8-9e1b-36bad5538394.png)

I saw the warning `Check DNS Configuration`, clicked it,  then poped a window as follow:

![default](https://user-images.githubusercontent.com/11608887/36404422-8a7e2bce-1625-11e8-9467-600654256f05.png)

I changed the content of my `CNAME` file  ( content - `honebay CNAME honebay.netlify.com` ) , but  the problem ( 404 ) is not solved.  So I clicked `Set up Netlify DNS for rbind.io` , poped another window as follow:

![default](https://user-images.githubusercontent.com/11608887/36404666-0dd07562-1627-11e8-8e19-1be5a74328f0.png)
I finished the steps of `Set up Netlify DNS for your domain`, to my surprise,  at the last step, the content of `the following hostnames` is **blank**. I guess it maybe the reason of the problem(404).

please give some advice to fix it . thanks in advance.

**Comment by road2stat** [comment]
@fengfengyuyu - ok... I see where the problem is.

If you want to host the website using Netlify, then

1. please remove the `CNAME` file from [your repo](https://github.com/fengfengyuyu/honebay.rbind.io) because it's no longer useful.
1. we need to reconfigure the rbind DNS record on our side to point it to `honebay.netlify.com`.

@yihui - could you please modify the record `honebay` to point it to `honebay.netlify.com` instead of `fengfengyuyu.github.io`? Thanks a lot!

**Comment by yihui** [comment]
Sure. Done.

**Comment by fengfengyuyu** [comment]
@road2stat @yihui - thanks !  everything is ok !
