### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by frankfarach** [rbind/support#151]
I am requesting a new rbind.io subdomain for my website, which uses the cactus theme for Hugo.

### Netlify website address

frankfarach.netlify.com

### Preferred rbind.io subdomain

frankfarach.rbind.io

**Comment by road2stat** [comment]
@frankfarach - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by frankfarach** [comment]
Thank you, @road2stat - the subdomain appears to be working.
