### ISSUE TITLE
Requesting subdomain

### ISSUE THREAD

**Issue by gtlaflair** [rbind/support#152]
I would like to request an rbind subdomain for my personal academic site

### Netlify website address

gtlaflair.netlify.com

### Preferred rbind.io subdomain

gtlaflair.rbind.io

**Comment by road2stat** [comment]
@gtlaflair - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by gtlaflair** [comment]
@nanxstats I've stopped using this website. I've already deleted the netlify account. Is there anything I should do here with rbind to do the same?

**Comment by nanxstats** [comment]
@gtlaflair Thanks for letting us know!

@yihui could you help remove the `gtlaflair.rbind.io` subdomain please?

**Comment by yihui** [comment]
Done.

**Comment by gtlaflair** [comment]
Thank you @nanxstats and @yihui! Thank you to you all for running this service for everyone :)
