### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by mcdussault** [rbind/support#153]
Good morning, I would like to get an rbind subdomain please! 
### Netlify website address

mcdussault.netlify.com
### Preferred rbind.io subdomain

mcdussault.rbind.io

Thank you!!!

Marie

**Comment by road2stat** [comment]
@mcdussault - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by mcdussault** [comment]
Thank you!!!

On Feb 15, 2018 5:44 PM, Nan Xiao <notifications@github.com> wrote:

@mcdussault<https://github.com/mcdussault> - we have configured the rbind subdomain you requested. Please set the rbind subdomain<https://support.rbind.io/about/> in your Netlify account.

[https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png]<https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png>

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
