### ISSUE TITLE
Repo transfer

### ISSUE THREAD

**Issue by nanhung** [rbind/support#154]
Hi, please give me the permission for the repo transfer.
My github repo is https://github.com/nanhung/nanhung.me

### Netlify website address

nanhung.netlify.com

### Preferred rbind.io subdomain

nanhung.rbind.io

**Comment by road2stat** [comment]
@nanhung - we have just invited you to the rbind organization for transferring your repo and configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by nanhung** [comment]
Thanks! I already transfer it. Another question is how do I edit the description of my repo in the organization.

**Comment by road2stat** [comment]
@nanhung - cool! You're now admin of the new repo which will allow editing the description.
