### ISSUE TITLE
New rbind.io subdomain

### ISSUE THREAD

**Issue by mikmart** [rbind/support#155]
Hey! I've just recently kicked off a blog, and would love for it to be included in Rbind.

// Mikko

### Netlify website address

mikkomarttila.netlify.com

### Preferred rbind.io subdomain

mikmart.rbind.io

**Comment by road2stat** [comment]
@mikmart - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by mikmart** [comment]
Fantastic, thanks a lot!

**Comment by mikmart** [comment]
Oh, could you also please invite me to the rbind organisation so I can move my repo over, too?

Thanks!

**Comment by road2stat** [comment]
@mikmart - invitation sent.

**Comment by mikmart** [comment]
Thank you, I've just accepted! Now to figure out the repo move..

**Comment by mikmart** [comment]
Clearly I'm too hasty with closing these. Maybe third time's the charm? I've just moved my repo, could I now have admin access to it? 😅

**Comment by road2stat** [comment]
@mikmart - of course, it's done.

**Comment by mikmart** [comment]
Thanks again, and sorry for the bother! It looks like everything is _actually_ set now!
