### ISSUE TITLE
Request rbind.io subdomain

### ISSUE THREAD

**Issue by martinsatt** [rbind/support#156]
Hello, it would be great to get an rbind subdomain. If possible.

My Netlify website address is: 

martinsatt.netlify.com

and my preferred rbind.io subdomain would be:

martinsatt.rbind.io

best regards Martin

**Comment by road2stat** [comment]
@martinsatt - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by martinsatt** [comment]
That is great. Thanks for your help.

Regards Martin

**Comment by road2stat** [comment]
Hey Martin, - no problem at all. It seems that the rbind.io subdomain was redirected with an extra `www.` prefix and it's not really working. I double checked the configuration on our side and it looks ok. Any chance you could fix this on your side?

**Comment by martinsatt** [comment]
Hello Nan Xiao,

Thanks for the help. I changed the settings and it works. Great :)

Martin

**Comment by road2stat** [comment]
- awesome! 👏
