### ISSUE TITLE
Intro to site request for Romain

### ISSUE THREAD

**Issue by thercast** [rbind/support#16]
Greetings @romainfrancois , we are excited to have your site hosted on rbind!  It would be great if you could add a short post that introduces your site and any other information you'd like to share on the [support.rbind.io](https://support.rbind.io/) portal.  It does not need to be long, and check out the various posts that have already been made for some examples.  Also check out the [about](https://support.rbind.io/about/) page for more technical information.  I'm happy to assist if you have any questions about the process.  As an aside I've been a huge fan of your work in the R community and the influential packages you've authored which I use daily in my R workflows :smile:

**Comment by romainfrancois** [comment]
sure. I will definitely do this. For now I'm getting familiar with the platform, and exhuming some old blog posts, then I have some original posts on my todo list, I'd like to have some meat and confidence that I'll keep blogging before advertising. 

and thanks for the kind words :-)

**Comment by romainfrancois** [comment]
Is there somewhere I can put screenshots to discuss some of my theming choices ?

**Comment by thercast** [comment]
I'd recommend you post them to the [rbind/support](https://gitter.im/rbind/support) channel in Gitter since we have a growing community of `blogdown` users helping each other with feedback, suggestions, and troubleshooting.

**Comment by romainfrancois** [comment]
![home](https://cloud.githubusercontent.com/assets/2625526/26580838/236f4952-453a-11e7-88ef-7bed0da86354.png)
![post](https://cloud.githubusercontent.com/assets/2625526/26580836/236df9c6-453a-11e7-84f0-81a90b8a44d2.png)
![gallery](https://cloud.githubusercontent.com/assets/2625526/26580837/236eb956-453a-11e7-9636-8f8fc3859e3a.png)
![recent_posts](https://cloud.githubusercontent.com/assets/2625526/26580839/236e5bf0-453a-11e7-9c36-eb921dca266c.png)

**Comment by thercast** [comment]
Your post is now online and looks fantastic!  I'll close this issue now.

**Comment by romainfrancois** [comment]
Thanks for the help :-)
