### ISSUE TITLE
Request rbind.io subdomain

### ISSUE THREAD

**Issue by jbaileyh** [rbind/support#160]
Hello, it would be great to get an rbind subdomain. If possible.

My Netlify website address is:

jbaileyh.netlify.com

and my preferred rbind.io subdomain would be:

jbaileyh.rbind.io

best regards,

Joseph

**Comment by road2stat** [comment]
@jbaileyh - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by jbaileyh** [comment]
Excellent thanks!
