### ISSUE TITLE
Request for rbind.io subdomain

### ISSUE THREAD

**Issue by lerban** [rbind/support#161]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

lerban.netlify.com

### Preferred rbind.io subdomain

lerban.rbind.io

**Comment by road2stat** [comment]
@lerban - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
