### ISSUE TITLE
New website with blogdown

### ISSUE THREAD

**Issue by mamaciasq** [rbind/support#164]
Hi @yihui and rbind support team! I have worked for a few months with the RStudio tools. I have done a few great things with bookdown, htmlwidgets and so on and now I am learning blogdown because I wish to work with web pages. I would appreciate if you can send me an invitation to join rbind. Thanks in advance! Martin

**Comment by road2stat** [comment]
@mamaciasq - welcome to rbind! Invitation sent. Please check email. Just let us know when you need a rbind.io subdomain. -Nan

**Comment by mamaciasq** [comment]
Thanks a lot, Nan

**Comment by road2stat** [comment]
@mamaciasq -cool! What's your Netlify website address? So we could point the subdomain to the site.

**Comment by mamaciasq** [comment]
martin.netlify.com

**Comment by road2stat** [comment]
@mamaciasq - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by mamaciasq** [comment]
Thanks a lot! ;-)
