### ISSUE TITLE
Website for Jan de Leeuw

### ISSUE THREAD

**Issue by yihui** [rbind/support#17]
@thercast Could you help @deleeuw set up a website here?

- Repo name: deleeuw
- Theme: https://github.com/lambdafu/hugo-finite
- Netlify subdomain `deleeuw.netlify.com` if possible (let me know if not)
    - add the custom domain `deleeuw.rbind.io`
    - enable HTTPS
    - add `deleeuw@stat.ucla.edu` as a collaborator

Thanks!

**Comment by thercast** [comment]
The site has been deployed successfully!  Address is <https://deleeuw.rbind.io/> and @deleeuw has been added as a collaborator.  @yihui please check to see if I missed anything in the process.

**Comment by yihui** [comment]
That is perfect. Thanks!
