### ISSUE TITLE
rbind.io request

### ISSUE THREAD

**Issue by middleprofessor** [rbind/support#171]
I'd very much like an rbind.io domain for a new blog. The focus will be "R Doodles" for implementing statistical best practices in biology.

Hugo theme is tranquilpeaks

### Netlify website address

rdoodles.netlify.com

### Preferred rbind.io subdomain

rdoodles.rbind.io

The site is live

Cheers! Jeff

**Comment by road2stat** [comment]
@middleprofessor Hi Jeff, - nice site! We have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by middleprofessor** [comment]
Thanks!
