### ISSUE TITLE
rbind.io request

### ISSUE THREAD

**Issue by nllspc** [rbind/support#172]
Thank you for the service!

### Netlify website address

erbo.netlify.com

### Preferred rbind.io subdomain

erbo.rbind.io

Now, do I go to netlify --> add custom domain --> erbo.rbind.io ?

**Comment by road2stat** [comment]
@nllspc - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
