### ISSUE TITLE
rbind.io domain request

### ISSUE THREAD

**Issue by the-Hull** [rbind/support#178]
Dear support team, I'd please like to get one of these rbind.io's also. Thanks so much!

### Netlify website address

affectionate-turing-70b3b0.netlify.com/

### Preferred rbind.io subdomain

aglhurley.rbind.io

**Comment by road2stat** [comment]
@the-Hull - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by the-Hull** [comment]
Thanks @road2stat - the R community/rbind.io/RStudio is fantastic. A notification on Netlify is warning me about DNS certificates taking up 24 h to be in effect after set-up. I'll wait until tonight (CET) and will report back, as the subdomain is not yet working (despite changing baseurl). In any case - fantastic, and thanks again!

**Comment by road2stat** [comment]
-great! Glad it works!
-Nan
