### ISSUE TITLE
rbind.io domain request

### ISSUE THREAD

**Issue by XUKEREN** [rbind/support#179]
Dear support team, I'd like to get one rbind.io. Thank you so much!

Netlify website address:
https://brave-bose-2b6b05.netlify.com/

Preferred rbind.io subdomain

xukeren.rbind.io

**Comment by road2stat** [comment]
@XUKEREN - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by XUKEREN** [comment]
Works! Thank you very much!
