### ISSUE TITLE
New Blogging Website

### ISSUE THREAD

**Issue by kgilds** [rbind/support#18]
I would love to get started with blog down and use R studio to generate content. I will need a domain name.

Thanks

**Comment by kgilds** [comment]
preferred subdomain: kgilds
Netlify subdomain: https://private-layer-43278.netlify.com/

**Comment by yihui** [comment]
Done.

**Comment by thercast** [comment]
@kgilds Just checking to see if everything is working as expected?  If so let me know and we can close the issue.  Welcome aboard!

**Comment by yihui** [comment]
@kgilds You have to configure the domain to kgilds.rbind.io on Netlify:

![](https://cloud.githubusercontent.com/assets/163582/26532991/e3e5bb40-4453-11e7-9bbb-ad54f5e14d09.png)

**Comment by kgilds** [comment]
@yihui thanks done.

**Comment by kgilds** [comment]
@thercast  thanks ; everything is set up now that I configured to the new domain. Feel free to close.

**Comment by yihui** [comment]
I'm not sure if it is due to delay in my browser, but http://kgilds.rbind.io does not seem to work for me. Are you sure you configured the custom domain on Netlify?

**Comment by yihui** [comment]
BTW, please feel free to transfer https://github.com/kgilds/kwgsite to rbind (like others did) if you like.

**Comment by kgilds** [comment]
Thanks for the catch, I messed that up;  I fixed that and made the request to transfer.

**Comment by drkamarul** [comment]
@yihui @thercast , I think I got the same issue. my rbind repo `https://github.com/rbind/drkamarul` does not contain the updated files and folders (including `public` folder`) as shown below:

![image](https://cloud.githubusercontent.com/assets/6749223/26612823/c831a886-45e9-11e7-96ed-70c7255ef301.png)
 
For your info, I had successfully rendered the page and **netlify** able to show my page  <http://hydrographer-radio-54151.netlify.com/> correctly like here.

![image](https://cloud.githubusercontent.com/assets/6749223/26612930/97316180-45ea-11e7-935f-40846adadb9b.png)

Issues are:

1. Even though I have pushed the changes to the repo using **Sourcetree**, no changes seen on  `https://github.com/rbind/drkamarul` (changes not merged?). 
2. After I save `drkamarul.rbind.io` in the `Custom Domain` page,   

![image](https://cloud.githubusercontent.com/assets/6749223/26612963/d3cd7bec-45ea-11e7-825a-a5b3cfd6a446.png)

![image](https://cloud.githubusercontent.com/assets/6749223/26612996/01fb886a-45eb-11e7-9a7e-8a1a36016655.png)

unfortunately, I got this

![image](https://cloud.githubusercontent.com/assets/6749223/26613004/13ea324c-45eb-11e7-90c2-d8f8c5e131db.png)

**Comment by yihui** [comment]
@drkamarul 1. Your git remote is probably not correct (check with `git remote -v`). 2. You need me to set up the subdomain drkamarul.rbind.io for you, which I just did.

**Comment by drkamarul** [comment]
Thanks @yihui for checking and setting up the subdomain. I run `git remote -v`, this what I got

![image](https://cloud.githubusercontent.com/assets/6749223/26618243/3e22ea4c-460c-11e7-936f-255414bf743b.png)

The site is up and running now which is very exciting. Many2 thanks to everyone esp @yihui and @thercast . Now it is the time to add more post and do some tweakings.
