### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by ronnyhdez** [rbind/support#181]
Hello, this is my subdomain request.
Thank you!

### Netlify website address

https://ronnyhdez.netlify.com/

### Preferred rbind.io subdomain

ronnyhdez.rbind.io

**Comment by road2stat** [comment]
@ronnyhdez - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by road2stat** [comment]
Hi @ronnyhdez , - it looks like the rbind.io subdomain configured in you Netlify settings has an extra `www.` in it, therefore it is not correctly redirected to you Netlify website. Please try to remove the `www.` part in the custom domain settings so it could work properly. -Nan

**Comment by ronnyhdez** [comment]
Thanks Nan! It´s already working!
