### ISSUE TITLE
subdomain request

### ISSUE THREAD

**Issue by alistaire47** [rbind/support#182]
Hi! Could I get alistaire.rbind.io? Details:

### Netlify website address
https://alistaire.netlify.com/

### Preferred rbind.io subdomain
alistaire.rbind.io

### Theme
[Future Imperfect](https://github.com/jpescador/hugo-future-imperfect)

Thanks for setting this up!

Best,
Edward

**Comment by road2stat** [comment]
@alistaire47 - cool website! We have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by alistaire47** [comment]
Awesome, thank you so much!
