### ISSUE TITLE
.rbind.io domain request

### ISSUE THREAD

**Issue by asbates** [rbind/support#186]
I would like to obtain an rbind.io domain. Thanks so much for your help!

### Netlify website address

https://asbates.netlify.com

### Preferred rbind.io subdomain

asbates.rbind.io

**Comment by road2stat** [comment]
@asbates - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
