### ISSUE TITLE
join rbind - I've had a blog

### ISSUE THREAD

**Issue by shrektan** [rbind/support#191]
### Netlify website address

shrektan.netlify.com (I'm using it)

### Preferred rbind.io subdomain

shrektan.rbind.io

Hi, I've had a [blog](https://shrektan.com) using blogdown (here's [the source](https://github.com/shrektan/shrektan_blog)) and I want to join rbind. 

Thanks.

**Comment by road2stat** [comment]
@shrektan - we have configured the rbind subdomain you requested, the organization member invitation was also sent. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by shrektan** [comment]
Thanks for the help. I've set it up successfully.
