### ISSUE TITLE
Updates on my website are not going to rbind

### ISSUE THREAD

**Issue by TiagoVentura** [rbind/support#198]
Hi, 

I built my website with blogdown and hugo. The website in on Netlify, and using the rbind domain. I just did some updates on the website, push to github, but the rbind page is not updating the changes. As you can see in the picture below, the site is deploying so I am not so sure what the problem is here. Any idea?

![image](https://user-images.githubusercontent.com/14006141/39080161-2360f5c4-44f7-11e8-8fa4-f6bd9a6d76c7.png)

**Comment by road2stat** [comment]
Hi @TiagoVentura , - we noticed that the rbind subdomain `tiagoventura.rbind.io` points to `tiagoventura.netlify.com`, but when we open the Netlify address it shows "Not found". Normally it should show the correct, latest content. So, could you please check if this Netlify address is properly configured your Netlify dashboard? Thanks!

**Comment by TiagoVentura** [comment]
Thanks for the answer. But I have already identified the problem. I recently changed my computer, so I had to download a new R, and also install all the packages. One of the packages I use on the website was not installed, then, the public folder was not updating the changes I was doing from my rep. thanks!
