### ISSUE TITLE
Would love rbind subdomain

### ISSUE THREAD

**Issue by DeependraD** [rbind/support#199]
Hey Team! I just deployed my site with default theme over netlify. I would love to have rbind subdomain for the following site. This is my first ever issue opening too! Thanks a lot to R and stats community. :smile: 

### Netlify website address

rookie.netlify.com

### Preferred rbind.io subdomain

rookie.rbind.io

**Comment by road2stat** [comment]
@DeependraD - congrats and welcome! We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by DeependraD** [comment]
Thanks. I appreciate the support.
