### ISSUE TITLE
Rename repo likanzhan.github.io

### ISSUE THREAD

**Issue by yihui** [rbind/support#2]
@likanzhan Could you rename your repo https://github.com/rbind/likanzhan.github.io to something like likan or likanzhan? I'm asking because likanzhan.github.io may be a little confusing (you are no longer hosting the website using Github pages). Thanks!

**Comment by likanzhan** [comment]
I'm new in this area, could you let me know how to change this? Thanks.

**Comment by yihui** [comment]
Sure: https://github.com/rbind/likanzhan.github.io/settings

**Comment by likanzhan** [comment]
Page not found. It seems that I do not have the permission to change it.

**Comment by yihui** [comment]
Ah, sorry about that! Now you are the admin of your repo, and should be able to change it.

**Comment by likanzhan** [comment]
Thanks, and I'm wondering how should I configure the DNS now?
It used to be something like
likanzhan.github.io

**Comment by likanzhan** [comment]
I cannot access my website with `likan.info` now

**Comment by yihui** [comment]
Oh I just realized that your repo was not the Markdown source repo but only the output files. You have at least three different ways to go. Don't worry. I'll help you in a few minutes.

**Comment by yihui** [comment]
The easiest way is to replace the output files with source files in the repo (like what I do in [my repo](https://github.com/rbind/yihui)). But if you don't want to do that, I can provide other solutions.

**Comment by yihui** [comment]
Okay, I figured it out. Basically you need to delete your repo https://github.com/likanzhan/likanzhan.github.io since it conflicts with this one. There is nothing you need to change in DNS.

**Comment by likanzhan** [comment]
Thanks. Actually, the repo under my name was deleted after I transferred the repo to rbind. In that case, if I changed the repo name in rbind from "likanzhan.github.io" to "likanzhan", then I cannot access the website via "likan.info". As I need to use this webpage today, so I added another repo under my name. Sorry for the confusing. Likan

**Comment by yihui** [comment]
No worries. When you do not need emergent access to likan.info, you can try to delete the repo https://github.com/likanzhan/likanzhan.github.io and wait for a few minutes before Github knows that likan.info refers to the repo here in rbind.

**Comment by likanzhan** [comment]
It works now. Thanks. Likan
