### ISSUE TITLE
joining request

### ISSUE THREAD

**Issue by triceraflops** [rbind/support#201]
Could I have one of them rbind.io subdomains please :) 

### Netlify website address

https://triceraflops-blog.netlify.com/

### Preferred rbind.io subdomain

triceraflops.rbind.io

**Comment by road2stat** [comment]
@triceraflops - of course! We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by triceraflops** [comment]
Thanks!
Do you know how long it should take before it's available?

I added www.triceraflops.rbind.io as a custom domain in Netifly, but I can't see it yet. Do I just need to wait a little longer?

**Comment by road2stat** [comment]
@triceraflops - please try removing the `www.` prefix in the custom domain, it should be up right away.

**Comment by triceraflops** [comment]
Oh! Perfect, it's working now. Thanks again!
