### ISSUE TITLE
Request website and subdomain

### ISSUE THREAD

**Issue by GuiyuanLei** [rbind/support#203]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address
Don't have one website yet. I would want to have a website with repo name "glei" under rbind
Theme name: Hugo academic
https://github.com/gcushen/hugo-academic

### Preferred rbind.io subdomain
glei.rbind.io

Cheers,
Guiyuan

**Comment by road2stat** [comment]
@GuiyuanLei - it would be great if you could create the blogdown site repo under your GitHub account and try hosting it with Netlify first. Then we will be happy to assign the subdomain and invite you to the rbind organization to transfer the repo.

**Comment by GuiyuanLei** [comment]
@road2stat, Thanks. I have the site initialized now (https://leig.netlify.com/) and am adding contents. I will let you know once I want to transfer.

**Comment by road2stat** [comment]
@GuiyuanLei - perfect, thanks! That's all we need. We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

You're also invited to the rbind GitHub organization (check the email) -- you should be able to transfer the repo anytime now.

**Comment by GuiyuanLei** [comment]
@road2sta, thanks. I just added http://glei.rbind.io/ subdomain and can access the website. But when I click one post, the link points to *.netlify.com (see below). Do I need to change baseurl in config.toml from "https://glei.netlify.com/" to "https://glei.rbind.io/"?

https://glei.netlify.com/post/2018-04-27-create-a-website-using-blogdown/

Cheers,
Guiyuan

**Comment by road2stat** [comment]
@GuiyuanLei - great! I believe switching the base url in `config.toml` would be the first thing to try since the links generated are all determined by this parameter (by default Hugo uses absolute paths instead of relative paths).
