### ISSUE TITLE
Request for a rbind.io subdomain

### ISSUE THREAD

**Issue by FabianFox** [rbind/support#207]
Hey, 

thanks for the wonderful support and your work for the R-community. I would like to request a rbind.io subdomain with the following specifics:

### Netlify website address

fguelzau.netlify.com

### Preferred rbind.io subdomain

fguelzau.rbind.io

Thanks.

Kind regards,
Fabian

**Comment by road2stat** [comment]
@FabianFox - welcome! We have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by FabianFox** [comment]
@road2stat Thanks so much. The rbind-domain works just fine. I'll try to give back to the community. Best, Fabian
