### ISSUE TITLE
sub-domain request 

### ISSUE THREAD

**Issue by cmg777** [rbind/support#209]
### Netlify website address

carlos-mendez.netlify.com

### Preferred rbind.io subdomain

carlos-mendez.rbind.io

**Comment by road2stat** [comment]
@cmg777 - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by cmg777** [comment]
Thank you very much.
