### ISSUE TITLE
New rbind.io subdomain request

### ISSUE THREAD

**Issue by chunyufen** [rbind/support#210]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

https://chunyufen.netlify.com/

### Preferred rbind.io subdomain

yufen-chun.rbind.io

**Comment by road2stat** [comment]
@chunyufen - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by road2stat** [comment]
Hi @chunyufen - just a follow-up, any issues configuring the subdomain on Netlify? We can help if needed.

**Comment by chunyufen** [comment]
Good afternoon. I need help.
Let me show you 3 4 screen captures.
![screen shot 2018-05-19 at 2 25 07 pm](https://user-images.githubusercontent.com/18733971/40265852-da01dee2-5b72-11e8-9f9c-82e994ce93d6.png)
This was what I had done at Netlify.
Then I changed the baseULR in my local config.toml to the new rhind.io account.
Then local site and Netlify site became ugly. They are: --
![screen shot 2018-05-19 at 2 33 14 pm](https://user-images.githubusercontent.com/18733971/40265864-139c673a-5b73-11e8-8512-acc1d5147136.png)
![screen shot 2018-05-19 at 2 32 15 pm](https://user-images.githubusercontent.com/18733971/40265865-13c918a2-5b73-11e8-92f8-8f24460955df.png)
The original one is like this: --
![screen shot 2018-05-19 at 2 34 41 pm](https://user-images.githubusercontent.com/18733971/40265868-20491820-5b73-11e8-9539-931ba3d7527a.png)
When I click the links shown in the local or the remote site, it said something like 404 error.
I must have done something wrong or I must have omitted to do another thing.
Please advise me and help me.
Thank you very much.
Best wishes.

**Comment by chunyufen** [comment]
Good afternoon, road2stat,
Now, local site works. The menu bar has changed from horizontal to the left hand side.
![screen shot 2018-05-19 at 2 49 56 pm](https://user-images.githubusercontent.com/18733971/40265935-1e3f76fe-5b74-11e8-9ad4-84325b1e43a7.png)
What did I do? I just serve the local site again with RStudio.
But the remote site, i.e. the http://yufen-chun.rbind.io/, remains the same.
![screen shot 2018-05-19 at 2 54 26 pm](https://user-images.githubusercontent.com/18733971/40265956-a311127a-5b74-11e8-961f-96ae0494c97b.png)
Let me wait for your advice.
Best wishes.

**Comment by road2stat** [comment]
@chunyufen - try adding `http://` to the `baseURL` in your `config.toml`:

```
baseURL = "http://yufen-chun.rbind.io"
```

**Comment by chunyufen** [comment]
Good morning. Thank you very much. Your advice works. Your team is GREAT.
Best wishes.
