### ISSUE TITLE
Request for rbind acct

### ISSUE THREAD

**Issue by technocrat** [rbind/support#214]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address
https://technocrat.netlify.com

### Preferred rbind.io subdomain

technocrat.rbind.io

**Comment by road2stat** [comment]
@technocrat We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by technocrat** [comment]
Wow! Thanks. That was quick. I set the rbind.subdomain, so I'm good to, I
think!



On May 21, 2018 at 1:18:02 PM, Nan Xiao (notifications@github.com) wrote:

@technocrat <https://github.com/technocrat> We have configured the rbind
subdomain you requested. Please set the rbind subdomain
<https://support.rbind.io/about/> in your Netlify account.

<https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png>

If you need HTTPS for your rbind.io subdomain, please enable the automatic
TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rbind/support/issues/214#issuecomment-390769557>, or mute
the thread
