### ISSUE TITLE
rbind subdomain request

### ISSUE THREAD

**Issue by alice1020** [rbind/support#215]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

aliceindataland.netlify.com

### Preferred rbind.io subdomain

aliceindataland.rbind.io

Thanks a lot!

**Comment by road2stat** [comment]
@alice1020 We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by road2stat** [comment]
@alice1020 - great! You're surely welcome to transfer the repo to rbind (while you don't have to). Anyway, I've sent the team invitation (check email) so that you will be able transfer the repo anytime.

-Nan

**Comment by alice1020** [comment]
@road2stat thanks a lot!
