### ISSUE TITLE
rbind subdomain request

### ISSUE THREAD

**Issue by josue-rodriguez** [rbind/support#216]
Thank you for this! Much appreciated

### Netlify website address

josue.netlify.com

### Preferred rbind.io subdomain

josue.rbind.io

**Comment by road2stat** [comment]
@josue-rodriguez We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan
