### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by seanangio** [rbind/support#218]
I'd be very grateful for an rbind.io subdomain address.

### Netlify website address

seanangio.netlify.com

### Preferred rbind.io subdomain

sean.rbind.io

(If that's not available: seanangio.rbind.io)

Thanks,

Sean

**Comment by road2stat** [comment]
@seanangio We have configured the rbind subdomain you requested (sean.rbind.io). Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by seanangio** [comment]
Thanks so much!
