### ISSUE TITLE
apply for a new rbind.io subdomain

### ISSUE THREAD

**Issue by Rothdyt** [rbind/support#219]
I'd be appreciate if I could have a bind.io subdomain.

### Netlify website address

roth.netlify.com

### Preferred rbind.io subdomain

roth.rbind.io

If that's not available, please try:
1.  yutong.rbind.io
2. dyt.rbind.io

Thanks for your help.

Best,
yutong

**Comment by road2stat** [comment]
@Rothdyt We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by Rothdyt** [comment]
Thank you!
