### ISSUE TITLE
new website / subdomain request

### ISSUE THREAD

**Issue by JVAdams** [rbind/support#22]
I would like to create a new website using blogdown.  I'm okay with the default Hugo theme.  I plan to have the source on Github.  I would like the subdomain, JVAdams.rbind.io.  I have no experience with Netlify.

**Comment by yiluheihei** [comment]
Hosting your website on Netlify from your Git repository following the steps in [this guid](https://hugodocs.info/hosting-and-deployment/hosting-on-netlify/). Once your website repository is connect with Netlify, Netlify will render your website automatically and  assign a subdomain `*.Netlify.com` to you.

Sending your Netlify subdomain  in this  issue and Rbind organization will assign your desired subdomain `JVAdams.rbind.io` to you. More details on rbind family in [https://support.rbind.io](https://support.rbind.io).

Happy to assist you with any further questions.

**Comment by yihui** [comment]
Thanks @yiluheihei! That is exactly what I hope Rbind family members could do (help newcomers).

@JVAdams I have sent the invite to you to join rbind. We can do the rest of things for you.

@thercast Do you have time to create the repo for @JVAdams and set up Netlify as well? Let me know the Netlify subdomain when you are done. Thanks!

**Comment by thercast** [comment]
I created the repository called [jvadams](https://github.com/rbind/jvadams) with a sample site created fresh from `blogdown`.While it seems like the site was built successfully in Netlify, I can't seem to browse to the site using the address of [`http://jvadams.rbind.io`](https://jvadas.rbind.io/).  The subdomain for the site is `jvadams.rbind.io` and the site is named `jvadams` in Netlify.  @yihui hope I didn't screw anything up!

**Comment by yihui** [comment]
No, you didn't. I have to point the CNAME record to the Netlify subdomain, which I just did. The only thing left on your side is to enable HTTPS on Netlify.

**Comment by thercast** [comment]
Cool, I got https configured so it looks like once the CNAME rreaches TTL we should be all set 👍

**Comment by JVAdams** [comment]
Thank you, @yiluheihei, @thercast, and @yihui.  I can now browse the sample site as both [http://jvadams.rbind.io](http://jvadams.rbind.io) and [https://jvadams.rbind.io](https://jvadams.rbind.io).  Next step, give **blogdown** a try.

**Comment by thercast** [comment]
@JVAdams since the sample site and domain address are working I will close the issue.  Feel free to open another issue or send a note to the rbind/support Gitter channel if you have further questions.  Welcome aboard!
