### ISSUE TITLE
rbind.io domain request

### ISSUE THREAD

**Issue by davidpb90** [rbind/support#221]
Thanks for this community support :)

### Netlify website address

datavid.netlify.com

### Preferred rbind.io subdomain

datavid.rbind.io

**Comment by road2stat** [comment]
@davidpb90 We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan
