### ISSUE TITLE
New rbind.io subdomain request

### ISSUE THREAD

**Issue by tslumley** [rbind/support#222]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

notstatschat.netlify.com/

### Preferred rbind.io subdomain

notstatschat.rbind.io

**Comment by road2stat** [comment]
@tslumley, - welcome to rbind! We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by yihui** [comment]
I also suggest you redirect your *.netlify.com domain to *.rbind.io, like this:
https://github.com/rbind/yihui/blob/4f3c4952/static/_redirects#L8-L9 so your readers don't need to remember two domains.
