### ISSUE TITLE
thanks in advance!

### ISSUE THREAD

**Issue by jcolomb** [rbind/support#226]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

https://zealous-johnson-d4652e.netlify.com

### Preferred rbind.io subdomain

rdm_promotion.rbind.io

**Comment by road2stat** [comment]
@jcolomb - underscores (`_`) are usually not legit characters for a subdomain name, do you want to change it to a hyphen (`-`) maybe?

**Comment by jcolomb** [comment]
hey!
sorry, I always forget that... "RDMpromotion" might be better.

**Comment by road2stat** [comment]
@jcolomb - sure! We have configured the rbind subdomain you requested (rdmpromotion.rbind.io). Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan
