### ISSUE TITLE
Request rbind.io (Thank you)

### ISSUE THREAD

**Issue by mhesselbarth** [rbind/support#227]
I'd be appreciate if I could have a rbind.io subdomain. Thanks in advance

### Netlify website address

mhesselbarth.netlify.com

### Preferred rbind.io subdomain

mhesselbarth.rbind.io

**Comment by road2stat** [comment]
@mhesselbarth We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by mhesselbarth** [comment]
Thanks a lot!
