### ISSUE TITLE
Joining rbind

### ISSUE THREAD

**Issue by drkamarul** [rbind/support#23]
I am a medical epidemiologist. have a website www.myanalytics.com.my where WordPress powers my blog. I write and reblog posts about epidemiology and statistics. I would like to join rbind and migrate from WordPress to hugo. Helps are guidance are very much welcome. 

Cheers. 

Kamarul

**Comment by yiluheihei** [comment]
Welcome to [rbind family](https://support.rbind.io/).

There is a very nice step-by-step [guid](https://github.com/rbind/support/issues/12#issuecomment-299040288) by [thercast](https://github.com/thercast).  And your can see the blogdown book for full details: [https://bookdown.org/yihui/blogdown](https://bookdown.org/yihui/blogdown).

If you have any further questions, please leave a comment here and the rbind family will help you for everything that you might need.

**Comment by drkamarul** [comment]
I have changed my mind. Instead of using my existing webpages, I will create a brand new website using blogdown on HUGO platform. I suppose, someone will send an invite to me and create a repo too.  Thanks

**Comment by thercast** [comment]
@drkamarul we are happy to have you join Rbind!  I created a repository here called [rbind/drkamarul](https://github.com/rbind/drkamarul) and you should be able to make any changes you wish. I started you off with a simple example site produced with `blogdown::new_site()`.  We can also configure your site domain to be part of the Rbind domain free of charge.  All I need is whatever you wish to call the site in the domain (for example something like `drkamarul.rbind.io`) so once you provide me your desired name of the site I can help with the rest.

**Comment by drkamarul** [comment]
@thercast , amazing! I am very much grateful for your help. I will add some more post and see of I can tweak a few more things there. I will keep you updated.

**Comment by drkamarul** [comment]
@thercast , i have added a new post and edited a few things. I had forked and pulled the repo. And then after I had rendered the webpage using `serve_site` function (the public folder created), I pushed the changes the repo (`https://github.com/rbind/drkamarul`). But no new changes seen on the repo. Did I miss anything? Please forgive my inadequate knowledge about github functionality

**Comment by thercast** [comment]
@drkamarul I see a few commits from you in the site repository so that part is working as expected.  I had forgotten to get you set up with the netlify service, but now you have a version of your site available at <http://trader-carelessness-31200.netlify.com/> (this is a random domain assigned by netlify).  But if you give us a desired URL you'd like to have on the `.rbind.io` domain (see my earlier comment in this thread), then we can make that simple change for you.

**Comment by drkamarul** [comment]
@thercast, 
1. my domain is drkamarul.rbind.io which is fine.  
2. every time I click `Addins::serve.site`, should I deploy the `public` folder` to **netlify**?
3. or should I just commit the changes on git and push the changes?

It seems that I need to deploy (copy and paste the `public` folder in Netlify) after every time I have changes (for example add post or delete post).

Or did I miss anything else? 

This is what I get when I checked `git remote -v`

![image](https://cloud.githubusercontent.com/assets/6749223/26667438/d5c735f8-46d7-11e7-9aa0-86c5cc3daaac.png)

**Comment by thercast** [comment]
Thanks @drkamarul .  It looks like we have your site up and running at <http://drkamarul.rbind.io/> and I've gone ahead and updated your repo description to have this URL.  The nice part of netlify is that you do not need to do anything special once you push your changes to the repo master branch.  Netlify is set to automatically re-deploy your site once it detects any update.  Your local Git configuration for your site files looks to be correct.

**Comment by thercast** [comment]
@drkamarul I'll close the issue since your site is successfully deployed, but feel free to re-open if you encounter any problems or questions

**Comment by drkamarul** [comment]
@thercast , thanks for the help. Will add new post the the site.
