### ISSUE TITLE
new domain

### ISSUE THREAD

**Issue by jenrichmond** [rbind/support#232]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

frosty-mahavira-a8b06a.netlify.com

### Preferred rbind.io subdomain

jenrichmond.rbind.io

**Comment by road2stat** [comment]
@jenrichmond - welcome to rbind! We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan
