### ISSUE TITLE
Domain request - thanks!

### ISSUE THREAD

**Issue by WatanabeSmith** [rbind/support#233]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

https://focused-meninsky-4ee1c1.netlify.com

### Preferred rbind.io subdomain

WatanabeSmith.rbind.io

**Comment by road2stat** [comment]
@WatanabeSmith We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by WatanabeSmith** [comment]
Done! Thank you so much @road2stat !
