### ISSUE TITLE
Domain request

### ISSUE THREAD

**Issue by jystatistics** [rbind/support#234]
Hi,

I would like to get subdomain for my site. 

Thank you!

### Netlify website address

thirsty-bardeen-c33805.netlify.com/

### Preferred rbind.io subdomain

jystatistics.rbind.io

**Comment by road2stat** [comment]
@jystatistics We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan
