### ISSUE TITLE
Change in netlify site name

### ISSUE THREAD

**Issue by asimumba** [rbind/support#236]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address
Existing Netlify site name: minister-wolf-23726.netlify.com

### Preferred rbind.io subdomain
Existing subdomain name: https://zedr.rbind.io
Can I have thie https://zedr.rbind.io domain point to zedr.netlify.com?
Thank you.

**Comment by yihui** [comment]
Done.

**Comment by asimumba** [comment]
Thank you @yihui
