### ISSUE TITLE
new rbind.io request

### ISSUE THREAD

**Issue by crazyhottommy** [rbind/support#238]
Hi there,

I just set up my website using blogdown following https://alison.rbind.io/post/up-and-running-with-blogdown/  and plan to migrate my posts from http://crazyhottommy.blogspot.com/ to my new site.

I want to have a rbind.io domain name.

Thanks very much!

### Netlify website address

https://divingintogeneticsandgenomics.netlify.com/

### Preferred rbind.io subdomain

divingintogeneticsandgenomics.rbind.io

Best,
Tommy

**Comment by road2stat** [comment]
@crazyhottommy We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by crazyhottommy** [comment]
@road2stat thanks! following the link, I need to transfer my repo to Rbind group?

<img width="785" alt="screenshot 2018-06-22 17 06 20" src="https://user-images.githubusercontent.com/4106146/41801186-a40807c6-763e-11e8-810e-c7abd237faa0.png">

**Comment by crazyhottommy** [comment]
@road2stat  thanks! now it is working!
