### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by mraess** [rbind/support#239]
Hi,

I would like to request an rbind.io subdomain for my website. Thank you very much!!

### Netlify website address

mraess.netlify.com

### Preferred rbind.io subdomain

mraess.rbind.io

**Comment by road2stat** [comment]
Hi @mraess - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by mraess** [comment]
Nan,

Thanks for the quick response! Much appreciated!

**Comment by mraess** [comment]
Hi,
When I add the subdomain to netlify and to my config.toml, it messes up the website. I'm using the hugo tranquilpeak theme. What am I doing wrong?

**Comment by road2stat** [comment]
@mraess - conceptually, you only need to add the new subdomain on the Netlify dashboard (also, enable the HTTPS support for it to access it with `https://`). No baseurl changes needed for `config.toml` (maybe just try set `relativeurls = true`, so the links would be adaptive to the domain). In this way, you should be able to use both domains to access the website.

**Comment by mraess** [comment]
Yes, that worked! Thanks!

**Comment by road2stat** [comment]
- great!
