### ISSUE TITLE
J.P. Le Cavalier's personal website

### ISSUE THREAD

**Issue by jplecavalier** [rbind/support#240]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address

jplecavalier.netlify.com (not deployed for the moment)

### Preferred rbind.io subdomain

jplecavalier.rbind.io

**Comment by jplecavalier** [comment]
I forgot to mention but I'd like the academic theme. Thanks for your time! 😀

**Comment by road2stat** [comment]
Also... just to clarify, the theme and content of your website are fully controlled by you, this is simply a custom domain name. 😁

**Comment by jplecavalier** [comment]
Thanks! I was confused with the support page for the theme :

![image](https://user-images.githubusercontent.com/21185978/42403188-6c779f3c-814d-11e8-80d1-be69c35f825e.png)

It's my first time creating a website, I'll let you know if I have some problems!

**Comment by jplecavalier** [comment]
Should I do something else now @road2stat or I'm ready to deploy?

![image](https://user-images.githubusercontent.com/21185978/42403541-d7313cdc-814f-11e8-9463-9e54ebbd944a.png)

**Comment by road2stat** [comment]
@jplecavalier - that's it, it's working! Please feel free to deploy.

**Comment by jplecavalier** [comment]
Thanks for the quick support! I'm still a beginner with web deployment, but when I'll be good enough, it will be a pleasure to join the organization and help future new members in their learning.

**Comment by road2stat** [comment]
ok, now I see where the confusion came from -- clearly, I didn't read the rbind support documentation thoroughly, sorry about that... 😅  and thanks @yihui for updating it.

@jplecavalier I've just created a blogdown website for you using the academic theme and invited you to the rbind organization, and set you to be the admin of this repo: https://github.com/rbind/jplecavalier 

The next step(s): please associate your Netlify website with this repo, following the blogdown book's [deployment guidelines](https://bookdown.org/yihui/blogdown/netlify.html).

As always, please just let us know if there are any issues during the configuration. We are happy to have you onboard!

**Comment by jplecavalier** [comment]
@road2stat I had begin my website on my personal GitHub account this morning, is it correct if I keep it there while it's not ready to deploy and move it to rbind when it will be up and running?

Thanks again for the support!

**Comment by road2stat** [comment]
@jplecavalier - sure thing, I've just removed the repo I created (rbind/jplecavalier) to avoid duplication.

On Netlify, you can set the source of the website as any repo you have access to, for the deployment. So you could always keep the repo under your personal account and deploy from there. Or optionally, you could transfer the repo to the rbind organization account and set on Netlify to deploy from here. It's just a matter of choice.

For building websites, I would personally recommend making the website online first and improve gradually, because it's almost impossible to get everything (backend, appearance, content) right at once. If you have a website online already, you will always have the motivations to improve it if something doesn't look right. Think it as a lite version of the iterative method for software development.

**Comment by jplecavalier** [comment]
Thanks @road2stat I will follow your recommendation and make the website online as fast as I can. I'll keep it on my personal GitHub account for the moment, I'll reevaluate the possibility of moving it to the rbind organization later.

Thanks again for the support!

**Comment by road2stat** [comment]
@jplecavalier - just wanna do a regular follow up -- were there any major issues when deploying the website or adding the rbind subdomain? Please just let us know if there were any, so after it's done we will be able to close this ticket. -Nan

**Comment by road2stat** [comment]
Hi @jplecavalier - any progress on creating the website? I'm doing some housekeeping work for the rbind support tickets which are open for a long time. It would be very helpful if you could kindly add the subdomain to your website so that we will be able to close this ticket. -Nan

**Comment by jplecavalier** [comment]
@road2stat - I have a publish a first website. It's still not perfect yet, I will have much more time to spend on it in November. Everything works fine for now. Thanks for the support!

**Comment by road2stat** [comment]
@jplecavalier -wow, the site looks super nice! I'm so happy this has worked out. 👍 Just let us know if you got any questions when building it.
