### ISSUE TITLE
request of a new rbind.io subdomain

### ISSUE THREAD

**Issue by seewe** [rbind/support#242]
Please use this template for new rbind.io subdomain requests. Thank you!
Netlify website address

ewanesergio.netlify.com
Preferred rbind.io subdomain

ewanesergio.rbind.io

Thank you very much

**Comment by yihui** [comment]
Well, you deleted the most important part in the issue template:

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
-thanks @yihui ! Closing this ticket here by having https://github.com/rbind/support/issues/243.
