### ISSUE TITLE
Domain Request

### ISSUE THREAD

**Issue by CharlieSpackman** [rbind/support#244]
Hi there, 

Looking to set up my blog with an rbind.io domain name.

## Netlify website address

https://inspiring-sammet-a1f4d8.netlify.com/

## Preferred rbind.io subdomain

Charlie-Spackman.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

Many thanks!

**Comment by road2stat** [comment]
@CharlieSpackman - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by road2stat** [comment]
@CharlieSpackman - just a hint, I saw an additional `www.` appeared in the redirect  -- to make it work properly, the `www.` part needs to be removed in the Netlify configuration.

**Comment by CharlieSpackman** [comment]
Thanks for your help Nan! Everything seems to be working fine now 

Charlie
