### ISSUE TITLE
Domain request

### ISSUE THREAD

**Issue by isteves** [rbind/support#245]
Hi there, I'm still working on my first blogpost, but I've got my website up on netlify!  I'd love to get an rbind domain.

## Netlify website address

isteves.netlify.com

## Preferred rbind.io subdomain

irene.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@isteves - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by isteves** [comment]
Great, thanks @road2stat!  Do you need more volunteers to help with domain configuration?  Let me know if you do.

**Comment by road2stat** [comment]
- yes, I guess more helping hands would probably be awesome and @yihui can provide more guidance on that.

**Comment by yihui** [comment]
@isteves The more volunteers, the better. Currently the whole rbind world is pretty much on @road2stat's shoulders. I'll email you about the instructions. Thanks!
