### ISSUE TITLE
New request for rbind.io subdomain

### ISSUE THREAD

**Issue by justincbagley** [rbind/support#247]
## Netlify website address

justinbagley.netlify.com

## Preferred rbind.io subdomain

justinbagley.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@justincbagley We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by justincbagley** [comment]
Hi Nan, I know this is closed, but thanks again! Thanks also to Alison Presmanes Hill for pointing out this option in her blog. This was very easy to set up, and I'm proud of my 'rbind.io' custom domain. I will spread the word. ~J
