### ISSUE TITLE
Converting wordpress to .xml and to jekyll - How to run exitwp::xmllint for .xml file (guide for newbies)

### ISSUE THREAD

**Issue by drkamarul** [rbind/support#25]
I refer to this github link <https://github.com/thomasf/exitwp>  and I am using Windows 10.  I have downloaded **exitwp**, exported wordpress blogs and have placed the `.xml` files inside the `wordpress-xml` directory inside `exitwp` folder in my `E` drive. 

I could see see a few files for examples `exitwp`, `html2text` and a few more files BUT I do not know how to proceed to the next steps namely:
1.    Run xmllint on your export file and fix errors if there are.
2.    Run the converter by typing python exitwp.py in the console from the directory of the unzipped archive

Helps are welcome and minimal coding are preferred. 

![image](https://cloud.githubusercontent.com/assets/6749223/26518654/2d30874e-42e7-11e7-8348-d79b980324a1.png)

**Comment by yihui** [comment]
From my experience, running xmllint is optional. Typically the XML file is valid.

You have to open a command window, cd to the directory of exitwp, and run python as a command line. You need a little bit experience with using command-line tools, and Windows is an unfortunate OS if you have never used the command window (shell / terminal) before.

**Comment by drkamarul** [comment]
Will give it a shot... Thanks

**Comment by thercast** [comment]
I've never had great luck running command-line utilities in Windows, so I hope you have better luck than me.  If you run in to problems and would like some assistance, I could easily spin up a linux server and install the exitwp tool to generate your converted site files.

**Comment by drkamarul** [comment]
@thercast , that is very kind of you. For now, I think I will start from zero - meaning I will not migrate my existing webpages to the new platform. This is the best for now. And this is because, my main objective is to have the simplest and most replicable method to create a website, which I then can teach to my doctor of public health students. Majority of them have almost zero knowledge on coding and would probably discouraged if the method is complicated. I would be happy if they can very quickly create a website containing their assignments which mainly consist of statistical analysis using R.

**Comment by thercast** [comment]
Since your site is now live I'll close this issue

**Comment by yihui** [comment]
I have provided this service to those who do not know how to use command-line or run Python scripts: https://github.com/yihui/travis-exitwp

**Comment by drkamarul** [comment]
Excellent. Thanks
