### ISSUE TITLE
request for rbind.io subdomain name

### ISSUE THREAD

**Issue by MarkJThomas** [rbind/support#251]
## Netlify website address

https://mark-j-thomas.netlify.com

## Preferred rbind.io subdomain

MThomas.rbind.io

### Agreement

- [Y] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@MarkJThomas - we have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by road2stat** [comment]
Hi @MarkJThomas - just a friendly reminder that you still need to configure the subdomain on your Netlify dashboard as described above. Please just let us know if you got any questions. -Nan

**Comment by MarkJThomas** [comment]
Hi @road2stat  I added my new domain name to Netifly and deployed it again, it gave me this: https://MThomas.rbind.io. However, when I try to access the link it doesn't work, am I missing something? 
Sorry, technical novice!
Mark

**Comment by yihui** [comment]
@MarkJThomas Could you delete the domain and add it again (then enable HTTPS)?

**Comment by MarkJThomas** [comment]
@yihui  I deleted it and added it again but the HTTPS was already enabled from the last time that I did it and it just says 'Check DNS configuration?

**Comment by yihui** [comment]
Yes, for all future *.rbind.io subdomains, HTTPS should be enabled by default since we have deployed a wildcard SSL certificate.

**Comment by road2stat** [comment]
@yihui - that's very cool... Does that also mean we can just remove the "If you need https to secure your website..." paragraph from the saved reply template for future messages? attn @isteves

**Comment by yihui** [comment]
Yes, I believe so. I have tested it myself, but I hope you can verify it independently, too.

**Comment by yihui** [comment]
BTW, rbind.io was so popular on Netlify that Let's Encrypt actually started to complain, so instead of issuing a different certificate for each individual *.rbind.io subdomain (and renewing everything three months), we will just use the wildcard certificate to put less pressure on Let's Encrypt.

**Comment by MarkJThomas** [comment]
Hi, so I have added it and deployed it, but when I check my site: https://MThomas.rbind.io it comes up as not found?
Sorry for being a tech novice!

**Comment by MarkJThomas** [comment]
![screen shot 2018-07-30 at 12 31 58](https://user-images.githubusercontent.com/41441629/43395074-b43b0480-93f4-11e8-8cca-7180765914c9.png)
![screen shot 2018-07-30 at 12 32 08](https://user-images.githubusercontent.com/41441629/43395082-bbd4857c-93f4-11e8-8177-236c61e33400.png)

**Comment by MarkJThomas** [comment]
here's screenshots to show what it says

**Comment by road2stat** [comment]
@MarkJThomas -  no worries! Not too sure where the issue comes from, but let's figure it out.

I just double-checked the configuration on our side and it shows the correct mapping. Would you mind trying to delete the rbind subdomain (using the drop-down menu by clicking `...`), then re-add it, using the lowercased name (`mthomas.rbind.io`)? Thanks a lot!

**Comment by road2stat** [comment]
Perfect! Glad it works. -Nan

**Comment by isteves** [comment]
@road2stat just read through this--got the memo re: https!
