### ISSUE TITLE
request for rbind.io

### ISSUE THREAD

**Issue by technocrat** [rbind/support#255]
## in deployment
technocrat.netify.com

## Preferred rbind.io subdomain

technocrat.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@technocrat - just wanna follow up and see if you were able to deploy the website and add the subdomain, so that we could close this ticket. Please do let us know if there were anything we could help.

**Comment by technocrat** [comment]
Thanks, I've been pulled into a python snake pit, but I'll give a shout if
I get hung up.

Richard



On August 3, 2018 at 5:48:59 PM, Nan Xiao (notifications@github.com) wrote:

@technocrat <https://github.com/technocrat> - just wanna follow up and see
if you were able to deploy the website and add the subdomain, so that we
could close this ticket. Please do let us know if there were anything we
could help.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rbind/support/issues/255#issuecomment-410409389>, or mute
the thread

**Comment by technocrat** [comment]
All working. Thanks, again. I'm proud to be on the site.



On August 3, 2018 at 6:48:19 PM, Richard Careaga (public@careaga.net) wrote:

Thanks, I've been pulled into a python snake pit, but I'll give a shout if
I get hung up.

Richard



On August 3, 2018 at 5:48:59 PM, Nan Xiao (notifications@github.com) wrote:

@technocrat <https://github.com/technocrat> - just wanna follow up and see
if you were able to deploy the website and add the subdomain, so that we
could close this ticket. Please do let us know if there were anything we
could help.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rbind/support/issues/255#issuecomment-410409389>, or mute
the thread
