### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by taluccia** [rbind/support#256]
## Netlify website address

actalucci.netlify.com

## Preferred rbind.io subdomain

annatalucci.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@taluccia - we have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

After adding the subdomain, you may click the "Force HTTPS" button to enforce all the HTTP traffic to be automatically redirected to HTTPS.

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored.

Thanks!
-Nan
