### ISSUE TITLE
Errors loading "*rbind.io" websites

### ISSUE THREAD

**Issue by asimumba** [rbind/support#260]
Hi, 

Can someone help to diagnose what would be the reason for this message when you try to visit most *.rbind.io websites. Tried to visit sites with both Google Chrome and Mozilla, but still getting security certificates errors. 

https://asimumba.rbind.io

![screenshot](https://user-images.githubusercontent.com/24398851/43685911-915b9e08-98bc-11e8-83aa-9098abb6a2d2.png)

**Comment by recleev** [comment]
I am also experiencing the same issue with my [site](https://amateurdatasci.rbind.io/) and [rbind's support page](https://support.rbind.io/). Someone already reported this in [twitter about a week ago](https://twitter.com/wytham88/status/1024303426979725312l). Must be a recurring issue?

**Comment by recleev** [comment]
I tried deleting and adding it gain, but that did nothing.  I triggered deploy but nothing happened.

Also saw this in my netlify page
![imagen](https://user-images.githubusercontent.com/32282701/43691785-baf37726-9953-11e8-87c9-4d7ddc3461dc.png)
Forcing https did not do anything either after triggering deploy.

I also noticed my `enforce_ssl = false` in my config.toml, set that to true and pushed, nothing happened. I set `enforce_ssl = true`, but nothing happened again.

Then, as if by magic, everything works again, including the [support page](https://support.rbind.io/).

Must be an issue with netlify?

**Comment by yihui** [comment]
@recleev Your site looks good in my browser:

![image](https://user-images.githubusercontent.com/163582/43695992-7b9bc116-9901-11e8-8d61-a722c80ab715.png)

**Comment by recleev** [comment]
@yihui Yes. @asimumba's site is also working now. Still can't make sense what happened.

**Comment by asimumba** [comment]
@recleev Yes, everything seems to be working just fine.

**Comment by asimumba** [comment]
I'm having this issue once more. At present, I'm able to navigate to the landing page, but any attempt to open any other page throws up the error.

**Comment by yihui** [comment]
Did you try to delete and re-add the domain asimumba.rbind.io?

**Comment by asimumba** [comment]
Yes, it is working now. Thank you
