### ISSUE TITLE
configuration problem of support.rbind.io?

### ISSUE THREAD

**Issue by petzi53** [rbind/support#262]
Sometimes when I try to call https://support.rbind.io in my browser I got an error claiming that the owner of the site hasn't configurated it correctly. I have tried with different browser. Sometimes I had to wait a long time, then the page appeared, but other times I only get the error message. What could be wrong?

**Comment by isteves** [comment]
@yihui @road2stat I'm getting this issue, too (also seems similar to #260).  Is this related to the wildcard certificate discussed in #251?  

I went through 10+ rbind domains and a majority of them have this problem.  Do you know of a way to somehow test this systematically and then maybe do a systematic reset?  (My best idea is to run httr::GET on a bunch of rbind domains to identify problematic URL's but not really sure how to address the underlying issue.)

![image](https://user-images.githubusercontent.com/25118334/44013536-d3db6a10-9e7a-11e8-9094-b736bd62e5d9.png)

**Comment by road2stat** [comment]
It's working for me here...

Not sure if there is an SSL certificate or DNS caching issue somewhere (local machines? Cloudflare?). I guess I'll try to switch my network providers and see if the issue happens.

Some of the previously created rbind subdomains didn't have HTTPS enabled. They should be accessible via HTTP without problems, but accessing them via HTTPS might give such errors. We should probably only test the ones that we know had HTTPS enabled before the wildcard certificate was introduced.

**Comment by yihui** [comment]
I have seen this on a few other *.rbind.io sites, too, but it is kind of random. I don't really know what's going on.

**Comment by petzi53** [comment]
@yihui I can confirm that it is random. Sometimes a site is reachable which was not some minutes ago.  But most of the time these problematic sites are not reachable. 

@isteves  Yes, I too experience this problem with the majority of the .rbind sites.

**Comment by isteves** [comment]
@road2stat I imagine support.rbind.io has https enabled?  If it randomly doesn't work, I wonder if the problem may lie elsewhere.  (Though if it doesn't, I guess we need to enable it!)

I'm not entirely sure how the certificates are currently set up, but could it be a problem with rate-limiting? https://letsencrypt.org/docs/rate-limits/

The subdomain weekly limit is pretty high, but perhaps renewals may matter?

> To make sure you can always renew your certificates when you need to, we have a Renewal Exemption to the Certificates per Registered Domain limit. Even if you’ve hit the limit for the week, you can still issue new certificates that count as renewals. An issuance request counts as a renewal if it contains the exact same set of hostnames as a previously issued certificate. This is the same definition used for the Duplicate Certificate limit described above. Renewals are still subject to the Duplicate Certificate limit. Also note: the order of renewals and new issuances matters. To get the maximum possible number of certificates, you must perform all new issuances before renewals during a given time window.

**Comment by yihui** [comment]
I have started talking to @netlify, and will post back once we have got a solution.

**Comment by road2stat** [comment]
@isteves Yes, `support.` has https enabled.

https://labs.rbind.io is a test site I created after the wildcard thing. Now I can see sometimes it's not reachable with a message "labs.rbind.io redirected you too many times. Try clearing your cookies. ERR_TOO_MANY_REDIRECTS". When it's working I can see it has a Cloudflare's free SSL certificate.

Talking to Netlify would be a great idea.

**Comment by yihui** [comment]
I think we are all set now. I have tested all *.rbind.io sites. Only a few cannot be accessed via HTTPS but the certificate was often not the reason (e.g. the domain was not actually added by the site owner to Netlify).

**Comment by road2stat** [comment]
Thanks Yihui for testing this! (that's a lot of sites...) Also tested a dozen and looking good from my network. Let's continue the conversation in case anything irregular happens again. Closing the ticket for now.

**Comment by yihui** [comment]
I used `httr::http_error()` to test them (after I retrieved the list from Cloudflare via its API), and manually inspected the ones that failed.
