### ISSUE TITLE
request for rbind.io

### ISSUE THREAD

**Issue by emitanaka** [rbind/support#265]
## Netlify website address

emitanaka.netlify.com

## Preferred rbind.io subdomain

emitanaka.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by isteves** [comment]
@emitanaka - we have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

After adding the subdomain, you may click the "Force HTTPS" button to enforce all the HTTP traffic to be automatically redirected to HTTPS.

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored.

Thanks!
Irene

**Comment by emitanaka** [comment]
Thank you @isteves ! All working now. Just tried transferring my repository to rbind but got "You don’t have the permission to create repositories on rbind". Would you know what to do here?

**Comment by road2stat** [comment]
@emitanaka - I've just sent the invitation (please check email) so you'll be able to create repos.

**Comment by emitanaka** [comment]
It is all working for me thank you!
