### ISSUE TITLE
Hey, I want to apply for a rbind.io subdomain

### ISSUE THREAD

**Issue by zitao1984** [rbind/support#266]
## Netlify website address

nifty-archimedes-a8d72c.netlify.com

## Preferred rbind.io subdomain

zitaoshen.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@zitao1984 We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored.

Thanks!
-Nan
