### ISSUE TITLE
Rename the hugoLithium repo

### ISSUE THREAD

**Issue by yihui** [rbind/support#27]
Hi @homerhanumat, could you rename the repo https://github.com/rbind/hugoLithium to make it obvious that it is your personal repo? I feel the name hugoLithium is too general (naming is hard). Thanks!

**Comment by homerhanumat** [comment]
I have already tried to do that, but the repo now appears only under rbind (not under github.com/homerhanumat) and on rbind I can't make changes.

**Comment by yihui** [comment]
Sorry. Just made you the admin of this repo.

**Comment by homerhanumat** [comment]
Thanks.  Repo has been renamed.

**Comment by yihui** [comment]
Perfect. Thanks!
