### ISSUE TITLE
Request rbind.io subdomain

### ISSUE THREAD

**Issue by PaulESantos** [rbind/support#273]
## Netlify website address

[paulsanand.netlify.com](https://paulefrensa.netlify.app/)

## Preferred rbind.io subdomain

paulefrensa.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@PaulESantos - underscores (`_`) are usually not legit characters for a subdomain name. Do you want maybe to change it to a hyphen (`-`) or just use `paulesa`?

**Comment by road2stat** [comment]
@PaulESantos - of course. We just have configured the rbind subdomain (`paulefrensa.rbind.io`) you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored.

Thanks!
-Nan

**Comment by PaulESantos** [comment]
Hi @road2stat, I have a few problems I change the subdomain. And the https:// is disabled for the website. how I can configure that.
![image](https://user-images.githubusercontent.com/16847375/44674190-1e86a600-aa70-11e8-9019-bfde9fe9d29b.png)
![image](https://user-images.githubusercontent.com/16847375/44674208-2c3c2b80-aa70-11e8-9137-7991bc4ff6bc.png)
I'm not sure how to fix that problem

**Comment by road2stat** [comment]
@PaulESantos - the subdomain and https are both working correctly as it shows in your screenshots (please ignore the "check DNS configuration" in the first one).

The only issue is from the second screenshot: apparently, the CSS and JS files are not loaded. To fix this, please try changing the `baseurl` in your `config.toml` from `"https://http://paulefrensa.rbind.io/"` to `"https://paulefrensa.rbind.io/"` or `"/"` so that the frontend assets can be loaded correctly.

**Comment by PaulESantos** [comment]
Thanks, @road2stat. I fixed the problem
![image](https://user-images.githubusercontent.com/16847375/44679381-2cdbbe80-aa7e-11e8-807a-4a3c04d84158.png)

**Comment by road2stat** [comment]
-looks great!

**Comment by PaulESantos** [comment]
## Netlify website address

[paulefrensa.netlify.app](https://paulefrensa.netlify.app/)

## Preferred rbind.io subdomain

paulefrensa.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@yihui could you help update the CNAME record for `paulefrensa.rbind.io` to point it to `paulefrensa.netlify.app`? Thanks!

**Comment by yihui** [comment]
That's exactly how the CNAME record is currently configured.

**Comment by PaulESantos** [comment]
Hi @yihui and @nanxstats, thank you for your response. As @yihui mentioned, you helped set up the rbind.io domain for my website. However, I attempted to update to Quarto and deleted the project from Netlify. I am currently working on a new project and endeavoring to recover the paulefrensa.rbind.io domain.

**Comment by nanxstats** [comment]
> That's exactly how the CNAME record is currently configured.

@yihui it looks like paulefrensa.rbind.io currently points to paul**sanand**.netlify.app, not paul**efrensa**.netlify.app, which is the new record requested here. Is that right?

**Comment by yihui** [comment]
Oh sorry, I didn't read carefully. Done now.

**Comment by nanxstats** [comment]
@PaulESantos Please add the custom domain to your new Netlify site. I'm closing this for now.
