### ISSUE TITLE
Request for rbind domain

### ISSUE THREAD

**Issue by Alaburda** [rbind/support#274]
Hello! I have finally started setting up my blog. I still have cleaning up to do but I have started writing my first blog post :) Thank you for all the effort you are putting in to this!

## Netlify website address

https://cocky-neumann-5e5ae0.netlify.com

## Preferred rbind.io subdomain

alaburda.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@Alaburda - looks good and welcome! We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored.

Thanks!
-Nan

**Comment by road2stat** [comment]
Nope, that's it. Happy blogging!
