### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by anguyen1210** [rbind/support#275]
## Netlify website address

mentalBreaks.netlify.com

## Preferred rbind.io subdomain

mentalBreaks.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@anguyen1210 -we're happy to offer the subdomain, while it looks like there is not any content at the Netlify website yet (a soft 404). Would you mind adding something there first, please? Thank you!

**Comment by road2stat** [comment]
@anguyen1210 - perfect, glad to see it works! We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored.

Thanks!
-Nan

**Comment by anguyen1210** [comment]
@road2stat Great, many thanks for your help!
