### ISSUE TITLE
Pietro Delfino’s personal website

### ISSUE THREAD

**Issue by PietroD** [rbind/support#277]
## Netlify website address

https://elegant-spence-20b1b7.netlify.com/

## Preferred rbind.io subdomain

pietrod.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by PietroD** [comment]
Will post mainly content related to my research and R coding stuff, thanks!!

**Comment by road2stat** [comment]
@PietroD - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored.

Thanks!
-Nan

**Comment by PietroD** [comment]
Wonderful thanks so much!
