### ISSUE TITLE
DEPIN WANG's personal website

### ISSUE THREAD

**Issue by wangdepin** [rbind/support#278]
## Netlify website address

depin.netlify.com

## Preferred rbind.io subdomain

depin.rbind.io

### Agreement
thank you very much！
- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@wangdepin -we're happy to offer the subdomain, while it looks like there is not any content at the Netlify website yet (a soft 404). Would you mind adding something there first, please? Thank you!

**Comment by wangdepin** [comment]
@road2stat  I have done it, please try agin.thank you!

**Comment by road2stat** [comment]
@wangdepin - ok, now it looks like the Netlify website (and domain) is added, while the site has not been deploy yet so it still shows a soft 404. Any chance of deploying a website so it shows some content instead of the "not found" page? Thanks a lot!

**Comment by wangdepin** [comment]
Thank you for your patience. Is the Netlify website looks like this: [http://www.depin.com/](url)? If yes, what would i do next? I'm a newbie,thanks a lot!

**Comment by road2stat** [comment]
@wangdepin - you will need to [deploy your website](https://bookdown.org/yihui/blogdown/netlify.html) so that it won't show "Page Not found" when we open `depin.netlify.com`. An example would be https://labs.rbind.io/ but any content will do.

**Comment by wangdepin** [comment]
I have createed a new site https://depinwang.netlify.com/  it can be opened. 
Preferred rbind.io subdomain
depin.rbind.io
thank you so much!

**Comment by road2stat** [comment]
- @wangdepin - perfect! We have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored.

Thanks!

**Comment by wangdepin** [comment]
thank you a lot! I will try it.
