### ISSUE TITLE
Enable automatic SSL certificate update

### ISSUE THREAD

**Issue by asimumba** [rbind/support#279]
Hi, 

I have this issue where I'm getting an error when I add my *rbind.io domain to netflify custom domain setting. 
See the image below for the details.
![screenshot](https://user-images.githubusercontent.com/24398851/45482747-2ec8a180-b74f-11e8-9e51-504bd6d9ea08.png)
![netlify](https://user-images.githubusercontent.com/24398851/45482751-2f613800-b74f-11e8-9334-49fe34fbba5e.png)

How do I add the CNAME to point to *netlify.com domain?

**Comment by road2stat** [comment]
Looks like `asimumba.rbind.io` is using Cloudflare's certificate, meaning it will be auto renewed by CF but not Let's Encrypt on Netlify. So I guess this is normal and can be safely ignored? Can't really say for sure but we can double-check with @yihui ...

**Comment by yihui** [comment]
Yes, feel free to ignore it.

**Comment by asimumba** [comment]
Problem is I can't access the website.

**Comment by road2stat** [comment]
Yeah, I can access it too (Chrome 70, Safari 11.1.2) using the DNS server from local ISP.

We will need a more specific error message to pinpoint the issue, @asimumba any chance of sharing that?

**Comment by asimumba** [comment]
I have cleared my browser cache, but still getting this message from CF. This happens on Mozilla Firefox too.
![screenshot](https://user-images.githubusercontent.com/24398851/45535491-ee286100-b7fe-11e8-916a-80ea780319f0.png)

**Comment by yihui** [comment]
Does it work in Chrome's Incognito Window (or Firefox's Private Window)?

**Comment by asimumba** [comment]
@yihui No.

**Comment by yihui** [comment]
That is weird. I have tested it with more services and all said your website was accessible:

- https://down.com
- https://isitdownorjust.me

Maybe restart your system, or try another computer (if you have one or a friend's computer)?

**Comment by asimumba** [comment]
@yihui I will try to access the site via a different computer. Thanks for your help

**Comment by road2stat** [comment]
From the screenshot it looks like Cloudflare's edge server in Johannesburg is having some caching problems.
