### ISSUE TITLE
New website sub-domain request

### ISSUE THREAD

**Issue by asimumba** [rbind/support#28]
Hi, 
I am requesting for access to transfer my repo to Rbind. My desired sub-domain name is : asimumba.rbind.io.

**Comment by thercast** [comment]
@asimumba I've sent you an invitation to join the Rbind group (you should receive an email shortly).  Once you accept that invite, go ahead and [transfer](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) your site repository and once it is complete we will be glad to configure Netlify to publish your site automatically to `asimumba.rbind.io`.

**Comment by asimumba** [comment]
I want to withdraw the repo called blog and transfer a new one with a descriptive name.

**Comment by asimumba** [comment]
@thercast I want to withdraw the repo called blog and transfer a new one with a descriptive name.

**Comment by yihui** [comment]
@asimumba I have made you the admin of the repo so that you can delete it by yourself.

**Comment by asimumba** [comment]
@yihui great. I hope you can also configure the hosting part for netlify. Thanks in advance

**Comment by thercast** [comment]
@asimumba I see that you have a new repo of [rbind/asimumba](https://github.com/rbind/asimumba) transferred over, so I configured netlify to deploy your site to [asimumba.rbind.io](http://asimumba.rbind.io).  Once the DNS record catches up you should be able to see your new site using the new link.

**Comment by yihui** [comment]
I have configured the rbind.io subdomain. Once HTTPS is enabled on Netlify, you should be ready to go.

**Comment by thercast** [comment]
We should be all set.  @asimumba your site is live at [asimumba.rbind.io](https://asimumba.rbind.io)

**Comment by asimumba** [comment]
@yihui @thercast thanks for the brilliant work. I can't wait to get my R journey a notch higher.

**Comment by thercast** [comment]
I'll close this issue but feel free to reach out to our Rbind community if you have additional questions along the way.  Welcome aboard!
