### ISSUE TITLE
LMoller's subdomain request

### ISSUE THREAD

**Issue by LMoller** [rbind/support#280]
## Netlify website address

https://blissful-bell-4ddc42.netlify.com

## Preferred rbind.io subdomain

lmoller.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@LMoller -we have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored.

Thanks!
-Nan

**Comment by LMoller** [comment]
Thank you very much!

**Comment by LMoller** [comment]
Hi Nan,

When I went to put in the custom domain, I received the following error. Should I contact Netlify? Or do you see something I am doing wrong? Thank you!
![screen shot 2018-09-18 at 10 01 32 am](https://user-images.githubusercontent.com/14356305/45700713-7aea5c00-bb2a-11e8-9c11-6f59b91f5863.png)

**Comment by road2stat** [comment]
@LMoller That's a little unexpected... I just tried on our testing subdomain and it's working. This should be the screen you see when adding the subdomain:

<img width="773" alt="add" src="https://user-images.githubusercontent.com/199363/45705846-9f553100-bb48-11e8-9219-eea6132a6193.png">

I also double-checked the CNAME record on our end and it looks ok. Would you mind trying to add the custom domain again? If it still doesn't work, I guess contacting Netlify support would be the way to go.

**Comment by LMoller** [comment]
Thank you Nan! I was using Safari and tried again with the same result. When I tried to contact Netlify support it wouldn't let me submit a ticket, so I switched to Chrome. Updating the custom domain using Chrome worked! I'm not sure why it would make a difference, but glad it worked. Thanks again for your help.

**Comment by road2stat** [comment]
-glad it works!
