### ISSUE TITLE
Change  Netlify website address

### ISSUE THREAD

**Issue by mwheymans** [rbind/support#281]
## Netlify website address

wizardly-murdock-62e5f7.netlify.com

## Preferred rbind.io subdomain

ADSR4U.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

Thanks
Martijn Heymans

Github name: mwheymans
email: mw.heymans@vumc.nl

**Comment by road2stat** [comment]
@mwheymans We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored.

Thanks!
-Nan

**Comment by mwheymans** [comment]
Thanks!
Martijn

**Comment by road2stat** [comment]
@mwheymans -cool, just a reminder that as the last step, you still need to add the subdomain as a custom domain in the Netlify dashboard.
