### ISSUE TITLE
Change website name

### ISSUE THREAD

**Issue by mwheymans** [rbind/support#282]
## Netlify website address

adsr4u.netlify.com

## Preferred rbind.io subdomain

adsr4u.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

Thanks for changing this
Martijn

**Comment by road2stat** [comment]
-ok, but I'll have to ask @yihui to do that.

**Comment by yihui** [comment]
Done.

The *.netlify.com subdomain doesn't really matter unless you are really going to use it (e.g. you won't use the *.rbind.io domain).

**Comment by mwheymans** [comment]
OK, thanks. So not useful for better recognition to change name to adsr4u.rbind.io

**Comment by road2stat** [comment]
@mwheymans -I would say using the rbind.io subdomain is probably a better branding than using the stock domain offered by Netlify or GitHub Pages.

Most importantly, please **add the custom subdomain** to your site, it only takes 30 seconds to do so:

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

Thank you!

**Comment by mwheymans** [comment]
Did that.

Thanks for your help.

Martijn

Van: Nan Xiao <notifications@github.com>
Verzonden: woensdag 19 september 2018 16:46
Aan: rbind/support <support@noreply.github.com>
CC: Heijmans, M.W. (Martijn) <mw.heymans@vumc.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [rbind/support] Change website name (#282)


@mwheymans<https://github.com/mwheymans> -I would say using the rbind.io subdomain is probably a better branding than using the stock domain offered by Netlify or GitHub Pages.

Most importantly, please add the custom subdomain to your site, it only takes 30 seconds to do so:

[https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png]<https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png>

Thank you!

**Comment by mwheymans** [comment]
Did that.

Thanks for your help.

Martijn
