### ISSUE TITLE
apply for a rbind.io subdomain name

### ISSUE THREAD

**Issue by zhujiedong** [rbind/support#283]
## Netlify website address

https://eager-tesla-1ba0ad.netlify.com/

## Preferred rbind.io subdomain

zhujiedong.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by isteves** [comment]
@zhujiedong - we have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored. 

Let us know in this issue when you've configured your site.

Thanks!
Irene

**Comment by road2stat** [comment]
@zhujiedong - just a friendly reminder: please take a minute and add the custom domain on Netlify:

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

Thanks a lot!
