### ISSUE TITLE
apply for a rbind.io subdomain name

### ISSUE THREAD

**Issue by renrosario** [rbind/support#284]
## Netlify website address

http://renrosario.netlify.com

## Preferred rbind.io subdomain

renrosario.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

### Purpose

This blogdown is the website for our R Users Group in Rosario, Argentina, and we would love to have the rbind.io domain. Thanks!

**Comment by road2stat** [comment]
@renrosario -welcome to rbind! We have just configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored.

Thanks!
-Nan

**Comment by renrosario** [comment]
I just configured the rbind subdomain. Anything else?
Thanks Nan,
Marcos

**Comment by road2stat** [comment]
@renrosario -that's it! But just one thing -- please remove the `www.` part in the custom domain setting so it can work properly. Currently `renrosario.rbind.io` redirects to `www.renrosario.rbind.io`, which doesn't really work.

**Comment by renrosario** [comment]
oh... I see... now I'll have to wait since "We're provisioning a certificate for your site, you cannot change custom domains until that process completes - Netlfiy", but thanks for your prompt support!

**Comment by road2stat** [comment]
@renrosario - maybe just remove the old record, and add a new one with `renrosario.rbind.io`. Conceptually it should be effective right away.

**Comment by renrosario** [comment]
That's right! It's ready now!. Sorry for my lack of knowledge in the area. Thank you so much for your help!!!

**Comment by road2stat** [comment]
-terrific! glad it works!
