### ISSUE TITLE
apply for a rbind.io subdomain name

### ISSUE THREAD

**Issue by rasmusfiskerbang** [rbind/support#285]
## Netlify website address

https://thedword.netlify.com/

## Preferred rbind.io subdomain

thedword.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@rasmusfiskerbang We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored.

Thanks!
-Nan

**Comment by rasmusfiskerbang** [comment]
Thank you!

**Comment by rasmusfiskerbang** [comment]
I don't know if you can help me with this, but when i go to my website, http://thedword.rbind.io/, it says "non-secure". Going to my site setting on netlify, it seems like I need to "Check DNS configuration" in order to get HTTPS, however, this does not seem to work. Have you heard of this issue before?

**Comment by yihui** [comment]
Use https://thedword.rbind.io/

And you may find the last two sections of this post helpful: https://yihui.name/en/2017/11/301-redirect/

**Comment by rasmusfiskerbang** [comment]
Thank you, this works.
