### ISSUE TITLE
apply for rbind.io-subdomain

### ISSUE THREAD

**Issue by henningsway** [rbind/support#286]
## Netlify website address

advanced-r-solutions.netlify.com/

## Preferred rbind.io subdomain

advanced-r-solutions.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@henningsway -we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored.

Thanks!
-Nan

**Comment by henningsway** [comment]
Thank you!

**Comment by henningsway** [comment]
I just tried to enable https by attempting to issue an ssl certificate for the site.

![image](https://user-images.githubusercontent.com/1403304/46908465-616ae300-cf23-11e8-9b7b-37d91ab95a36.png)

Is there a way to change the DNS-configuration so, this becomes possible?

**Comment by road2stat** [comment]
@henningsway -no need to change any configurations, just use https://advanced-r-solutions.rbind.io/. To redirect HTTP to HTTPS automatically for Netlify websites, you may find the last two sections of this post helpful: https://yihui.name/en/2017/11/301-redirect/.

(From: https://github.com/rbind/support/issues/285)
