### ISSUE TITLE
chenhuimin.rbind.io

### ISSUE THREAD

**Issue by chenhuiming0218** [rbind/support#287]
## Netlify website address

example.netlify.com

## Preferred rbind.io subdomain

example.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@chenhuiming0218 -would you mind letting us know the Netlify address of the website, please?

**Comment by road2stat** [comment]
-ok I'm gonna close this for now.

**Comment by chenhuiming0218** [comment]
now that,I have not get to.IF knowed,tell you right.would your mind?
