### ISSUE TITLE
apply for a rbind.io subdomain name

### ISSUE THREAD

**Issue by feichangsweet** [rbind/support#288]
## Netlify website address

feichangsweet.netlify.com

## Preferred rbind.io subdomain

feichang.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by isteves** [comment]
Hi @feichangsweet, the Netlify address seems to be broken.  Have you already published to Netlify?

**Comment by feichangsweet** [comment]
Thank you very much for your reply.I am worried about the deploy failed message I see on Netlify.It prompts：Build script returned non-zero exit code: 255.I am looking for a solution.

**Comment by isteves** [comment]
What other messages does Netlify give you? Perhaps check the hugo version to start: https://discourse.gohugo.io/t/solved-netlify-deployment-errors-yet-nothing-errors-on-localhost/5895

**Comment by feichangsweet** [comment]
> 
> 
> What other messages does Netlify give you? Perhaps check the hugo version to start: https://discourse.gohugo.io/t/solved-netlify-deployment-errors-yet-nothing-errors-on-localhost/5895

I created an environment variable HUGO_VERSION on Netlify,the version 0.20 and the version 0.49.It still does not work.Deploy failed and the other error message is：“ Error: Unable to locate Config file. Perhaps you need to create a new site.  Run `hugo help new` for details. (Config File "config" Not Found in "[/opt/build/repo]")” 
And I found this [https://stackoverflow.com/questions/46924031/deploy-fail-status-on-netlify-but-site-still-deploys]This problem seems to be very similar to my problem. I am reading the documentation on Netlify in the blogdown book and trying to solve this problem.

**Comment by feichangsweet** [comment]
> 
> 
> What other messages does Netlify give you? Perhaps check the hugo version to start: https://discourse.gohugo.io/t/solved-netlify-deployment-errors-yet-nothing-errors-on-localhost/5895

Thank you very much! The site now deploys without any error messages.

**Comment by isteves** [comment]
Hi @feichangsweet glad you were able to troubleshoot some of the issues yourself!  I'm still not able to view your netlify site. Could you check to see if there are other errors? Is the feichangsweet.netlify.com url correct?

**Comment by feichangsweet** [comment]
> Hi @feichangsweet glad you were able to troubleshoot some of the issues yourself! I'm still not able to view your netlify site. Could you check to see if there are other errors? Is the feichangsweet.netlify.com url correct?
I am looking for a solution.When my website can be opened, I will apply again.Thangks a lot.

**Comment by isteves** [comment]
Ok, then I will close this issue for now.  Good luck!
