### ISSUE TITLE
New site for Kevin Cheung

### ISSUE THREAD

**Issue by yihui** [rbind/support#29]
I wonder if anyone has time to create a repo for @dataopt:

```r
blogdown::new_site(theme = "gcushen/hugo-academic")
```

**Comment by thercast** [comment]
I have the site created at the repo [rbind/dataopt](https://github.com/rbind/dataopt) with the auto deploy configured on netlify.  I requested the domain of `dataopt.rbind.io` so we should be good once the cname record is set.

**Comment by yihui** [comment]
I have set the CNAME record. Once you enable HTTPS, I think we are all set. Thanks!

**Comment by thercast** [comment]
All set 👍   

@dataopt your web site files are now in the [rbind/dataopt](https://github.com/rbind/dataopt) repository (you have full access to the repository) and your site will be automatically deployed to [dataopt.rbind.io](http://dataopt.rbind.io/) on every push to your master branch.  Let us know if you need anything else or have any issues working with the site.

**Comment by thercast** [comment]
Closing as it seems everything is working well, but feel free to re-open if you need additional help or have questions.
