### ISSUE TITLE
Change Website name

### ISSUE THREAD

**Issue by mwheymans** [rbind/support#290]
Current Netlify website address
adsr4u.rbind.io

Preferred rbind.io subdomain
missingdatasolutions.rbind.io

Agreement
 By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

Thanks
Martijn Heymans

Github name: mwheymans
email: mw.heymans@vumc.nl

**Comment by yihui** [comment]
Done.

**Comment by mwheymans** [comment]
Great Thanks!

Martijn



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Yihui Xie <notifications@github.com>
Datum: 11-10-18 04:32 (GMT+01:00)
Aan: rbind/support <support@noreply.github.com>
Cc: "Heijmans, M.W. (Martijn)" <mw.heymans@vumc.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [rbind/support] Change Website name (#290)


Done.
