### ISSUE TITLE
new rbind.io subdomain requests

### ISSUE THREAD

**Issue by shaocf** [rbind/support#294]
## Netlify website address

shaocf.netlify.com

## Preferred rbind.io subdomain

shaocf.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@shaocf -just want to confirm if you'd like to have the rbind subdomain or not (since you've closed the issue)?

**Comment by shaocf** [comment]
@road2stat   Yes, I do want to have the rbind subdomain.  I closed the issue because I have not finished website building, now I finish it and send another issue.  Thank you!

**Comment by road2stat** [comment]
@shaocf -great, I've just added the subdomain in your new ticket https://github.com/rbind/support/issues/295.
