### ISSUE TITLE
New rbind domain request

### ISSUE THREAD

**Issue by bjk127** [rbind/support#298]
Hi! I'd like to change my netlify address to an rbind.io subdomain. 

The netlify address is: https://infallible-hugle-81ff83.netlify.com

And my preferred rbind.io subdomain is: 

bkinsella.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

Thanks!
Ben

**Comment by road2stat** [comment]
@bjk127 We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

Note that there might be a hint "Check DNS configuration" in the domain section after adding the rbind subdomain -- it can be safely ignored.

You may find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by bjk127** [comment]
@road2stat Do you know if in the config.toml I need to change it to baseurl = "www.bkinsella.rbind.io/"? I did, but netlify failed to deploy site. Or is it because there is a delay in the creating the domain?

**Comment by yihui** [comment]
This post might be helpful to you: https://yihui.name/en/2018/01/valid-url/

**Comment by bjk127** [comment]
@road2stat Thanks! I already set it up as "http://www.bkinsella.rbind.io" on netlify. So trying to change it back without the www. part... :/

**Comment by road2stat** [comment]
@bjk127 -sure, you can easily remove that custom domain on Netlify, and add `bkinsella.rbind.io` as the custom domain.

**Comment by bjk127** [comment]
Thanks! Though I think I have to wait until they provision a certificate for the old domain with www.
<img width="583" alt="screen shot 2018-11-07 at 1 41 55 pm" src="https://user-images.githubusercontent.com/25569016/48152848-ecc16500-e292-11e8-90be-265ff6e9583d.png">

**Comment by road2stat** [comment]
@bjk127 -there's actually no certificate needed, since we're using a wildcard certificate. You should be able to do it by **remove** the old entry first, and then add a new one without `www`, instead of editing the old entry directly.

**Comment by bjk127** [comment]
@road2stat Got it! Thank you!!!!

**Comment by road2stat** [comment]
@bjk127 -great! Glad it works.
