### ISSUE TITLE
bind.io please

### ISSUE THREAD

**Issue by pgseye** [rbind/support#299]
## Netlify website address

https://nifty-goldberg-962511.netlify.com

## Preferred rbind.io subdomain

psbiostats.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@pgseye -hmm, just one thing I forgot to mention -- please remove the `www.` part in the custom domain setting so it can work properly. You should be able to do it by removing the old entry, and then add a new record (use `psbiostats.rbind.io` directly).

**Comment by pgseye** [comment]
Thank you - I did figure this out after a while of it not working😀

**Comment by road2stat** [comment]
@pgseye -no worries, just I saw it's still redirecting to `www` here. Any chance of getting it fixed?

**Comment by road2stat** [comment]
@pgseye -yes! Now it works perfectly. Thanks for the quick fix! -Nan
