### ISSUE TITLE
requesting subdomain

### ISSUE THREAD

**Issue by drivenvector** [rbind/support#300]
## Netlify website address

https://brave-easley-46a88e.netlify.com

## Preferred rbind.io subdomain

drivenvector.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by isteves** [comment]
Hi @drivenvector, your netlify web address is not working for me. Could you check to make sure your website is properly deployed?

**Comment by drivenvector** [comment]
Hi @isteves!
I dont think I correctly followed the steps in order. To set things right, I have started reading https://bookdown.org/yihui/blogdown/ . It might take me few days to set things up in right manner. Please dont close this PR.

**Comment by road2stat** [comment]
Hi @drivenvector 

-thanks so much for the sending the request and the clarification! We have no intention to discourage anyone but as a good practice we'd like to keep the number of opened issues as few as possible and also keep the support turnaround time as short as possible. So I'm going to close this for now, but you're very welcome to request the subdomain by **reopening this issue** or **creating a new issue** when your website is ready, any time in the future. We will be thrilled to see your blogdown website!

Looking forward,
-Nan
