### ISSUE TITLE
New rbind.io subdomain requests

### ISSUE THREAD

**Issue by drivenvector** [rbind/support#303]
## Netlify website address

saurabhjain.netlify.com

## Preferred rbind.io subdomain

saurabhjain.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

PS: I am still very new to this and need help. I have somehow got the site up and running but it is not as clean as I want it to be. Can someone please help me in setting my blog?

**Comment by road2stat** [comment]
@drivenvector - if by "clean" you meant appearance, here are some [theme recommendations](https://bookdown.org/yihui/blogdown/other-themes.html) in the first chapter of the blogdown book, a more [detailed introduction](https://bookdown.org/yihui/blogdown/themes.html) on configuring themes, and [here](https://themes.gohugo.io/) are hundreds of Hugo themes you can select.

**Comment by road2stat** [comment]
@drivenvector -great! Happy to help.
