### ISSUE TITLE
Please invite me.

### ISSUE THREAD

**Issue by shanmdphd** [rbind/support#31]
I would like to get started with blogdown. Would you please invite me so that I can transfer my repo to rbind? https://github.com/shanmdphd/shanmdphd.rbind.io

Preferred subdomain: shanmdphd
Netlify subdomain: https://shanmdphd.netlify.com/

**Comment by yihui** [comment]
Invited. Subdomain shanmdphd.rbind.io added.

**Comment by shanmdphd** [comment]
Thanks, @yihui.
