### ISSUE TITLE
new rbind.io subdomain requests

### ISSUE THREAD

**Issue by YoichiMukai** [rbind/support#310]
## Netlify website address

yoichi-mukai-2.netlify.com

## Preferred rbind.io subdomain

yoichi_mukai.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@YoichiMukai -cool, no worries. @yihui -would you mind helping us change the cname record for `yoichimukai.rbind.io` and point it to `yoichi-mukai-2.netlify.com`, please? Thanks!

**Comment by yihui** [comment]
Sure. Done!

**Comment by YoichiMukai** [comment]
@road2stat - Thank you!

**Comment by road2stat** [comment]
-awesome, thanks a lot! Closing for now...
