### ISSUE TITLE
Changing the url of my blog again...

### ISSUE THREAD

**Issue by jasonbaik94** [rbind/support#311]
### Current rbind.io subdomain : crossvalidated.rbind.io

Hello rbind team,

I've already changed my blog name once and would like to change it one last time!  

The first change is referenced in #223

I'd like to change it to 

**jsonbaik.rbind.io**

To change the domain on Netlify, I was wondering if I should "Add domain alias"? My Netlify domain settings are a bit different from the one on the help page (https://support.rbind.io/about/) because I've already changed mine once!

<img width="977" alt="screen shot 2018-12-03 at 2 09 38 pm" src="https://user-images.githubusercontent.com/28586264/49395952-ded1f900-f705-11e8-9b6e-4e5276e69805.png">

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@jasonbaik94 -you sure it's `json` but not `jason`? 😄 

Please remove the two existing `.rbind.io` records. So we can remove them from our end too for housekeeping purposes. Then we'll just add a new subdomain you just requested (pending json or jason)... then you can add the new subdomain there.

**Comment by jasonbaik94** [comment]
Haha good point. I purposefully chose `jsonbaik` because that's my Twitter handle and I'm a nerd :)

**Comment by jasonbaik94** [comment]
Nan, I just removed the two existing `.rbind.io` records.


<img width="1413" alt="screen shot 2018-12-03 at 2 33 25 pm" src="https://user-images.githubusercontent.com/28586264/49396985-6c164d00-f708-11e8-95be-d8b7ce818191.png">

**Comment by road2stat** [comment]
@jasonbaik94 -awesome, I like that! 😃 So we have just configured the rbind subdomain (`jsonbaik.rbind.io`) you requested. Like before, please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by road2stat** [comment]
hey @yihui -would you mind helping us remove the records for the two unused subdomains here `crossvalidated` and `jasonbaik94`? Thanks a lot!

**Comment by jasonbaik94** [comment]
Great. I've completed Steps 1 and 2.

 Do you know if I have to change anything inside my blogdown files inside RStudio?

**Comment by road2stat** [comment]
@jasonbaik94 -looks like it's already working: https://jsonbaik.rbind.io/. so I guess you're all set.

Just in case, you can probably update the `baseURL` in `config.toml`: (https://github.com/jasonbaik94/blog/blob/master/config.toml#L1) and also the URL in the header area of the repo (https://github.com/jasonbaik94/blog).

**Comment by jasonbaik94** [comment]
You are so helpful! 

Thanks for everything. Have a good day.

**Comment by yihui** [comment]
@road2stat Done.
