### ISSUE TITLE
request for a rbind.io subdomain

### ISSUE THREAD

**Issue by AntoineSir** [rbind/support#312]
## Netlify website address

antoinesir.netlify.com

## Preferred rbind.io subdomain

antoinesir.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by AntoineSir** [comment]
Hi,

 

Thank you very much for that ! I am new to this world and I’m not sure to understand everything : do I need to do something to be indexed by search engines ? My netlify subdomain was not indexed and I was not able to authentify to Google that the site was mine.

Have a good week-end,

 

Antoine Sireyjol

 

De : Nan Xiao <notifications@github.com> 
Envoyé : vendredi 7 décembre 2018 15:25
À : rbind/support <support@noreply.github.com>
Cc : AntoineSir <antoine.sireyjol@gmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [rbind/support] request for a rbind.io subdomain (#312)

 

@AntoineSir <https://github.com/AntoineSir>  We have configured the rbind subdomain you requested. Please:

1.	Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your subdomain.rbind.io as the record, no www needed.

 <https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png> 

2.	There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.
3.	You may also find the last two sections of this post <https://yihui.name/en/2017/11/301-redirect/>  helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by road2stat** [comment]
@AntoineSir -maybe it's not my place to say this, but conceptually: you can add your site in webmaster tools and verify your site's ownership via several methods: https://support.google.com/webmasters/answer/35179 The upload HTML and the meta tag method are both possible for your case.

**Comment by AntoineSir** [comment]
Thank you very much for your reply and your help. I had uploaded successfully the HTML authentification (here : http://antoinesir.rbind.io/google97f73df960210299/) but Google doesn’t recognize it. Time for more researches I guess…

Thanks again !

 

De : Nan Xiao <notifications@github.com> 
Envoyé : vendredi 7 décembre 2018 17:02
À : rbind/support <support@noreply.github.com>
Cc : AntoineSir <antoine.sireyjol@gmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [rbind/support] request for a rbind.io subdomain (#312)

 

@AntoineSir <https://github.com/AntoineSir>  -maybe it's not my place to say this, but conceptually: you can add your site in webmaster tools and verify your site's ownership via several methods: https://support.google.com/webmasters/answer/35179 The upload HTML and the meta tag method are both possible for your case.

**Comment by road2stat** [comment]
@AntoineSir -it should be the html link http://antoinesir.rbind.io/google97f73df960210299.html directly.
