### ISSUE TITLE
My Desired Subdomain Name Request

### ISSUE THREAD

**Issue by Rileypj1** [rbind/support#314]
## Netlify website address

rileypj1.netlify.com

## Preferred rbind.io subdomain

rileypj1.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@Rileypj1 We have just configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by road2stat** [comment]
Hey @Rileypj1 -just a reminder to add the custom domain on Netlify.

**Comment by Rileypj1** [comment]
Hi road2stat,
I've added this custom domain. I have another problem unfortunately. My site is already not deploying continuously from netlify. Do you know what the problem might be?

**Comment by road2stat** [comment]
@Rileypj1 -great, looks like the subdomain is working.

For the Netlify issue, I'm not too sure what "not deploying continuously from netlify" means exactly, but I guess you can first go to the "Deploys" tab, click the listed deploy "Production: master@HEAD" and you'll see the previous deploy logs, see if there are any errors there.

Also, check "Settings" - "Build & Deploy" - "Continuous Deployment" following this guide: https://bookdown.org/yihui/blogdown/netlify.html.
