### ISSUE TITLE
request subdomain

### ISSUE THREAD

**Issue by GregBuck** [rbind/support#319]
## Netlify website address

eloquent-stonebraker-93b0cf.netlify.com

## Preferred rbind.io subdomain

nerkanotebook.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by chuxinyuan** [comment]
> ## Netlify website address
> wsn.netlify.com
> 
> ## Preferred rbind.io subdomain
> ws.rbind.io
> 
> ### Agreement
> * [x]  By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
Hey @GregBuck -just a reminder to add the custom domain on Netlify.
