### ISSUE TITLE
rgo.rbind.io

### ISSUE THREAD

**Issue by romainfrancois** [rbind/support#32]
I'm probably going to write many R and Go posts, so I'm copying (for now) that content into a dedicated site. 

Can I have `rgo.rbind.io` for `http://priest-seal-36447.netlify.com` please.

**Comment by yihui** [comment]
Done. Since you don't have to compete with many other people at the moment in terms of the rbind subdomains, how about just go.rbind.io? Just a suggestion.

**Comment by romainfrancois** [comment]
even better :-)

**Comment by yihui** [comment]
Okay, feel free to use go.rbind.io then. I just set the CNAME record.

**Comment by romainfrancois** [comment]
Thanks. Same as last time, I'll probably noodle around with themes before I talk about it.

**Comment by yihui** [comment]
No problem. Take your time!
