### ISSUE TITLE
subdomain request

### ISSUE THREAD

**Issue by chuxinyuan** [rbind/support#320]
## Netlify website address

wsn.netlify.com

## Preferred rbind.io subdomain

ws.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by yihui** [comment]
I tend to say no.

It's hard to imagine a company cannot afford a domain name, which is typically only $10 per year.

**Comment by road2stat** [comment]
@yihui -makes sense, I'll just close this for now.
