### ISSUE TITLE
Subdomain request

### ISSUE THREAD

**Issue by jrozra200** [rbind/support#321]
## Netlify website address

optimistic-euler-9efb82.netlify.com

## Preferred rbind.io subdomain

jakelearnsdatascience.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
Hi @jrozra200 -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by road2stat** [comment]
Hey @jrozra200 -just a reminder to add the custom domain on Netlify.

**Comment by jrozra200** [comment]
Hi - thank you for following up. I've purchased my own domain and will no longer need the rbind domain. Thank you so much for your assistance and this free service. My apologies for not taking advantage or letting you know sooner.

**Comment by yihui** [comment]
No worries. I have deleted the rbind subdomain accordingly. Thanks!
