### ISSUE TITLE
rbind.io subdomain record for Rubin Wei's site

### ISSUE THREAD

**Issue by thercast** [rbind/support#33]
I have a colleague (Rubin) who has requested to join Rbind and I've set up a repository for his site at [rbind/rubin](https://github.com/rbind/rubin).  Netlify auto-deployment has been configured, and all he needs now is to have a CNAME record set up for `rubin.rbind.io` so we can finish up the process.

**Comment by yihui** [comment]
Done.

**Comment by thercast** [comment]
Thanks!  Everything's looking good and @weirubin  is excited to begin his `blogdown` journey 👍

**Comment by weirubin** [comment]
Thanks @thercast and @yihui. I am excited to start the new journey with `blogdown`.
