### ISSUE TITLE
Subdomain request

### ISSUE THREAD

**Issue by Enchufa2** [rbind/support#330]
## Netlify website address

codingclubuc3m.netlify.com

## Preferred rbind.io subdomain

codingclubuc3m.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by isteves** [comment]
@Enchufa2 - we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
Irene

**Comment by isteves** [comment]
Excellent!

**Comment by Enchufa2** [comment]
This subdomain shows a privacy error, because the certificate is for `*.netlify.app`. Previously, it worked fine. Do you know how to solve this?

**Comment by Enchufa2** [comment]
Never mind. It's working again.

**Comment by nanxstats** [comment]
@Enchufa2 Check this out if the issue persists: https://github.com/rbind/support/issues/797#issuecomment-830434719
