### ISSUE TITLE
Request for sub-domain on rbind to connect it with Netlify

### ISSUE THREAD

**Issue by saschawo** [rbind/support#334]
## Comment

I want to transfer my R-blog Rcrastinate from blogspot to a blogdown-based solution. I am following the advice given in https://bookdown.org/yihui/blogdown/netlify.html to host it on GitHub, make it public with Netlify and using a sub-domain from rbind.io. Thanks for your help!!! This is awesome.

## Netlify website address

practical-allen-412b80.netlify.com/

## Preferred rbind.io subdomain

rcrastinate.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by saschawo** [comment]
And thank you!

**Comment by road2stat** [comment]
-that's great. You're welcome!
