### ISSUE TITLE
Subdomain request

### ISSUE THREAD

**Issue by e-arslan** [rbind/support#335]
## Netlify website address

earslan.netlify.com

## Preferred rbind.io subdomain

earslan.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@e-arslan -we're happy to offer the subdomain, while it looks like there is not any content at the Netlify website yet (a soft 404). Would you mind adding something there first, please? Thank you!

**Comment by road2stat** [comment]
Hey @e-arslan -any chance of adding contents there? If not, we'll probably close this ticket in the next few days.

**Comment by road2stat** [comment]
@e-arslan We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by e-arslan** [comment]
Great, thanks a lot for everything.

**Comment by road2stat** [comment]
You're welcome!
