### ISSUE TITLE
Request to join rbind.io

### ISSUE THREAD

**Issue by CarlvinJerry** [rbind/support#341]
Hello, I am a young data enthusiast working in a fintech company and as a quantitative analysis. I recently started my own blog using blogdown and I just came across rbind.io while research more about blogdown. My current blog is carlvinjerry.github.io and I was wondering if I could be assisted on joining rbind. My main intent is to do research on several topics and blog about them, this will help me grow my profile and my career as well. I have however not set up a netlify account at the moment. Kindly assist. Thanks

## Netlify website address

I do not have one set up yet as I'm still getting familiar to this

## Preferred rbind.io subdomain

beyondrawdata.rbind.io 

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by isteves** [comment]
Hi @CarlvinJerry, I recommend reading through https://bookdown.org/yihui/blogdown/netlify.html to get set up with Netlify. Let us know if you have any questions.

**Comment by road2stat** [comment]
Hey @CarlvinJerry -welcome! You can choose to host your website on Netlify or GitHub Pages freely, and we are happy to offer the rbind subdomain in either case. To move forward:

- If you decided to host the site on GitHub Pages, please check [this doc](https://bookdown.org/yihui/blogdown/github-pages.html), and let us know the website address (maybe `carlvinjerry.github.io`). One particular thing for GitHub Pages is to remember [adding a CNAME file to your repo](https://github.com/rbind/support/issues/139).

- If you decided to host the site on Netlify, please check the doc in Irene's comment above and make sure there are at least some contents there (for example, the site cannot be a 404 page) and just let us know the Netlify website address.

For housekeeping reasons, I will close this issue for now, but please feel free to reopen it or open a new issue to request the subdomain when your website is ready.

Thanks!
-Nan

**Comment by CarlvinJerry** [comment]
Thank you @isteves and @road2stat I have already hosted my website on Github pages. The website address is https://carlvinjerry.github.io  and I have also created the CNAME file you mentioned above. I would therefore like to request for an rbind subdomain under beyondrawdata.rbind.io ,thanks

**Comment by sohelkhanz** [comment]
My netlify address is sohelkhanz.netlify.app 
I want sohelkhan.rbind.io
