### ISSUE TITLE
request for rbind.io subdomain

### ISSUE THREAD

**Issue by CarlvinJerry** [rbind/support#342]
Hello, this is based on issue #341 earlier @isteves and @road2stat I have already hosted my website on Github pages. The website address is https://carlvinjerry.github.io and I have also created the CNAME file you mentioned above. I would therefore like to request for an rbind subdomain under beyondrawdata.rbind.io , thanks

## Preferred rbind.io subdomain

beyondrawdata.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@CarlvinJerry -we have just configured the rbind subdomain you requested. Looks like you're all set!

**Comment by CarlvinJerry** [comment]
Thank you @road2stat
