### ISSUE TITLE
New site request

### ISSUE THREAD

**Issue by EllaKaye** [rbind/support#35]
Hello,

I'd love to be part of the rbind community. I've just got a website up-and-running on netfily (thanks to the awesome blogdown tools @yihui). It's at ellakaye.netlify.com. Could I please have ellakaye.rbind.io? 

Thank you,
Ella

**Comment by yihui** [comment]
Done.

Although it is not required, it will be nice if you could transfer your repo to rbind and share it with the broader community: https://support.rbind.io/about/

**Comment by EllaKaye** [comment]
That Yihui. Very happy to transfer my repo over - I learnt a lot from looking at other rbind repos, so I only hope that others find mine useful too.

Only thing is, currently going to https://ellakaye.rbind.io just shows 'Not Found", even after updating my config.toml file with that address and waiting several minutes. https://ellakaye.netfily.com is still up (though curiously now without the profile picture). Is there anything else I need to do?

Your support is much appreciated!

**Comment by yihui** [comment]
Yes, you have to configure the domain on your side on Netlify: https://support.rbind.io/about/ (scroll to bullet before the screenshot).

**Comment by EllaKaye** [comment]
All done! website up-and-running and repo on rbind. Thanks again, and sorry about getting ahead of myself with my previous comment.

**Comment by yihui** [comment]
No worries. Thanks for joining rbind!
