### ISSUE TITLE
DNS 

### ISSUE THREAD

**Issue by sdiwash** [rbind/support#355]
please  add a CNAME record for diwashrestha pointing to diwashrestha.netlify.com

**Comment by sdiwash** [comment]
add a CNAME record for diwashrestha pointing to diwashrestha.netlify.com

**Comment by road2stat** [comment]
Hi @sdiwash -I think we already did that in https://github.com/rbind/support/issues/349 and it's working -- meaning you can open diwashrestha.rbind.io and it points to the netlify website correctly. Please let us know if you need help with other aspects of this.
