### ISSUE TITLE
Mara's site

### ISSUE THREAD

**Issue by batpigandme** [rbind/support#36]
Hi,
Would love to do my site on rbind.io.

Currently it's at maraaverick.netlify.com, but if I could do the same for rbind (maraaverick subdomain) that would be great.

Thanks for your consideration, and please let me know if there's more info you need!

**Comment by yihui** [comment]
Done.

**Comment by yihui** [comment]
I thought I didn't need to mention this, but apparently I do: https://support.rbind.io/about/ You need to read the third bullet on this page.

BTW, feel free to transfer your source repo to rbind, since you are a member of rbind now.

**Comment by batpigandme** [comment]
Hopefully I configured things correctly this time around. Unfortunately, Netlify isn't letting me switch the source repo to [rbind/waxwings](https://github.com/rbind/waxwings) because I lack admin rights (see below).
![netlify1](http://i.imgur.com/EVHN6ZRl.png)
![netlify2](http://i.imgur.com/xmriM59l.png)
![netlify3](http://i.imgur.com/c04rcrsl.png)

I'm guessing this is why I can't change the description either– I was trying to switch the url there from netlify to rbind.

No rush on any of this— chances are I botched things up when I transfered.

Thanks for all your help.

**Comment by yihui** [comment]
That is my fault. I just promoted you to admin.

In fact, it probably still works even if you do not switch the repo on Netlify, because Github will automatically redirect the old repo to the new one.

**Comment by batpigandme** [comment]
Awesome. Everything's working perfectly now! Thanks for your help, @yihui!

**Comment by yihui** [comment]
Great! Whenever you are ready, please feel free to announce your site at https://support.rbind.io like other people did (no obligation).
