### ISSUE TITLE
subdomain request

### ISSUE THREAD

**Issue by aq92** [rbind/support#362]
## Netlify website address

https://agitated-pike-ff9f1e.netlify.com/

## Preferred rbind.io subdomain

https://qabazard.rbind.io
https://qabazard.netlify.com/

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
Hi @aq92 -sorry we don't have control over your Netlify subdomain, but you can change the `agitated-pike-ff9f1e.netlify.com` domain to `qabazard.netlify.com` yourself easily (click the "Domain settings" button, click `...` on the right side of the Netlify domain, then click "Edit site name").

After you changed it to `qabazard.netlify.com`, we can proceed to point `qabazard.rbind.io` to this address.

**Comment by road2stat** [comment]
hey @aq92 -just want to follow up on this, got any chance to change the netlify subdomain yet? it probably only takes a minute.

**Comment by road2stat** [comment]
Hi @aq92 -just a reminder that we need your action on the Netlify domain before we can assign the rbind subdomain.

**Comment by aq92** [comment]
Hi Nan,

Apologies for the late response. I have decided to use a private domain.

Thank you,
Ahmad

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
