### ISSUE TITLE
requesting subdomain

### ISSUE THREAD

**Issue by byngdeuk** [rbind/support#364]
## Netlify website address

byungdeukwoo.netlify.com

## Preferred rbind.io subdomain

byungdeukwoo.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
Hey @byngdeuk -looks like this is very similar to https://github.com/rbind/support/issues/363, could you please let us know which one do you want to use? Or both? And again, before offering the any of the subdomains you requested, we'd like to see some content on the website, instead of a 404 error. Thank you!

**Comment by byngdeuk** [comment]
Thank you for answering my question! 
I prefer "byungdeukwoo.rbind,io". 
This is the website for academic CV, Resume, etc. made from GitHub - Rmarkdown. 
I don't know why there is a "404 error," though..
Thanks!

**Comment by byngdeuk** [comment]
Oh I solve the problem!! Now there is no error!
Thanks.

**Comment by road2stat** [comment]
@byngdeuk -great! We have configured the rbind subdomain (byungdeukwoo.rbind.io) you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan
