### ISSUE TITLE
James website

### ISSUE THREAD

**Issue by blairj09** [rbind/support#37]
Hi,
I've been reading up on blogdown and rbind and would like to host my site on rbind. I'm currently set up on Netlify and have a personal repo I would like to transition to rbind. My Netlify subdomain is batteriesnotincluded.netlify.com

If I could have the subdomain batteriesnotincluded.rbind.io that would be great.

I've been having some issues with my site rendering correctly on Netlify, but I suspect that may be due to the selected theme (although it renders fine locally using blogdown::serve_site()).

Thanks for all your help! If there is further information I need to provide, please let me know.

**Comment by yihui** [comment]
Invite sent. Subdomain has been set up. Please read https://support.rbind.io/about/ to finish the last step.

**Comment by blairj09** [comment]
Thanks! Everything is set up. I wasn't able to point Netlify to the transfered repo, but as mentioned in #36 that shouldn't cause any issues. The only thing left is for me to sort out why the site isn't rendering properly. Thanks again for your help! Once I have everything set up I'll submit a pull request to introduce my site.

**Comment by yihui** [comment]
I have made you the admin.

Your problem should be fairly easy to fix. I'll leave it as an exercise to someone else: https://gitter.im/rbind/support
