### ISSUE TITLE
Repo Transfer

### ISSUE THREAD

**Issue by UTexas80** [rbind/support#372]
Hello,
Can you please help me understand how I can transfer my github repo to rbind?
Thank you.

## github repo:

My github repo is https://github.com/UTexas80/GlenCFalk

## Netlify website address

My current Netlify website address is: https://lucid-goldstine-63b32c.netlify.com

## Preferred rbind.io subdomain

glen.c.falk.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
Hi @UTexas80 -please see https://support.rbind.io/about/ about repo transfer details. We'll invite you as a new member to the rbind GitHub organization and then you'll be able to transfer your repo.

One issue is that your Netlify website address is not currently accessible, could you please double check that to make sure the website is online? Thanks!

**Comment by UTexas80** [comment]
Hello - Thank you for the quick response. I just checked the [**Netify**](https://lucid-goldstine-63b32c.netlify.com) website and I am able to access it online. Are there any additional steps that I need to take?
Regards,
Glen

**Comment by road2stat** [comment]
@UTexas80 -great! I've just sent the invitation for joining rbind, please check the email. Just let me know if you need admin permissions for the new repo after the transfer.

We have also configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by UTexas80** [comment]
Nan - Thank you so much! May I please be granted admin permissions for the new repo? Also, can you please help me understand what url name to use for the custom domain? Will it be glen.c.falk.rbind.io ?
Glen

**Comment by road2stat** [comment]
For sure! Glen, please transfer the repo to rbind first, so that I can then assign you as the repo admin.

Yes, please try adding `glen.c.falk.rbind.io` as the custom domain for your Netlify website. If it works, it should work almost immediately.

**Comment by UTexas80** [comment]
Hi Nan,
In the GitHub Transfer repository window;  for the _New owner's GitHub username_  input box, do I enter "**https://github.com/rbin**" or is "**rbind**" sufficient? 
Thank you

**Comment by road2stat** [comment]
-I guess it's `rbind` since that's a username.

**Comment by UTexas80** [comment]
Thank you Nan, the repo has been transferred to rbind.
I appreciate your assistance,
Have a good day.
Glen

**Comment by road2stat** [comment]
@UTexas80 -you're welcome! It seems the subdomain is working, and you are now admin of the transferred repo. 💯

**Comment by UTexas80** [comment]
Hello Nan - quick question for you. I just updated my website on Github but don't see the changes propagated to my website. This is my first time doing this so can you please help me understand what steps I missed in the process.
Thank you and I look forward to hearing from you.
Glen

**Comment by road2stat** [comment]
@UTexas80 -that's a bit too generic so I can't really provide too much useful information. But in case, here's the general guide for Netlify deployments: https://bookdown.org/yihui/blogdown/netlify.html You might also find the deployment logs useful on Netlify, click "Deploys" -> click "Production: master@HEAD", then you will be able to see the build log and preview "the build".

**Comment by UTexas80** [comment]
Nan - Mea culpa. I should have known better and not get ahead of myself.  A little hubris on my part thinking that "**I** _did this, it should just work._" Right after I posted this it dawned on my to check the netlify documentation and along with your suggestions I was able to resolve the issue by changing the HUGO_VERSION to 0.48. I think (hope) I learned my lesson and will not be so impetus next time and provide better reproducibility. Thank you for your time and consideration.

**Comment by road2stat** [comment]
That's great, glad that works!

**Comment by UTexas80** [comment]
Hi Nan,
How are you. I just updated my glen.c.falk.rbind.io site and I am getting a "Can' connect securely to this page" error message. When I look at my domain settings on Netlify I see a "check DNS configuration" warning message. Do you have any suggestions how I can troubleshoot and resolve this issue?
Thank you,
Glen

**Comment by nanxstats** [comment]
Hi @UTexas80 -as we mentioned before, the "Check DNS configuration" hint can be safely ignored. See proper solution in https://github.com/rbind/support/issues/382.
