### ISSUE TITLE
The entire rbind.io domain is categorized as "Gambling" by Sophos

### ISSUE THREAD

**Issue by samuelcrane** [rbind/support#378]
My office uses Sophos, a major corporate antivirus and web security provider, to monitor web traffic and the rbind.io domain is blocked, categorized as gambling. This means I—and presumably many others—can't view any of the awesome R blogs hosted on the domain when behind Sophos protection. 

Here is a screenshot of what I see when I try to view rbind.io
![D0A-GuLXgAEVXVS](https://user-images.githubusercontent.com/4019845/54484833-3c68fc00-4844-11e9-9767-4f195ae26f94.jpg)

I have filed an issue at the link they provide (https://www.sophos.com/en-us/threat-center/reassessment-request.aspx). No action seems to have been taken thus far. 

I'm not sure what can be done but I thought you should know that you're being blocked by Sophos for gambling.

**Comment by road2stat** [comment]
-thanks @samuelcrane for letting us know and reporting this issue to them. As you believed this is probably a false positive since I think we vetted the content of all the websites at least when the subdomain is being offered, and we will always keep the standard high.

FYI @yihui
