### ISSUE TITLE
gabrielkaiser.rbind.io

### ISSUE THREAD

**Issue by GabrielKaiserQFin** [rbind/support#380]
## Netlify website address

gabrielkaiser.netlify.com

## Preferred rbind.io subdomain

gabrielkaiser.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Hi @GabrielKaiserQFin -we're happy to offer the subdomain, while it looks like there is not any content at the Netlify website yet (a 404 not found). Would you mind adding something there first, please? Thank you!

**Comment by nanxstats** [comment]
@GabrielKaiserQFin -just a reminder.

**Comment by nanxstats** [comment]
@GabrielKaiserQFin -just checking in, any updates on making your awesome website online?

For housekeeping reasons, we will try to wait for one more week before we close this ticket. If so, please feel free to open another ticket anytime to request the subdomain when the website is ready.

**Comment by nanxstats** [comment]
Closing now for no response.
