### ISSUE TITLE
Subdomain request

### ISSUE THREAD

**Issue by Death-Moose** [rbind/support#389]
## Netlify website address

jaredcummings.netlify.com

## Preferred rbind.io subdomain

jarecummings.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@Death-Moose -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by nanxstats** [comment]
@Death-Moose -just a reminder to add the custom rbind subdomain on Netlify.

**Comment by nanxstats** [comment]
@Death-Moose -any chance of adding the rbind subdomain on Netlify? It only takes a minute.

**Comment by nanxstats** [comment]
@Death-Moose -just checking in, any updates on adding the subdomain on Netlify?

For housekeeping reasons, we will try to wait for one more week before we remove the subdomain from our record and close this ticket. If so, please feel free to open another ticket anytime to request the subdomain again when it's ready to be added.

**Comment by Death-Moose** [comment]
Sorry, I've been wrapping my semester up. Would it be possible to change the subdomain? I mistyped it. jaredcummings.rbind.io is the one I wanted, not jarecummings.rbind.io. That is my mistake. I thought I'd set this up a week ago, but the typo got me.

**Comment by yihui** [comment]
Yes. Changed.

**Comment by Death-Moose** [comment]
My netlify site is configured correctly per the instructions, but when I go to jaredcummings.rbind.io it says the server IP address could not be found. Is that something on my end I need to fix?

**Comment by yihui** [comment]
I'm able to open and view your website: https://jaredcummings.rbind.io. Occasionally DNS changes may take a while, but shouldn't be longer than a couple of hours. You can try another computer or a mobile device and see if it works.

**Comment by nanxstats** [comment]
It already works for me, probably a short delay of DNS propagation, so just check again later.

**Comment by Death-Moose** [comment]
I see it now too. Thanks guys!
