### ISSUE TITLE
Netlify error renewing TLS certificate

### ISSUE THREAD

**Issue by atyre2** [rbind/support#393]
I just received the message below from Netlify:
Failed to renew TLS certificate for drewtyre.rbind.io

We tried to renew the TLS certificate for drewtyre.rbind.io but failed. Your TLS certificate is about to expire on Apr 25, 2019, which will impact your site’s availability. We will continue trying to renew it in the next few days.

Error message:

Acme::Client::Error::RateLimited: Error creating new order :: too many new orders recently: see https://letsencrypt.org/docs/rate-limits/

From the troubleshooting guide it seems like this might happen with a lot of subdomains? Is the solution to manually request a renewal or some other networking black magic?

**Comment by nanxstats** [comment]
@yihui -might want to chime in here. Looks like Let's Encrypt hits the rate limit for a subdomain before the wildcard switch. Relevant issues: https://github.com/rbind/support/issues/41 https://github.com/rbind/support/issues/40

**Comment by yihui** [comment]
I believe you can safely ignore the message.

**Comment by atyre2** [comment]
Thanks, If OK I might just leave this open until the apparent deadline passes -- if anything else pops up I'll post it here.

**Comment by nanxstats** [comment]
It looks like the certificate has been successfully renewed (expires July 16, 2019). I'm closing this.
