### ISSUE TITLE
Changes Netlify domain name 

### ISSUE THREAD

**Issue by Ebedthan** [rbind/support#40]
We have a blog create with **blogdown** and **Netlify**. We have now to change the domain name and we want a *.rbind.io domain names. The links to our Netlify site is http://bricklayer-panda-24374.netlify.com/. 

We wan the domain name to be dsan-blog.rbind.io
Thanks you.

**Comment by yihui** [comment]
Done.

**Comment by Ebedthan** [comment]
Thanks you @yihui for adding us and give us the subdomain name. 
After changing the config.toml file i don't get the result expected. Have i miss a step ?

**Comment by yihui** [comment]
[Again](https://github.com/Ebedthan/DSaN-UseR-2017-blog/issues/4), please read https://support.rbind.io/about

**Comment by Ebedthan** [comment]
I am done with this step but i got an error: "Must be unique", When i change the domain name

**Comment by atyre2** [comment]
I am getting the same response from netlify app after clicking the button to change the domain name:
<img width="933" alt="screen shot 2017-07-04 at 4 55 14 pm" src="https://user-images.githubusercontent.com/2787883/27843490-d6e9bd90-60d9-11e7-867b-e4fba404b3e3.png">

Doesn't matter which button I press for DNS. I must have missed a step somewhere else?

**Comment by yihui** [comment]
I cannot reproduce the error. Did you use the domain on another site on Netlify? If not, you may add me (`xie@yihui.name`) as an administrator of your site on Netlify, and I can take a look.

**Comment by atyre2** [comment]
No, this is my first attempt at using netlify. 

If I should use "Use another DNS" do I need to know which DNS to use?

**Comment by yihui** [comment]
@atyre2 Hmm. I don't know what's wrong there. Could you transfer your source repo to rbind and let me retry? You don't need to know anything about DNS. I have set up the correct DNS record for you.  If you do want to know more about these things, you may read https://bookdown.org/yihui/blogdown/domain-name.html

**Comment by yihui** [comment]
@atyre2 Ah. Forget it. Your repo is already here. Sorry.

**Comment by atyre2** [comment]
I had read the sections on domain names, but didn't help me avoid whatever mistake I made that messed it up! Thanks very much for all the followup.

**Comment by yihui** [comment]
That should not make any difference.

**Comment by Ebedthan** [comment]
Hello @yihui i have tried to find out waht problem i have with the DNS name of my blog but cannot find it. 
So i want to change the DNS name from dsan-blog.rbind.io to anicetebou.rbind.io and try again to see if it works.

**Comment by yihui** [comment]
Netlify currently has an issue (see #42). If it cannot be solved in a couple of days, we will have to create the site for you on Netlify. Thanks for your patience!

**Comment by yihui** [comment]
You can contact Netlify support (again please see #42) and they will help you set up your domain.

**Comment by thercast** [comment]
@Ebedthan just checking to see if you had this issue with your site domain resolved?

**Comment by Ebedthan** [comment]
Excuse me a lot @thercast. i've not yet fix this issue, i'm waiting for an answer from Netlify as #42 suggest.

**Comment by Ebedthan** [comment]
It seems like the issue underlined by Netlify was fixed. So i have fix the issue on my side by re-entering the domain name and all is well.

**Comment by Ebedthan** [comment]
@yihui should i close the issue now?

**Comment by yihui** [comment]
Yes.

**Comment by Ebedthan** [comment]
Thanks you a lot @yihui for your help, but before to close the issue I've just one need i you permit. I want to change the name of the domain from dsan-blog.rbind.io to point it to my name aebou.rbind.io ? Because the purpose of the site have changed and i want to use it now as my new blog instead.
Is it possible? thanks you

**Comment by yihui** [comment]
Yes, it is possible. @rbind/matrix can help you.

**Comment by Ebedthan** [comment]
OK thanks

**Comment by yihui** [comment]
Actually since I'm here, I just changed it for you. Please update it on your side accordingly.

**Comment by Ebedthan** [comment]
Great!!  all is well, thanks you @yihui.
