### ISSUE TITLE
requesting subdomain for Drew Tyre's website

### ISSUE THREAD

**Issue by atyre2** [rbind/support#41]
This is both cool and terrifying at the same time!

I would like to use the subdomain drewtyre.rbind.io for the cheap_shots repository.
The site is deployed at http://doctor-badger-84111.netlify.com

Thanks for the invitation, and to everyone for providing great notes on the path!

**Comment by yihui** [comment]
Done. You are welcome!

**Comment by thercast** [comment]
Looks like everything is working for you so we'll close the issue.  Keep us posted if you encounter other issues and welcome to Rbind :+1:
