### ISSUE TITLE
Site not updating 

### ISSUE THREAD

**Issue by asimumba** [rbind/support#43]
Hi, I am having a challenge with my site, when i push new content to my repo, the site doesn't update to accommodate the new stuff. What maybe the causer of such behaviour?  Plus how do I access the site on netlify? Netlify setup was done by @thercast .

**Comment by yihui** [comment]
@thercast should be able to add you as the admin on Netlify so you can see the (error) logs if you tell him your email.

**Comment by asimumba** [comment]
@yihui @thercast my github email: simumbaa21@gmail.com.

**Comment by asimumba** [comment]
The site is up and running smoothly. You can now attend to my second request.

**Comment by thercast** [comment]
@asimumba you should receive an email from Netlify shortly now that you've been added as a site administrator

**Comment by asimumba** [comment]
@thercast everything done. Thank you for your hand.
