### ISSUE TITLE
New Domain request

### ISSUE THREAD

**Issue by mstuart1** [rbind/support#439]
## Netlify website address

https://pensive-minsky-141605.netlify.com

## Preferred rbind.io subdomain

mstuart.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@mstuart1 -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by mstuart1** [comment]
Thank you!

On Jul 16, 2019, at 10:20 AM, Nan Xiao <notifications@github.com<mailto:notifications@github.com>> wrote:


@mstuart1<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmstuart1&data=02%7C01%7Cmichelle.stuart%40rutgers.edu%7Cfac96c4aef9f43ceaa1d08d709f8becf%7Cb92d2b234d35447093ff69aca6632ffe%7C1%7C0%7C636988836264246587&sdata=7llXpj2LxpovM8wC5jZogI6s9g%2FmFYhEl3mejcPGxvs%3D&reserved=0> -we have configured the rbind subdomain you requested. Please:

  1.  Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your subdomain.rbind.io<http://subdomain.rbind.io> as the record, no www needed.

[https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F199363%2F45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png&data=02%7C01%7Cmichelle.stuart%40rutgers.edu%7Cfac96c4aef9f43ceaa1d08d709f8becf%7Cb92d2b234d35447093ff69aca6632ffe%7C1%7C0%7C636988836264256576&sdata=NjvNHvdb7SRpA5UujPmEKbxPpnlf2RWTkcnQfUxrquA%3D&reserved=0>

  1.  There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

  2.  You may also find the last two sections of this post<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyihui.name%2Fen%2F2017%2F11%2F301-redirect%2F&data=02%7C01%7Cmichelle.stuart%40rutgers.edu%7Cfac96c4aef9f43ceaa1d08d709f8becf%7Cb92d2b234d35447093ff69aca6632ffe%7C1%7C0%7C636988836264256576&sdata=Xm09uIeBvM3BwWh1uQHw7SU%2BySd6VibO3Asdeojx4pE%3D&reserved=0> helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan
