### ISSUE TITLE
netlify failed to deploy site after the repo is transferred to rbind

### ISSUE THREAD

**Issue by tcgriffith** [rbind/support#44]
My repo for the blog is named blogsite. now transferred under rbind.

When It's under my personal account, netlify has no problem deploying it. But after I transferred this repo into rbind, I got the following error message that said I don't have admin rights: 

> We couldn’t set up continuous deployment for this repository. This typically happens when you don’t have admin rights to the repository.

Did I miss anything here?

**Comment by yihui** [comment]
After you transfer the repo to rbind, I guess you do not need to create a new site, since Github will automatically redirect your old repo to the new one.

Anyway, we should definitely make you the admin of your own repo. @thercast Could you do it when you have got time? Thanks!

**Comment by thercast** [comment]
@tcgriffith you now have admin access to your repo

**Comment by tcgriffith** [comment]
Thanks, it works smoothly now.
