### ISSUE TITLE
new domain request

### ISSUE THREAD

**Issue by jiwanheo** [rbind/support#441]
## Netlify website address

https://priceless-jang-3e94e7.netlify.com/

## Preferred rbind.io subdomain

jiwanheo.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@jiwanheo -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by jiwanheo** [comment]
Thank you so much!

**Comment by nanxstats** [comment]
@jiwanheo -you're very welcome. The link still shows a 404 though, any issues adding the subdomain on Netlify?

**Comment by jiwanheo** [comment]
@nanxstats I was on a long train ride yesterday, and couldn't access Netlify. I added the subdomain now. I did get an error message on Let’s Encrypt certificate. However, when I go to the website, it is up and running.

**Comment by nanxstats** [comment]
-cool, I can confirm it's working now.

**Comment by jiwanheo** [comment]
Hi @nanxstats I'm trying to add https to my site, and it won't allow me to unless i configure the DNS. Is the solution to this simply adding a _redirects file to my root directory? Thanks for your help

**Comment by nanxstats** [comment]
Hi @jiwanheo,

On HTTPS, please see point 2 in my initial reply: it's already working for the subdomain (https://jiwanheo.rbind.io/), and you can safely ignore the DNS hints/warnings.

On redirect, yes, if you need to redirect HTTP traffic to HTTPS automatically, please follow the solution in point 3 of the initial reply.
