### ISSUE TITLE
rbind Subdomain Request

### ISSUE THREAD

**Issue by sbrocker** [rbind/support#446]
## Netlify website address

brocker.netlify.com

## Preferred rbind.io subdomain

brocker.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@sbrocker -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by sbrocker** [comment]
@nanxstats Hello Nan!

thanks for the fast reply and configuration. It seems like I have successfully added my custom domain.
brocker.rbind.io gives the hint to "check the DNS configuration" as you mentioned - I ignored it.
When I try to access the new domain I have the issue that the theme isn't working properly. 
![rbind1](https://user-images.githubusercontent.com/44430384/62384440-b7605400-b552-11e9-8648-7e368b865c90.PNG)
![rbind2](https://user-images.githubusercontent.com/44430384/62384441-b7605400-b552-11e9-8c5b-070d57026162.PNG)

This is how it does look like in the browser and how it is supposed to look like in RStudio.
I configured the _redirects anyway;
https://brocker.netlify.com/*  https://brocker.rbind.io/:splat  301!
http://brocker.netlify.com/*  https://brocker.rbind.io/:splat  301!

as Yihui advised to.

Is there anything that I missed or did incorrectly?
Thanks again!

Sven

**Comment by nanxstats** [comment]
@sbrocker -when I open the developer tools console:

```
Subresource Integrity: The resource 'https://brocker.netlify.com/css/style.min.568c54a56780af2a70c45272522247710b69dbfc080b315211fb98381e3796f8.css' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced.

brocker.rbind.io/:1 Subresource Integrity: The resource 'https://brocker.netlify.com/js/main.min.35ccbf1cdceb91e4c64c06b5d009d6e2977fafe56beda7762febd4e67528d2ac.js' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced.
```

`crossorigin="anonymous"` is needed for them, see https://stackoverflow.com/questions/35323268/

**Comment by sbrocker** [comment]
@nanxstats Thanks, I didn't think of it! Added it in my config and now it works like a charm!
Also had a quick look at your blog and stumbled over the documentary "Taking the Long View" - beautiful!

Thanks again and all the best
Sven
