### ISSUE TITLE
subdomain for "Swimming in the data lake"

### ISSUE THREAD

**Issue by verajosemanuel** [rbind/support#45]
Please, could you provide a rbind subdomain for my R blog at http://jvera.netlify.com ?
Still testing and tweaking but a place to migrate all my blog posts from medium.

Completely amazed with Blogdown and Hugo!
Thanks for such a piece of art.

**Comment by yihui** [comment]
Yes, please just tell us the subdomain name you prefer.

BTW, I'm glad that you picked the hugo-xmin theme 😁

**Comment by verajosemanuel** [comment]
I think  jvera.rbind.io  is ok. So I don't get attached to blog title in case I want to change it.

hugo-xmin is a **very** good theme. Focused on content, readable, clean, and easy to manage just in some hours reading documentation. Just tweaked adding a summary and a "read me" link in list and it's perfect for my needs.
Many thanks for your work.

**Comment by yihui** [comment]
Done. But currently Netlify seems to have an issue (see #42), so you probably won't be able to use this subdomain unless I create the site for you on Netlify...

**Comment by verajosemanuel** [comment]
ok, very much obliged.

by the way, is there any way of deleting my first test post? deleted from GitHub but Netlify keeps on showing it

**Comment by yihui** [comment]
You should be able to delete any content in your repo, and Netlify should delete it accordingly.

**Comment by verajosemanuel** [comment]
Hit the "must ne unique" issue.

What do you need from me to be able to use bind.io domain ? any setting on my part? some instructions to make arrangements on netlify?

**Comment by yihui** [comment]
Please contact Netlify support. They will help you (see #42).

**Comment by verajosemanuel** [comment]
They have finished setting things up. My domain is working. Thanks a lot Yihui

**Comment by yihui** [comment]
Excellent! Glad to hear that.

**Comment by verajosemanuel** [comment]
a little off topic: I pretend to keep a "spanish version" of all my english posts. any recommended/suggested way of managing the files with your theme?

**Comment by thercast** [comment]
Everything looks to be working well so I'll close for now.  Let us know if you encounter any other issues.
