### ISSUE TITLE
issue with subdomain

### ISSUE THREAD

**Issue by CarlvinJerry** [rbind/support#452]
Hello, after the recent update on Hugo, my website couldn't render due to some deprecated values. I however guessed a workaround by reinstalling my current theme and everything works fine locally. The website renders perfectly locally but not on http://beyondrawdata.rbind.io/ and I'm beginning to think I might have messed up on the subdomain side, any help with this will be appreciated. Here is a link to my source files https://github.com/CarlvinJerry/sources

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@CarlvinJerry -looks like the rbind subdomain points to `carlvinjerry.github.io`. When you open them, they both show a 404 pages from GitHub Pages -- so I think the domain redirect still works. It's also not likely to get 404 from a Hugo theme change.

I would check if something was misconfigured on the hosting part (GitHub Pages), e.g. a recent handle change, repo name change, case-sensitive names, etc.

**Comment by CarlvinJerry** [comment]
Thank you Nan, let me try see what could be wrong on my end. The same has
been mentioned by the Hugo support team as well.

**Comment by CarlvinJerry** [comment]
Hi @nanxstats , I think I sorted out the issue with my git submodules which was causing the problem above. However, https://carlvinjerry.github.io/ works perfectly now but I seem to have lost the custom domain you guys created for the same, https://beyondrawdata.rbind.io/ (still shows 404). Could you please reconfigure this for me?

**Comment by CarlvinJerry** [comment]
@nanxstats  you're right. I had totally forgotten about the CNAME file. It works perfectly now. Thank you for your support.
