### ISSUE TITLE
Investigate intermittent issues of "Invalid SSL Certificate"

### ISSUE THREAD

**Issue by nanxstats** [rbind/support#462]
I know this has been a mysterious issue... so jotting down some information here in case it's helpful. FYI @yihui 

## Context

@huttoncp reported today in https://github.com/rbind/support/issues/461 about the "invalid SSL certificate" issue when accessing an rbind subdomain with an outdated Netlify subdomain.

## Reproduce the issue

I happen to successfully reproduce this issue independently on a reserved experimental subdomain I set up a year ago with the persistently unchanged settings:

Netlify: https://rbind-labs.netlify.com/

<img width="1282" alt="Screen Shot 2019-08-29 at 12 13 33 AM" src="https://user-images.githubusercontent.com/199363/63910289-0e433700-c9f4-11e9-9512-f4f03aa932d2.png">

rbind: https://labs.rbind.io/ (from Boston, MA)

<img width="1282" alt="Screen Shot 2019-08-29 at 12 13 24 AM" src="https://user-images.githubusercontent.com/199363/63910290-11d6be00-c9f4-11e9-8c1e-b74c4457bb94.png">

Surprisingly, this issue is then reproduced on all other rbind.io subdomains, but only intermittently (not showing the error an hour ago).

HTTP (without S) works ok.

## Resolutions tried

- I tried to remove the rbind subdomain on Netlify -> wait a minute and visit labs.rbind.io, now it shows Not Found -> add the rbind subdomain back on Netlify again -> wait a few minutes and visit labs.rbind.io -> still shows Error 526 - Invalid SSL certificate.

- I tried to use the "[additional troubleshooting information](https://support.cloudflare.com/hc/en-us/articles/115003011431#526error)" for Error 526 linked in the above Cloudflare error page to check the SSL certificate for rbind-labs.netlify.com, and the result looks fine to me.

<img width="1077" alt="Screen Shot 2019-08-29 at 12 44 20 AM" src="https://user-images.githubusercontent.com/199363/63910807-303db900-c9f6-11e9-875a-371abb8e955d.png">

## Some hypothesis

- A similar issue was reported previously (https://github.com/rbind/support/issues/279) but cannot be reproduced by Internet users from other locations. It's possible that Cloudflare's edge servers in Philadelphia now may have the same "caching issues" like their Johannesburg servers back then.

  This hypothesis can be validated by checking **if** the invalid certificate issue can be reproduced by users from other locations in the world.

  This is to see if Cloudflare should take some responsibilities in fixing the issue.

- A recent [thread](https://community.netlify.com/t/https-ssl-error-net-err-cert-common-name-invalid/2466/2) on Netlify's support forum about invalid SSL certificates. The response might be relevant, as I quote:

  > Note that one of the main reason that our system will issue an incomplete certificate is when there is a multiple conflicting records for your apex/bare domain or subdomain. Making you don’t have duplicate DNS records should typically help resolve issues like these.

  This is to see if the issue happened mostly on the Netlify side.

**Comment by nanxstats** [comment]
-ok, the issue disappeared today, within 12 hours I think. Intermittent indeed.

I speculate that it might be related to how Cloudflare's servers communicate with Netlify's servers (pretty sure at least one side is responsible), but it's hard to pin down the exact point of failure and get concrete evidence since it's probably CDN over CDN thus hard to trace from a different geolocation at the right time. I'd say let's keep looking at this closely in case it happens again in a larger scale.

**Comment by algunion** [comment]
It seems that this issue is still happening.
 
 My experience is very similar in terms of "intermittent nature".
 
 Is there a know solution at this time?
 
![sslcertissue](https://user-images.githubusercontent.com/3482227/114451743-45be2180-9be0-11eb-8438-23a7f51222d1.PNG)

**Comment by nanxstats** [comment]
@algunion Looks ok on my side. Also looks ok by checking on https://geopeeker.com/ worldwide so perhaps it's just a caching issue somewhere and there is not much we can do right now except for waiting a while.

**Comment by algunion** [comment]
@nanxstats, thanks.

I'll wait. Hopefully it goes away.

I know that reproducing the issue is improbable because of the intermittent nature.

Thanks for taking the time and answering.

**Comment by yihui** [comment]
https://github.com/rbind/support/issues/797#issuecomment-830434719
