### ISSUE TITLE
Request subdomain rbind 

### ISSUE THREAD

**Issue by sevvel108** [rbind/support#464]
## Netlify website address

https://festive-lichterman-a00833.netlify.com

## Preferred rbind.io subdomain

savvy.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@sevvel108 -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by nanxstats** [comment]
hey @sevvel108 just a reminder to add the subdomain on Netlify please.

**Comment by nanxstats** [comment]
@sevvel108 -another reminder -- please add the subdomain on Netlify, thank you!

**Comment by nanxstats** [comment]
@sevvel108 -please add the subdomain on Netlify. If not, we will start removing the subdomain for housekeeping reasons. Thank you!

**Comment by nanxstats** [comment]
Hi @sevvel108 -one last friendly reminder before we proceed to remove the subdomain one week from now, if we still don't see the subdomain added.

**Comment by nanxstats** [comment]
Hi @yihui -I propose we remove the record for `savvy.rbind.io` and close this issue, as we still haven't got any response for a month after multiple reminders.

**Comment by yihui** [comment]
👌 Got you. Removed.
