### ISSUE TITLE
Request subdomain rbind

### ISSUE THREAD

**Issue by myfollowers** [rbind/support#469]
## Netlify website address

rongdong.netlify.com

## Preferred rbind.io subdomain

rongdong.rbind.io

### Agreement

By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Hey @myfollowers -we'd be happy to offer the subdomain, while it looks like there is not any content at the Netlify website yet (a soft 404). Would you mind adding something there first, please? Thank you

**Comment by myfollowers** [comment]
@nanxstats I'm sorry,it's the first to deploy site on the Netlify website, but unluckily ,there were something wrong .I will immediately  solve this problem , and  sincerely thanks your reply.

**Comment by myfollowers** [comment]
@nanxstats Could you please take a look at this [link](rongdong.netlify.com) to see if there are any more questions? 
Netlify website address: rongdong.netlify.com
Thank you

**Comment by nanxstats** [comment]
@myfollowers -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan
