### ISSUE TITLE
Request invite, admin rights, repo transfer approval and custom domain.

### ISSUE THREAD

**Issue by fortunewalla** [rbind/support#47]
1. Request invite & admin rights & repo transfer approval.
2. Site already set up at [https://fw.netlify.com/](https://fw.netlify.com/)
3. Repo at [https://www.github.com/fortunewalla/f/](https://www.github.com/fortunewalla/f/)
4. Request custom domain `f.rbind.io`
5. Using theme `hugo-xmin`. minimal and very functional. Wonderful work! 
6. Site will deal with data analysis.
7. Suggestions: central database / datatable of all sites with tags and metadata to allow easily classification and search for specific topics and research interests.
8. Thanks to everyone who put in the effort to keep this project growing!

**Comment by yihui** [comment]
The invite has been sent. Subdomain has been set. For 7, perhaps you mean #38?

**Comment by yihui** [comment]
For 2, please contact Netlify support. They will help you (see #42).

For 3, I just made you the admin.

**Comment by fortunewalla** [comment]
Contacted Netlify and they assigned the sub-domain. All working now. thanks.
