### ISSUE TITLE
Request Subdomain

### ISSUE THREAD

**Issue by nggyujia** [rbind/support#471]
Hi,

I am writing to request a subdomain:

## Netlify website address

https://cocky-kalam-0070dc.netlify.com

## Preferred rbind.io subdomain

gloriayujiadeng.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

Thanks!

**Comment by nacnudus** [comment]
I think you meant @nggyujia :)

**Comment by nggyujia** [comment]
Oh sorry I meant @nanxstats . Thanks!!

**Comment by nanxstats** [comment]
@nggyujia -great, we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by nggyujia** [comment]
Thanks!

**Comment by nggyujia** [comment]
Sorry for not identifying this before I closed the issue. It looks like now the domain gloriadengyujiadeng.rbind.io is redirecting to the original https://cocky-kalam-0070dc.netlify.com url, instead of showing the rbind.io on the address bar. Any idea of why this is happening and where could I check to make it display the rbind.io url?


Thank you.

**Comment by nggyujia** [comment]
I was able to fix it but there are some other issues with the display. I think it has something to do with the configuration of the theme I used, not the settings on Netlify.
