### ISSUE TITLE
Blogdown stopped updating

### ISSUE THREAD

**Issue by HaoWang47** [rbind/support#472]
# Issue 

I am maintaining Dr. Liu's website, https://pliu.rbind.io/ , but after June 4, the website stopped updating. What is online now is still the old version (Portrait, biography and last-update-dates should have been all updated). I used the addin, serve site, in R and everything looks fine at the local preview window. 

I have googled as much as I can and tried re-install hugo, but it seems possible solutions I found at Stackoverflow did not help.

Also, the source code in GitHub is consistent with my local files. I really do not know what is wrong.

github: https://github.com/rbind/pengliu

# Environment
                         
platform:  x86_64-apple-darwin15.6.0   
arch:  x86_64                      
os:  darwin15.6.0                
system:  x86_64, darwin15.6.0        
status                                     
major:  3                           
minor:  5.2                         
year:  2018                        
month:  12                          
day:  20                          
svn rev:   75870                       
language:  R                           
version.string:  R version 3.5.2 (2018-12-20)
nickname:  Eggshell Igloo    

> blogdown::hugo_version()
[1] ‘0.58.2’

# Errors

*These errors existed before the website stopped updating.*

==> rmarkdown::render_site(encoding = 'UTF-8')

Building sites … WARN 2019/09/14 15:35:03 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2019/09/14 15:35:03 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}.
WARN 2019/09/14 15:35:03 .File.TranslationBaseName on zero object. Wrap it in if or with: {{ with .File }}{{ .TranslationBaseName }}{{ end }}

                   | EN   
+------------------+-----+
  Pages            | 115  
  Paginator pages  |   1  
  Non-page files   |  15  
  Static files     |  11  
  Processed images |   0  
  Aliases          |   5  
  Sitemaps         |   1  
  Cleaned          |   0  

Total in 206 ms

Output created: public/index.html

<br><br>

Thank you very much! 

Hao

email: halewang@iastate.edu
github: HaoWang47

**Comment by nanxstats** [comment]
Hmm, if the site source is updated but the rendered content didn't update, maybe the Netlify build was not triggered properly or the build did not work for some reasons.

I'd first check the deployment logs on Netlify, by clicking "Deploys" -> "Production: master@HEAD", then you could see the build log for the latest commits and preview the build.

**Comment by nanxstats** [comment]
@HaoWang47 -is the problem resolved so that we can close the issue?

**Comment by HaoWang47** [comment]
@nanxstats Unfortunately not yet, the rendered content is still not updated. I am still working on it. Any other suggestions? 

Thanks!

**Comment by nanxstats** [comment]
@HaoWang47 -have you checked the deployment logs first?

**Comment by HaoWang47** [comment]
@nanxstats - I apologize that I am not familiar with Netlify. I googled, and I asked my friend but I am still not sure where I can click "Deploys" -> "Production: master@HEAD". My friend thought I should have that icon in GitHub, but from my GitHub account, I can't find the icon in the GitHub repo 'rbind/pengliu'. Am I on the right track so far? Is it because I am not the owner of the repo?

Thank you Nan!

**Comment by HaoWang47** [comment]
@nanxstats - I checked https://bookdown.org/yihui/blogdown/netlify.html but I have never seen Figure 3.1 before. Also, do I need to sign up a Netlify account to see the deployments log?

Thanks, Nan! I appreciate your help!

**Comment by nanxstats** [comment]
@HaoWang47 

-ok, so here is how the whole thing works: GitHub is only the upstream source of the website, and the website is actually served by Netlify. Each commit in the linked GitHub repo for that Netlify site will be synced to Netlify and trigger a rebuild.

You should create an account on Netlify (can just use their GitHub single sign-on) and ask the owner of the Netlify site to add you to their team so that you can potentially see and manage the site.

<img width="1691" alt="" src="https://user-images.githubusercontent.com/199363/65380947-5cc2b900-dcb4-11e9-915f-48c263b2af2a.png">

**Comment by HaoWang47** [comment]
@nanxstats - 

**Thanks a lot Nan! So the preview of the website on Netlify is updated! Everything is right except for the missing portrait picture (this is not a big issue). A dot after the second bullet under "Interests" is also there, which I added yesterday on purpose to see if the website source code can be updated.** 

<img width="1176" alt="Screen Shot 2019-09-21 at 20 21 50" src="https://user-images.githubusercontent.com/46979321/65381041-cee3cf80-dcad-11e9-915c-d66daf953783.png">

**I did not see any warning or error from the deploy log.** 

8:22:56 PM: Build ready to start
8:22:58 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
8:22:58 PM: build-image tag: v3.3.2
8:22:58 PM: buildbot version: 89a70647dd4caa4f3273ade0957c10d63327cb10
8:22:58 PM: Fetching cached dependencies
8:22:58 PM: Starting to download cache of 92.7MB
8:22:59 PM: Finished downloading cache in 735.043422ms
8:22:59 PM: Starting to extract cache
8:23:02 PM: Finished extracting cache in 2.940955125s
8:23:02 PM: Finished fetching cache in 3.707960665s
8:23:02 PM: Starting to prepare the repo for build
8:23:02 PM: Preparing Git Reference refs/heads/master
8:23:03 PM: Starting build script
8:23:03 PM: Installing dependencies
8:23:03 PM: Started restoring cached node version
8:23:06 PM: Finished restoring cached node version
8:23:07 PM: v10.16.3 is already installed.
8:23:08 PM: Now using node v10.16.3 (npm v6.9.0)
8:23:08 PM: Attempting ruby version 2.6.2, read from environment
8:23:09 PM: Using ruby version 2.6.2
8:23:10 PM: Using PHP version 5.6
8:23:10 PM: Started restoring cached go cache
8:23:10 PM: Finished restoring cached go cache
8:23:10 PM: unset GOOS;
8:23:10 PM: unset GOARCH;
8:23:10 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
8:23:10 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
8:23:10 PM: go version >&2;
8:23:10 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
8:23:10 PM: go version go1.12 linux/amd64
8:23:10 PM: Installing missing commands
8:23:10 PM: Verify run directory
8:23:10 PM: Executing user command: hugo
8:23:10 PM: Building sites …
8:23:10 PM:                    | EN
8:23:10 PM: +
8:23:10 PM: ------------------+-----+
8:23:10 PM:   Pages            | 117
8:23:10 PM:   Paginator pages  |   2
8:23:10 PM:   Non-page files   |  15
8:23:10 PM:   Static files     |  11
8:23:10 PM:   Processed images |   0
8:23:10 PM:   Aliases          |   6
8:23:10 PM:   Sitemaps         |   1
8:23:10 PM:   Cleaned          |
8:23:10 PM:    0
8:23:10 PM: Total in 225 ms
8:23:10 PM: Skipping functions preparation step: no functions directory set
8:23:10 PM: Caching artifacts
8:23:10 PM: Started saving pip cache
8:23:10 PM: Finished saving pip cache
8:23:10 PM: Started saving emacs cask dependencies
8:23:10 PM: Finished saving emacs cask dependencies
8:23:10 PM: Started saving maven dependencies
8:23:10 PM: Finished saving maven dependencies
8:23:10 PM: Started saving boot dependencies
8:23:10 PM: Finished saving boot dependencies
8:23:10 PM: Started saving go dependencies
8:23:10 PM: Finished saving go dependencies
8:23:10 PM: Build script success
8:23:10 PM: Starting to deploy site from 'public'
8:23:10 PM: Creating deploy tree 
8:23:10 PM: 4 new files to upload
8:23:10 PM: 0 new functions to upload
8:23:11 PM: Starting post processing
8:23:13 PM: Post processing done
8:23:13 PM: Site is live
8:23:26 PM: Finished processing build request in 28.280281868s

**Do you know what is the issue?**


Thank you very much for your help and time!
Hao

**Comment by HaoWang47** [comment]
@nanxstats 

The public website is still not updated (pliu.rbind.io).

<img width="1111" alt="Screen Shot 2019-09-21 at 20 32 45" src="https://user-images.githubusercontent.com/46979321/65381092-07d07400-dcaf-11e9-9c14-4de29df12324.png">

**Comment by HaoWang47** [comment]
@nanxstats -
Hi Nan, 

I just want to let you know all I did to this repo. I changed the config.toml month ago, changing baseurl: "pliu.rbind.io/" to publicurl: "pliu.rbind.io/" or baseurl: "pliu.rbind.io". I was learning what all this code means and I did not know these changes might cause some issues. Based on what I can see from Netlify, it seems like the domain of the website is not right. 

<img width="902" alt="Screen Shot 2019-09-21 at 20 42 18" src="https://user-images.githubusercontent.com/46979321/65381180-ab228880-dcb1-11e9-9351-ea33d27243aa.png">
<img width="913" alt="Screen Shot 2019-09-21 at 20 43 13" src="https://user-images.githubusercontent.com/46979321/65381182-afe73c80-dcb1-11e9-883c-805e41a69c4e.png">

What do you think?

Also, I noticed in the pengliu repo there are two masters. I assumed I was working the master/HEAD but somehow I did not. Is this a potential issue?

<img width="583" alt="Screen Shot 2019-09-21 at 20 44 58" src="https://user-images.githubusercontent.com/46979321/65381173-80d0cb00-dcb1-11e9-82b1-46f4d3831516.png">


Thank you very much!

Hao

**Comment by nanxstats** [comment]
@HaoWang47 -ok, now the the reason is clear: `pliu.rbind.io` is pointed to `pliu.netlify.com`, but not `festive-wozniak-b3cf08.netlify.com`.

I guess to fix this on your side, you could find where the `pliu.netlify.com` site is on Netlify and check if the GitHub repo is correctly linked there and properly published.

Or, if you want to use the current Netlify site shown above, first change its Netlify domain to `pliu.netlify.com`, and then add `pliu.rbind.io` as the custom domain. You probably still need to find and retire the old Netlify site anyways because it still occupies the old Netlify subdomain.

The third way is for us to point `pliu.rbind.io` to a new Netlify address.

**Comment by HaoWang47** [comment]
@nanxstats - 
Hi Nan,

So, I checked several things. 

`pliu.netlify.com` is the same as `pliu.rbind.io`.

`festive-wozniak-b3cf08.netlify.com` is the site I created yesterday. Then I have a question, where is the original site? Is it because I am not the first maintainer of this site? Since I can see the original site before. I might mess up something so I "unlinked" `pliu.netlify.com` and the GitHub repo `rbind/pengliu`. 

I believe the site is properly linked to the GitHub repo and site based on updated source code from GitHub is also published. (See the screenshot)

<img width="558" alt="Screen Shot 2019-09-22 at 02 58 21" src="https://user-images.githubusercontent.com/46979321/65384202-decad600-dce4-11e9-9bed-f2b6c03e0ed6.png">

When I tried to change the domain to `pliu.netlify.com`, it shows **This site name is already taken**. I am not sure how to retire the old Netlify site right now on my side since I can not find it, but I can ask Dr. Liu to check her Netlify account (if she has one).

`pliu.rbind.io` is still the `baseurl` in *config.toml* file. So if you could point it to the new Netlify address, I appreciate it! I can change the domain of new Netlify site to `pengliu.Netlify.com` or something else.

Last question, would you know by chance why I have replaced the portrait picture (I deleted the old one, and uploaded a new one with the same name) but the published site still shows the previous one?


Thank you!

Hao

**Comment by nanxstats** [comment]
@HaoWang47 -sure, to make the new site work, please just let us know the preferred Netlify address you change it to (e.g. `pengliu.netlify.com`, if the random name is not preferred), so that we can update the record on our side to point the rbind subdomain to the new Netlify address.

The image link points to `pliu.rbind.io/img/portrait.jpg` which is still `pliu.netlify.com/img/portrait.jpg` served by the old site. This should be fixed automatically when we updated the record to point to the new site.

Optionally, you could figure out on your side where the original site `pliu.netlify.com` is and then archive/remove it. Given the fact that the "site name is already taken" and it's still accessible, it's probably still active under someone's account.

**Comment by HaoWang47** [comment]
@nanxstats -
Hi Nan,

I have changed the name of the site under my Netlify account into `pengliu.netlify.com`. Could you please point `pliu.rbind.io/` to the new site? 

Thank you very much for your help!

Hao

**Comment by nanxstats** [comment]
@yihui -could you please update the cname record for `pliu.rbind.io` to `pengliu.netlify.com`? Thanks!

**Comment by yihui** [comment]
@nanxstats Done.

**Comment by HaoWang47** [comment]
@nanxstats -

Hi Nan,

Is there anything I need to do on my side? I just checked the site `pliu.rbind.io`, which is not updated. But I am very sure `pengliu.netlify.com` is working since I just change the date again to see if it works. Do I need to customize the subdomain of `pengliu.netlify.com` again?

I tried `set up a subdomain`, but an error occurred.

<img width="629" alt="Screen Shot 2019-09-23 at 11 24 27" src="https://user-images.githubusercontent.com/46979321/65444087-f0030800-ddf4-11e9-8f9a-2c16aeeb31ea.png">
<img width="685" alt="Screen Shot 2019-09-23 at 11 24 36" src="https://user-images.githubusercontent.com/46979321/65444094-f4c7bc00-ddf4-11e9-8666-5a6f8380a3b8.png">

The `baseurl` in `config.toml` is set as `"pliu.rbind.io/"`

Thanks, Nan!

Hao

**Comment by nanxstats** [comment]
@HaoWang47 -Hmm, looks like you still need to remove the custom domain added to the old site on Netlify before adding it to the new site.

The `baseurl` has nothing to do with this error message --- the parameter only determines how the urls are linked in the rendered site. When you build the site with Netlify, it can be simply set as `baseurl = "/"`.

**Comment by HaoWang47** [comment]
@nanxstats -

Thanks! I will try to find the old site as soon as possible and if I did, I will try to change the custom domain again. 

If I did not find the old site, could Dr. Liu just use pengliu.netlify.com as her site? Is it permanently free and functioning? I will keep maintaining it for sure. 

Also, I am afraid I need to keep this issue open for extra several days in case I come across other questions.

Thank you Nan! I really appreciate it!

Best,
Hao

**Comment by nanxstats** [comment]
@HaoWang47 -that would be great. Please do find and retire it, and probably keep only one Netlify site that has an rbind subdomain pointing to it.

I think you can, but ideally there should be only one site instead of two or three. As of now you got two sites with three domains which are all accessible... This might confuse search engines like google and the old links might rank higher.

We can keep this ticket open until you fix the issue.

**Comment by HaoWang47** [comment]
@nanxstats -
Hi Nan!

We can not find the site `pliu.netlify.com` so far. Also, I realized not only the portrait is pointing to the original file, but also all other internal links under Publications, Talks, Grants, and CV (pointing to `pliu.rbind.io/talks/...` instead of `pengliu.netlify.com/talks/...`). The portrait is not a big problem but other links do matter. Source codes pushed to GitHub have been correctly updated. 

Would you know what I can do?

Thank you very much!

Hao

**Comment by nanxstats** [comment]
@HaoWang47 -I would probably suggest contacting Netlify support to help locate the old site.

**Comment by yihui** [comment]
FYI I have deleted `pliu.netlify.com`.

**Comment by HaoWang47** [comment]
@nanxstats @yihui -

The website works now! Thank you very much for your help! I apologize I messed the website up during the summer.

Thank you!

Hao
