### ISSUE TITLE
Request for rbind subdomain

### ISSUE THREAD

**Issue by spcanelon** [rbind/support#477]
## Netlify website address

silvia.netlify.com

## Preferred rbind.io subdomain

silvia.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@spcanelon -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by spcanelon** [comment]
Hello @nanxstats! Thanks for helping me get set up with my [silvia.rbind.io](https://silvia.rbind.io) subdomain back in 2019! I have been a very happy user 🙂 

I'm wondering if there is a way for me to use a subdomain like **slides.silvia.rbind.io** if I'd like to keep my slide decks in a "slides" repository and point to them within my site (using a git submodule, I think). Is this possible with the ***rbind.io** subdomain or would I need to look into getting my own domain name?

**Comment by nanxstats** [comment]
Hi @spcanelon I guess we can do this by adding a new subdomain with the cname `slides.silvia` (example: http://datavizgvpt.tiagoventura.rbind.io). All we need is another (Netlify) site address to point to.

Does that sound good? Please feel free to create a new issue for this request.

**Comment by spcanelon** [comment]
Hi @nanxstats, that would be wonderful, thank you! I will follow up with a new issue for the new subdomain once I have something working. At the moment all of my slides are still scattered across multiple repos 😅
Thanks again!
