### ISSUE TITLE
request invite to join rbind + transfer + admin rights to repo + custom domain.

### ISSUE THREAD

**Issue by vodlomanga** [rbind/support#48]
request invite to join rbind + transfer + admin rights to repo + custom domain.
desired sub-domain: `s.rbind.io`
purpose: analysis + visualization of society and cultural interests using R and other tools.

repo: [https://github.com/vodlomanga/s](https://github.com/vodlomanga/s)
netlify: [https://culture.netlify.com/](https://culture.netlify.com/)

**Comment by yihui** [comment]
Done. Note you will have to contact Netlify support to set up the custom domain for you if you run into the same domain issue as #42.

**Comment by vodlomanga** [comment]
done. thanks.
