### ISSUE TITLE
Need support to add my domain : sabirahamed.rbind.io

### ISSUE THREAD

**Issue by sabirahamedpratichi** [rbind/support#485]
## Netlify website address

example.netlify.com

## Preferred rbind.io subdomain

example.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@sabirahamedpratichi -please replace the example addresses with the actual address, thanks!

**Comment by nanxstats** [comment]
Closing for now. Please feel free to reopen with the updated address or create a new issue afterwards.
