### ISSUE TITLE
Yutani's site request

### ISSUE THREAD

**Issue by yutannihilation** [rbind/support#49]
Hi, thanks for adding me to rbind! (Sorry for saying this too late). I'd love to join this great rbind movement.

I want to use **yutani.rbind.io** as my URL if it is still available.

By the way, I've just transferred a repo for my blog:

https://github.com/rbind/yutani

But I couldn't set up Netlify on it by the error bellow:

![image](https://user-images.githubusercontent.com/1978793/28243722-2bed1f82-6a10-11e7-9df4-3c1941fa1ac3.png)

Was my way of transferring was wrong? Or should I missing something? I need your help, thanks.

**Comment by yihui** [comment]
I just made you the admin of your repo. Please let me know your Netlify subdomain and I can configure the rbind subdomain for you.

**Comment by yutannihilation** [comment]
Thanks!

**Comment by yutannihilation** [comment]
My Netlify subdomain is **yutani** (https://yutani.netlify.com/).

But, I got this error when I tried to setup custom domain. Is this the same as #42?

![image](https://user-images.githubusercontent.com/1978793/28244077-84daa4b0-6a1b-11e7-92da-7f711f53fbaa.png)

**Comment by yutannihilation** [comment]
I am almost ready to email to Netlify support ✉️.

**Comment by yihui** [comment]
Yes, same as #42. Email them.

**Comment by yutannihilation** [comment]
Sure.

**Comment by yutannihilation** [comment]
Done. They manually added yutani.rbind.io and I've confirmed that I can access to https://yutani.rbind.io/ successfully now.

Thanks for your help! 👍
