### ISSUE TITLE
SSL Certificate Issue

### ISSUE THREAD

**Issue by vidyasagarbhargava** [rbind/support#490]
I am not able to secure my site with SSL certificate. As told by netlify support team currently my DNS set so that cloudflare serves my website. If i want to be able to provision SSL certificates natively with netlify need to change this setting.

website :- 

https://vidyasagar.rbind.io

Kindly help

![Screenshot 2019-10-20 13 28 36](https://user-images.githubusercontent.com/5356632/67159526-b1059b00-f33d-11e9-811a-bca4b8892d66.png)

**Comment by nanxstats** [comment]
Don't worry about it --- SSL for all rbind subdomains is automatically provided by Cloudflare already. This message appears for all rbind subdomains added to Netlify.
