### ISSUE TITLE
carles' web site

### ISSUE THREAD

**Issue by carleshf** [rbind/support#50]
Hi,

I would like to try out `rbind`.

I would like to ask for `carleshf.netlify.com`. My current repo is `http://banker-hamish-45161.netlify.com/`.

Thanks!

**Comment by carleshf** [comment]
I manage to change the name by myself.

Thx!

**Comment by yihui** [comment]
Yes, you are free to change the Netlify subdomain. Let us know if you need an rbind subdomain.
