### ISSUE TITLE
subdomain request

### ISSUE THREAD

**Issue by samherniman** [rbind/support#502]
## Netlify website address

stupefied-morse-91b0fe.netlify.com

## Preferred rbind.io subdomain

sam.rbind.io

Hiya
I already have samherniman.rbind.io (issue #483) but I'd like to switch over to sam.rbind.io
Would that be possible?

Thanks!

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@samherniman -yes, that subdomain is still available. I'd ask @yihui to update the record for you.

**Comment by yihui** [comment]
Done.

**Comment by samherniman** [comment]
Thanks!
