### ISSUE TITLE
Change subdomain

### ISSUE THREAD

**Issue by wvictor14** [rbind/support#509]
Hi, I already have a subdomain with rbind, but I was was wondering if I could change it to:

**victor.rbind.io**

Netlify website address
wvictor14.netlify.com

Current rbind.io subdomain
wvictor14.rbind.io

Agreement
 

- [X] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
-yes, and I'd love to ask @yihui to make that happen.

**Comment by yihui** [comment]
Done.

**Comment by nanxstats** [comment]
@wvictor14 -just a reminder to please update the subdomain configuration on your side.

**Comment by wvictor14** [comment]
Sorry, been busy this week. I think I have it properly configured now. Thanks a lot!

**Comment by nanxstats** [comment]
Alright, looks like the updated subdomain is working.

The failing builds are probably due to something else... just let us know if you still encounter problems and need help on that part. I'm closing this issue for now.
