### ISSUE TITLE
Requesting subdomain

### ISSUE THREAD

**Issue by richardohrvall** [rbind/support#51]
Hi!

I would like the subdomain richardohrvall.rbind.io for the site https://richardohrvall.netlify.com/ that I just set up, if possible. (No, I haven't changed the template yet, having some troubles exporting my old Wordpress blog, but I will give it one more try).

Thank you so much for all the help and for providing this! Looking forward to leaving WP behind.

All the best,
Richard

**Comment by yihui** [comment]
Done. You may need to contact Netlify support (#42).

**Comment by richardohrvall** [comment]
The support at Netlify was very helpful, and it is all working now. Thank you for your help and all your work!
