### ISSUE TITLE
domain name

### ISSUE THREAD

**Issue by anoumouteko** [rbind/support#510]
## Netlify website address

queleanalytics.netlify.com

## Preferred rbind.io subdomain

queleanalytics.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@anoumouteko -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thank you,
-Nan

**Comment by anoumouteko** [comment]
thanks!!!

**Comment by nanxstats** [comment]
-no problem, please add the subdomain on Netlify, so that we can close this issue.

**Comment by nanxstats** [comment]
@anoumouteko -another reminder to add the subdomain on Netlify, please.

**Comment by queleanalytics** [comment]
actualy i have a problem to properly deploy my blog on netlify.
Will let you know .
sorry for the delay

**Comment by nanxstats** [comment]
Hey @queleanalytics it looks like the Netlify site is up (again). Could you add the custom domain, please?

**Comment by nanxstats** [comment]
Hello @queleanalytics @anoumouteko -the last reminder to add the subdomain on Netlify please, or we will start the domain removal process due to security reasons. Thanks!

**Comment by queleanalytics** [comment]
Hello, sorry for the delay. i decide something else so you can remove the subdomain queleanalytics.rbind.io.thanks

**Comment by nanxstats** [comment]
@yihui -could you remove the record for `queleanalytics.rbind.io`, please? Thanks!

**Comment by queleanalytics** [comment]
already done!!! thanks

**Comment by yihui** [comment]
Done.
