### ISSUE TITLE
New Domain request :) 

### ISSUE THREAD

**Issue by jarrodscott** [rbind/support#514]
## Netlify website address

istmobiome.netlify.com

## Preferred rbind.io subdomain

istmobiome.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

Check!

**Comment by nanxstats** [comment]
Hi @jarrodscott -nice website. We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by jarrodscott** [comment]
Thanks @nanxstats! still a work in progress but it's moving along...

Ok, perfect, thank you so much for the custom domain and how-to info. 
istmobiome.rbind.io is up and running. Working on the `_redirects` now but  since my request has been resolved I will close this issue. Hope thats ok :)
