### ISSUE TITLE
request invite, repo transfer, admin rights and sub-domain.

### ISSUE THREAD

**Issue by fortunewalla** [rbind/support#52]
Request invite, repo transfer, admin rights and sub-domain.

Current website: [adventure.netlify.com](https://adventure.netlify.com)
Requested sub-domain: `a.rbind.io`
Purpose: Collaborating to use non-Microsoft tools to implement BI solutions on MS Adventure Works Cycles database.

thanks.

**Comment by yihui** [comment]
Mostly done. Please see #42 if you run into problems and contact Netlify support.

**Comment by fortunewalla** [comment]
done. thanks.
