### ISSUE TITLE
Want a subdomain

### ISSUE THREAD

**Issue by Liripo** [rbind/support#527]
Dear Developer：
## Netlify website address

ecstatic-poincare-18a275.netlify.com

## want rbind.io subdomain

liripo.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.
Thanks!

**Comment by Liripo** [comment]
ecstatic-poincare-18a275.netlify.com change into liripo.netlify.com

**Comment by nanxstats** [comment]
@Liripo -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by nanxstats** [comment]
@Liripo -just a reminder: please add the subdomain on Netlify, thanks.

**Comment by nanxstats** [comment]
@Liripo -another reminder to add the subdomain on Netlify, please.

**Comment by nanxstats** [comment]
Hey @Liripo -please add the subdomain on Netlify, or we will start the process of removing the subdomain. Thank you.

**Comment by Liripo** [comment]
Already added, thanks for your reminder。The website has been deployed, thank you for providing a free domain name.
