### ISSUE TITLE
welch16 rbind site

### ISSUE THREAD

**Issue by welch16** [rbind/support#53]
Hi,

I would like to get started with blogdown. Can I have `welch16.rbind.io` for `coach-phyllis-83361.netlify.com` 

Thanks in advance!

**Comment by yihui** [comment]
I have configured the CNAME for you.

**Comment by thercast** [comment]
@welch16 just checking in to see if everything is working well for you?

**Comment by welch16** [comment]
yes, sorry it took me so long to get back to you guys. Thank you very much!
