### ISSUE TITLE
URL request

### ISSUE THREAD

**Issue by benjamincrary** [rbind/support#530]
## Netlify website address

https://festive-brattain-72401a.netlify.com/

## Preferred rbind.io subdomain

uuconf2020.rind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@benjamincrary -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by nanxstats** [comment]
@benjamincrary -just a reminder to add the subdomain on Netlify, please.

**Comment by benjamincrary** [comment]
@nanxstats I followed the instructions per your last message (see image below). Is there anything else I need to finalize?
![image](https://user-images.githubusercontent.com/4306181/71987362-aac3e400-31f3-11ea-9660-91ad2859a90e.png)

**Comment by nanxstats** [comment]
@benjamincrary -no worries, there was probably some DNS record refresh delays on my machine, but now looks like it's working properly. Thanks!
