### ISSUE TITLE
CNAME record 

### ISSUE THREAD

**Issue by rhaefer** [rbind/support#531]
I set up a rbind site previously under reidhaefer.rbind.io but recently there was a DNS issue when deploying. Can you point the CNAME record for reidhaefer.rbind.io to reidrhaefer.netlify.com? Thanks!

## Netlify website address

reidrhaefer.netlify.com

## Preferred rbind.io subdomain

reidhaefer.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Hmm, I see reidhaefer.rbind.io already points to reidrhaefer.netlify.com in the CNAME record, as in the original request (https://github.com/rbind/support/issues/448). The two domains seem both working under http and https, too.

**Comment by nanxstats** [comment]
@rhaefer -just curious --- was the "DNS issue when deploying" resolved? Or we can close this issue?

**Comment by rhaefer** [comment]
yes you can. thanks!
