### ISSUE TITLE
subdomain request

### ISSUE THREAD

**Issue by ebologna** [rbind/support#548]
## Netlify website address

https://youthful-thompson-395e43.netlify.com

## Preferred rbind.io subdomain

ebologna.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@ebologna -we see a soft 404 for the current netlify website. Could you please make sure the link work and add some content there? Thanks.

**Comment by nanxstats** [comment]
@ebologna -a reminder to update netlify website address to a valid one.

**Comment by nanxstats** [comment]
@ebologna -another reminder to  update the netlify website address, please.

**Comment by nanxstats** [comment]
Closing for now. Please create a new issue when the Netlify website is ready.
