### ISSUE TITLE
CNAME change?

### ISSUE THREAD

**Issue by denizCvrl** [rbind/support#552]
Hello, my custom domain (makingwebsiteswithr.rbind.io) doesn't point to Netlify but Cloudware.
original website is: makingwebsiteswithr.netlify.com

Is this something I am supposed to solve? Here is the respond I received from Netlify community: 
  
"However, the required DNS records for that custom domain point to Cloudflare, not Netlify:

$ dig makingwebsiteswithr.rbind.io +noall +answer

; <<>> DiG 9.10.6 <<>> makingwebsiteswithr.rbind.io +noall +answer
;; global options: +cmd
makingwebsiteswithr.rbind.io. 299 IN	A	104.31.76.168
makingwebsiteswithr.rbind.io. 299 IN	A	104.31.77.168
The solution is to create a CNAME record (instead of these A records) which point to the Netlify subdomain. There is more information about this here:

https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/#configure-a-subdomain

Once that is done and the records above expire (which should take five minutes due to the TTL values), the custom domain should point to the Netlify site above."
### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
hey @denizCvrl -nothing needs to be changed here, this is how it works.

**Comment by denizCvrl** [comment]
Sorry again, but then I cannot make http to https. Is there any other way. I am sorry but for newbies these are complicated issues. Yihui Xie's blog suggests following Netlify direction but Netlify directions suggest this??

**Comment by nanxstats** [comment]
Hi @denizCvrl -the https version for your rbind subdomain already works. It's just that the http URLs are not automatically redirected to the https urls. You may find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting http traffic to https automatically using a 301 redirect.

**Comment by denizCvrl** [comment]
Ok i got it. I am sorry, these are all new for me. So i already have https so i don't need to ask from netlify. I just need to redirect it. Thank you.
