### ISSUE TITLE
host my github website with rbind.io

### ISSUE THREAD

**Issue by oboukary** [rbind/support#554]
## Netlify website address

https://oboukary.github.io/website/

## Preferred rbind.io subdomain

ouedraogo.boukary.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Hi @oboukary -we can only point the subdomain to `oboukary.github.io`. Could you please make sure your website is accessible via `https://oboukary.github.io` instead of `https://oboukary.github.io/website/`?

**Comment by oboukary** [comment]
Hi @nanxstats  it's ok. I have made my website accessible via  to https://oboukary.github.io instead of https://oboukary.github.io/website/

Thank you

**Comment by nanxstats** [comment]
@oboukary -great! We have just configured the subdomain on our side. Please add a `CNAME` file in your repo, pointing to the rbind subdomain (`ouedraogo.boukary.rbind.io`), just like what you would do to [configure custom domains for GitHub Pages](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain).

Thanks!
-Nan

**Comment by oboukary** [comment]
@nanxstats great! Thank you  to much
