### ISSUE TITLE
Subdomain request

### ISSUE THREAD

**Issue by simonschoe** [rbind/support#557]
## Netlify website address

https://simonschoe.netlify.com/

## Preferred rbind.io subdomain

simonschoe.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@simonschoe -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by simonschoe** [comment]
Hi,
thanks for the service! Is it possible to once more change the domain from simonschoe.rbind.io to simon.schoelzel.rbind.io?
Best
Simon

**Comment by nanxstats** [comment]
I'd ask @yihui to make that happen for you

**Comment by yihui** [comment]
Done.

**Comment by nanxstats** [comment]
@simonschoe -please go ahead and update the record on Netlify, thanks!

**Comment by simonschoe** [comment]
Thanks for the fast reply! I keep on getting the following error message when trying to access the website under the new domain: 

Error code: SSL_ERROR_NO_CYPHER_OVERLAP

And Netlify tells me: We could not provision a Let’s Encrypt certificate for your custom domain.

Any ideas what might be the issue here?

**Comment by nanxstats** [comment]
Hmm, not really sure, I double checked and `simon.schoelzel.rbind.io` now points to `simonschoe.netlify.com`.

Could you elaborate more on the domain configuration on Netlify? Also, simonschoe.netlify.com is currently returning a 404.

**Comment by simonschoe** [comment]
I deleted the whole page on netlify and set it up from scratch - same result here. Since I am not an expert, I'm not sure which information might be helpful...

On Netlify I got `simonschoelzel.netlify.app` as the default subdomain with `www.simon.schoelzel.rbind.io` as primary domain. For the latter, Netlify asked me if I am the owner of the domain (which I am obviously not). 

With the `static/_redirects` file I am redirecting traffic from `https://simonschoelzel.netlify.com/*`, `http://simonschoelzel.netlify.com/*`, `http://simon.schoelzel.rbind.io/*`, `http://simonschoe.rbind.io/*`, `http://simonschoe.rbind.io/*` 
to `https://simon.schoelzel.rbind.io/`.

Best, 
Simon

**Comment by nanxstats** [comment]
@simonschoe -as before, please set `simon.schoelzel.rbind.io` as the primary domain, no `www` needed.

**Comment by simonschoe** [comment]
I changed that, with no result. Since roughly 48h Netlify is now telling me: "Waiting on DNS propagation" (under the "SSL/TLS certificate" section).

**Comment by nanxstats** [comment]
Hmm, then i'm running out of ideas.

**Comment by simonschoe** [comment]
So, when i don't use any redirect functionalities there is no issue at all - means I can access the site via `https://simonschoelzel.netlify.app/`. However, as soon as I try to add `simon.schoelzel.rbind.io` as custom domain on Netlify I run into this error. Also, Netlify is always telling me that `rbind.io already has an owner. Is it you?` which never occurred to me before, when I was just using `simonschoe.rbind.io`...

Thanks anyway for the help!

**Comment by nanxstats** [comment]
The owner message can be safely ignored.

Some facts about netlify.com vs netlify.app: Netlify [changed](https://community.netlify.com/t/changes-coming-to-netlify-site-urls/8918) the default domain assigned for hosted websites to .app instead of .com since mid April, while the .com domain is still useable for new sites. We're still pointing to .com domains because .app requires mandatory SSL which were problematic ([1](https://github.com/rbind/support/issues/587) and [2](https://github.com/rbind/support/issues/595)).

`simon.schoelzel.rbind.io` currently points to `simonschoe.netlify.com`, which should be redirected to `simonschoe.netlify.app` by Netlify.

`http://simon.schoelzel.rbind.io` (non-https) already works. The only non-working is the https version `https://simon.schoelzel.rbind.io`.

```
→ curl https://simon.schoelzel.rbind.io
curl: (35) error:14004410:SSL routines:CONNECT_CR_SRVR_HELLO:sslv3 alert handshake failure
```

**Comment by simonschoe** [comment]
Finally, I am starting to wrap my head around it - thanks @nanxstats! It now seems to work properly, at least the redirects to the http-version. Any ideas if the use of https paired with an .app domain will be possible in the future?

**Comment by nanxstats** [comment]
I think I might find a reasonable explanation of the current SSL issue:

https://community.cloudflare.com/t/subdomain-too-deep/81872

Is it possible to remove the dot in the requested subdomain?

**Comment by simonschoe** [comment]
Yes, that is totally fine for me, especially if it’s one step towards the desired solution

**Comment by nanxstats** [comment]
-ok let's try it. @yihui do you mind changing the subdomain `simon.schoelzel.rbind.io` to `simonschoelzel.rbind.io` (removing the dot)?

**Comment by yihui** [comment]
Done.

**Comment by nanxstats** [comment]
@simonschoe -ok, please try removing the old custom domain record for `simonschoe.netlify.app`, and add `simonschoelzel.rbind.io` as its custom domain.

**Comment by simonschoe** [comment]
Thanks! This finally did the trick and https is working properly.
