### ISSUE TITLE
New rbind.io subdomain request

### ISSUE THREAD

**Issue by chunyufen** [rbind/support#558]
## Netlify website address

https://yufen-chun.netlify.com/

## Preferred rbind.io subdomain

yufen-chun.rbind.io

Previously, you have given me "yufen-chun.rbind.io" for "https://chunyufen.netlify.com". The website was redirected from GitHub. This week, I updated Hugo and changed theme. GitHub did not build the website on gh-pages. I changed to bitbucket. Therefore, I created the same website with a new theme at netlify. The netlify website address is changed from "https://chunyufen.netlify.com" to "https://yufen-chun.netlify.com/".

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@yihui -could you please update the cname record for `yufen-chun.rbind.io` to `yufen-chun.netlify.com`? Thanks.

**Comment by chunyufen** [comment]
Dear Nanxstats,

I don't quite understand the technical terms. But I have done something as shown in the attachment. Now, if I type yufen-chun.rbind.io, I get my website. So, can I say I have done the correct thing?
<img width="896" alt="Screenshot 2020-02-23 at 1 47 34 PM" src="https://user-images.githubusercontent.com/18733971/75104365-4f36a400-5643-11ea-8514-de47cf18256d.png">
Thanks for the help.

**Comment by nanxstats** [comment]
@chunyufen - `yufen-chun.rbind.io` is still pointing to `chunyufen.netlify.com`. Please wait for @yihui to update the record on our side.

**Comment by yihui** [comment]
Done.

**Comment by nanxstats** [comment]
@chunyufen -looks like the record is updated on our side and the site is working properly. I'm closing this for now but please feel free to let us know if you need further assistance.
