### ISSUE TITLE
request subdomain for David Jankoski's website

### ISSUE THREAD

**Issue by david-jankoski** [rbind/support#57]
hello rbind team,

thank you for an awesome initiative and this organisation! the blogdown package and the accompanying book are great - I am not knowledgable in web technologies at all but was able to set up a blog and host it on netlify easy. 
I would like to use (if available) the subdomain davidjankoski.rbind.io for my [website repository](https://github.com/david-jankoski/website).
The website is deployed on http://davidjankoski.netlify.com/. 
I tried transferring it but I guess I need some sort of approval from your side first.

Thanks again for all your hard work and kick ass projects!

greetings,
david

**Comment by yihui** [comment]
@thercast @njtierney Could either of you send the rbind invite?

@david-jankoski I have configured the CNAME record for davidjankoski.rbind.io. If you run into any problems on Netlify when configuring your custom domain, please see #42.

**Comment by njtierney** [comment]
Invite sent!

Sorry for the delay. I made them a vector member, is that right?

**Comment by yihui** [comment]
Yes.

**Comment by david-jankoski** [comment]
@yihui thank you yihui, everything worked out fine - i had the same problems as you pointed out in #42, but contacted the netlify support and they fixed everything swiftly. 

@njtierney thanks nick! btw hi - macedonian david from useR here ;-) 
 
one last question though - i transferred my website repo to rbind, however it seems like now the netlify site does not pick up the new changes and commits i do? I tried several times making changes and committing them but no effect on the live site - any ideas what might be causing this?

**Comment by yihui** [comment]
@njtierney Could you grant @david-jankoski admin rights from his repo settings?

**Comment by njtierney** [comment]
Ah, Macedonian David! Nice to see you again, virtually :)

I'll grant him admin rights from his repo.

**Comment by njtierney** [comment]
OK done, I think?

![image](https://user-images.githubusercontent.com/6488485/29543058-da813fd2-8721-11e7-96e1-c999fee96d3b.png)

Apologies for the late reply on this, btw.

**Comment by thercast** [comment]
@david-jankoski I checked out your site and everything looks to be working well.  I'll close for now but if you encounter any other issues please let us know.  Welcome to Rbind!

**Comment by david-jankoski** [comment]
yes - sorry for the late reply and thank you all for your help, everything works great now.  
I had some minor problems (the site did not want to pick up on the changes somehow - but rebuild, redeploy fixed), but i am learning as i go and think i can take it from here.

thanks again!
greetings,
david

**Comment by yihui** [comment]
Right. I also noticed that @Netlify was not quite stable recently. Sometimes you just have to rebuild/redeploy manually from app.netlify.com.
