### ISSUE TITLE
Domain request

### ISSUE THREAD

**Issue by avyukt** [rbind/support#584]
## Netlify website address

anushaa1.netlify.com

## Preferred rbind.io subdomain

anushaa1.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@avyukt -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by avyukt** [comment]
Thanks Nan, 

I followed the steps above. I added the subdomain name to netlify and it is still checking for DNS integration and checking for DNS propogation for HTTS security. I have created the redirects folder as suggested above as well. The website is currently working on netlify but still not working on rbind. How shall I make this subdomain work?

**Comment by avyukt** [comment]
I am getting the error 
This page isn’t workinganushaa1.rbind.io redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

Yihui in one of the posts suggests that this is a random error for some names. 
Can you assign me another subdomain like anusha.rbind.io or anushaa.rbind.io to see if that works. 

Thank you.

**Comment by nanxstats** [comment]
@avyukt -saw the error here too. I added another subdomain `anusha.rbind.io` to point to `anushaa1.netlify.com`. Please update the custom domain settings on your side and see if this works.
