### ISSUE TITLE
Switch subdomain name

### ISSUE THREAD

**Issue by aurorepaligot** [rbind/support#594]
## rbind.io subdomain

aboreal.rbind.io

## Preferred rbind.io subdomain

aurore.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
pinging @yihui to update the record for ya

**Comment by yihui** [comment]
Done.

**Comment by aurorepaligot** [comment]
Thanks a lot!
