### ISSUE TITLE
Subdomain Request

### ISSUE THREAD

**Issue by biswas2** [rbind/support#603]
## Netlify website address

raselbiswas.netlify.app

## Preferred rbind.io subdomain

rasel.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@biswas2 -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by biswas2** [comment]
Many thanks, Nan.
I have a question. My site can be reached via https://rasel.rbind.io, does it mean that I've already set up the HTTPS redirection? (Apparently I did nothing to redirect)

Another question:
If I change my GitHub username, will it affect my 'rasel.rbind.io' subdomain in some way, other than having to change the repository in the Continuous Deployment setting in Netlify?

**Comment by nataliablock** [comment]
### Netlify website address

nataliablock.netlify.app

### Preferred rbind.io subdomain

nataliablock.rbind.io

Agreement

 

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@biswas2 1. Nope, if you access it with explicit http `http://rasel.rbind.io` it doesn't redirect to https, so you might still want to do it. 2. No, it won't affect anything as long as you don't change the Netlify subdomain where the rbind subdomain is pointing to.

**Comment by nanxstats** [comment]
@nataliablock -please create a new issue for your request, thanks!

**Comment by nataliablock** [comment]
@nanxstats ok, sorry for that
