### ISSUE TITLE
aapply for subdomain name

### ISSUE THREAD

**Issue by Metalesaek** [rbind/support#606]
## Netlify website address

serene-einstein-b01e4e.netlify.app

## Preferred rbind.io subdomain

ModelingwithR.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Hey @Metalesaek -I see a soft 404 on your site, could you please put up some content there first? Thanks.

**Comment by Metalesaek** [comment]
thanks for reply, i check out every think ok , they ask me to add a new domain , can i put there :  ModelingwithR.rbind.io  as my subdomain or is to you  to do that, please this my first attempt to build my own site. thanks again

**Comment by nanxstats** [comment]
@Metalesaek -sorry no can do, please see the agreement --- we will only add the subdomain until some content is up there.

**Comment by Metalesaek** [comment]
@nanxstats , Hello , my first attempt has been failed so i created another one with a new request , thank you.

**Comment by nanxstats** [comment]
-ok let's move to https://github.com/rbind/support/issues/608
