### ISSUE TITLE
Subdomain request

### ISSUE THREAD

**Issue by yijutseng** [rbind/support#61]
May I receive subdomain yjtseng?

yjtseng.rbind.io

Thank you!

**Comment by yihui** [comment]
Please provide your Netlify subdomain: https://support.rbind.io/about/

**Comment by yijutseng** [comment]
Thanks for your reply. Here is my netlify info: 
https://purchasing-officer-daisy-14376.netlify.com/

**Comment by yihui** [comment]
Done.

**Comment by thercast** [comment]
@yijutseng just checking in to see if everything is working as expected for you?

**Comment by Zhiqiangcao** [comment]
May I receive subdomain statczq.rbind.io? 
my netlify info is http://statczq.netlify.com/ 
Thanks!

**Comment by yihui** [comment]
@Zhiqiangcao Done. See #42 if you run into problems.

**Comment by Zhiqiangcao** [comment]
@yihui Thanks! It works! ^_^

**Comment by thercast** [comment]
@Zhiqiangcao looks like everything is working well so I'll close the issue. Feel free to reach out again if you encounter any questions or need further assistance.
