### ISSUE TITLE
Requesting help with DNS configuration

### ISSUE THREAD

**Issue by spcanelon** [rbind/support#613]
Recently I noticed that my [silvia.rbind.io](https://silvia.rbind.io) site isn't currently being served by Netlify so it doesn't have a proper SSL/TLS certificate. I just checked the (closed) issue I submitted to request the silvia.rbind.io subdomain and realized I provided _silvia.netflify.com_ as the Netlify address when in fact it's **_silvia.netlify.app_** in my Netlify account. Could that be what's causing issues? I'm new to this so any pointers would be much appreciated!

**Comment by nanxstats** [comment]
I'm not sure what this means: "it doesn't have a proper SSL/TLS certificate". silvia.rbind.io renders ok on my side with the Cloudflare SSL. If it's rendering ok you can ignore the messages about certificates on Netlify.

It currently points to silvia.netlify.com, and I think Netlify points silvia.netflify.com to silvia.netlify.app, although they don't advertise the netlify.com subdomain anymore.

**Comment by spcanelon** [comment]
Thanks @nanxstats ! The messages on Netlify made me think there was something wrong on the SSL side (see screenshot), so it's comforting to hear that's not the case and that I can ignore them! Also helpful to see you confirm that my site _should_ be served by Cloudfare, not Netlify.

<img width="669" alt="Screen Shot 2020-05-07 at 11 33 11 AM" src="https://user-images.githubusercontent.com/49913337/81313989-93d4b780-9056-11ea-8e98-c6cfb256220d.png">

I was hoping this "issue" was the reason I haven't been able to verify my silvia.rbind.io site using Google Search Console, but I guess now I know the two things are unrelated. Thanks for your help!

**Comment by nanxstats** [comment]
-no problem! Yes, this message can be safely ignored, and yes, they are probably unrelated. Please do let us know if you encountered any other issues in the future.
