### ISSUE TITLE
sc2 subdomain request

### ISSUE THREAD

**Issue by ummel** [rbind/support#62]
Hello -- Thanks for starting this initiative. My colleague and I are starting a new project with private repos but would like ability to share ongoing results via a simple blogdown site (not yet built). The [hugo-academic](https://github.com/gcushen/hugo-academic) theme seems suitable. Ideal subdomain is: sc2.rbind.io

What else do you require from me to get something up and running with an example site? Again, many thanks!

**Comment by yihui** [comment]
@thercast @njtierney Could you get @ummel started?

**Comment by thercast** [comment]
@ummel I set up a sample `blogdown` site powered by the hugo-academic theme in a new repository [rbind/sc2.rbind.io](https://github.com/rbind/sc2.rbind.io).  You should have received an invitation to the repository by now, but let us know if you have any issues working with the repo.  We highly recommend reading through the [blogdown online text](https://bookdown.org/yihui/blogdown) for comprehensive details on using the package to power your web site.

**Comment by yihui** [comment]
@ummel And note that I cannot set up your subdomain until you set up your Netlify subdomain.

**Comment by ummel** [comment]
Many thanks, everyone. @yihui I have successfully deployed via Netlify: http://butcher-programs-60464.netlify.com/

**Comment by yihui** [comment]
Okay, the sc2 subdomain has been assigned to you. If you run into any problems, please see #42.

**Comment by ummel** [comment]
Everything appears to be deploying correctly at [sc2.rbind.io](sc2.rbind.io). Did require Netlify support to set custom domain manually. Only outstanding issue: I cloned repo to local machine and ran serve_site(). Receive error 'Not found: ./"https://sc2.rbind.io/"', but I thought serve_site() is supposed to override baseurl with "/" (only) for [local paths](https://bookdown.org/yihui/blogdown/local-preview.html) -- no?

**Comment by yihui** [comment]
Here is the fix: https://github.com/rbind/sc2.rbind.io/pull/1

**Comment by ummel** [comment]
If anyone is monitoring this, the [sc2 repo](https://github.com/rbind/sc2.rbind.io) can be deleted. It is no longer used.
