### ISSUE TITLE
rbind subdomain request

### ISSUE THREAD

**Issue by pgg1610** [rbind/support#623]
Thank you for setting up this service and for the clear instructions on how to get started.
 
## Netlify website address

https://hopeful-noyce-2f7ecd.netlify.app/

## Preferred rbind.io subdomain

pushkar.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Hey @pgg1610 -could you add some content to the site please? Currently it's a soft 404. Thanks!

**Comment by pgg1610** [comment]
Hello @nanxstats  I decided to use a custom domain and while doing so changed my netlify URL while led to the soft 404. With that, I wont need the rbind.io domain. Thank you for getting back and for providing this amazing resource!
