### ISSUE TITLE
domain request msaeltzer

### ISSUE THREAD

**Issue by msaeltzer** [rbind/support#627]
## Netlify website address

msaeltzer.netlify.app

## Preferred rbind.io subdomain

msaeltzer.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
hey @msaeltzer -the site currently shows a soft 404, could you please make sure there's some content there?

**Comment by nanxstats** [comment]
@msaeltzer -any updates?

**Comment by msaeltzer** [comment]
Sorry I am just in the process of building the page but it is still filled with latin filler text. I will finish it and then open a new issue. Sorry for the inconvinience.
