### ISSUE TITLE
Request admin rights over repo rbind/s as not able to deploy on netlify

### ISSUE THREAD

**Issue by vodlomanga** [rbind/support#63]
I have repo https://github.com/rbind/s connected to `netlify.com` through https://s.rbind.io/

I can update it from computer. But new changes not reflected on `netlify.com`. 
Last successful deploy:
```
Production: master@235113c published
"initial website" Jul 14 at 6:06 pm
Deployed in 9 seconds
```
Tried manual trigger deploy but give error
```
2:05:03 AM: Build started
2:05:03 AM: Fetching cached dependencies
2:05:03 AM: No cached dependencies found. Cloning fresh repo
2:05:03 AM: git lfs clone git@github.com:vodlomanga/s
2:05:05 AM: Error cloning repository: git@github.com:vodlomanga/s
2:05:06 AM: An error occurred while building the site, skipping the deploy and cache refresh.
2:05:06 AM: exit status 2
2:05:06 AM: Finished processing build request in 3.133697576s
```
Tried to change repo from `vodlomanga/s` folder to `rbind/s` folder but it says
```
Error: We couldn’t set up continuous deployment for this repository. This typically happens when you don’t have admin rights to the repository.
```
Any ideas?

**Comment by yihui** [comment]
@thercast @njtierney Could you take care of this?

**Comment by thercast** [comment]
@vodlomanga you should now have admin access to your repository.  Let us know if you are still experiencing the same issues.

**Comment by vodlomanga** [comment]
done. thanks.
