### ISSUE TITLE
domain request

### ISSUE THREAD

**Issue by GregBuck** [rbind/support#630]
I would like to request and domain name:

bbresearch.rbind.io

Thank you
Reply: gregory.buck@alaska.gov

**Comment by nanxstats** [comment]
Hey @GregBuck -which URL should we point the subdomain to? Please see the issue template.

**Comment by GregBuck** [comment]
Preferred rbind.io subdomain
bbresearch.rbind.io
Agreement

  *   By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

This is the only template I could find on rbind.io/support. The netlify URL I want this to point to is https://app.netlify.com/sites/cranky-fermi-1ab637/
_____________________________
Greg Buck
Area Research Biologist, Bristol Bay
Commercial Fisheries Division
Alaska Department of Fish and Game
Phone (907)267-2355
FAX (907)267-2442

**Comment by nanxstats** [comment]
@GregBuck -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan
