### ISSUE TITLE
Hello. I am applying for a rbind.io subdomain

### ISSUE THREAD

**Issue by farzadsaif** [rbind/support#634]
## Netlify website address

https://eloquent-euclid-d13872.netlify.app

## Preferred rbind.io subdomain

farzadsaif.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by farzadsaif** [comment]
Dear Nan,

Thank you for helping me get a rbind.io subdomain. I much appreciate the help. I have a couple of questions: 

I know you said that “DNS verification failed” can be ignored, but Netfly is telling me that I cannot enable HTTPS without a DNS verification. Is this possible with a rbind.io <http://rbind.io/> subdomain?

Thank you,

Farzad Saif
BA Economics
University of Illinois at Urbana-Champaign

**Comment by nanxstats** [comment]
-that message can be ignored. It's already supported: `https://farzadsaif.rbind.io/`.
