### ISSUE TITLE
https://ayao-website.netlify.app/

### ISSUE THREAD

**Issue by Ayao12** [rbind/support#637]
## Netlify website address

ayao-website.netlify.app

## Preferred rbind.io subdomain

ayao-nomenyo.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@Ayao12 -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by nanxstats** [comment]
Hey @yihui could you please remove the record `ayao-nomenyo.rbind.io`? Thanks.

**Comment by Ayao12** [comment]
I follow the instructions step by step but something it is wrong, I don't know : 

![gitpict1](https://user-images.githubusercontent.com/58120478/84543353-2110c900-acf3-11ea-82f8-7386df60809d.png)
![gitpict2](https://user-images.githubusercontent.com/58120478/84543360-24a45000-acf3-11ea-9e1e-752844cf56cd.png)
![gitpict3](https://user-images.githubusercontent.com/58120478/84543364-25d57d00-acf3-11ea-8999-cc6a3cd16f98.png)


Can you help me, please?

**Comment by nanxstats** [comment]
@Ayao12 

In the first instruction: **no `www` needed**.

In the second instruction: **"check DNS configuration" can be safely ignored**.

**Comment by Ayao12** [comment]
@nanxstats 

Thank you so much. It is ok now 👍 

Best regards

**Comment by yihui** [comment]
@nanxstats Done.
