### ISSUE TITLE
ayao website

### ISSUE THREAD

**Issue by Ayao12** [rbind/support#639]
## Netlify website address

ayao-nomenyo.netlify.app

## Preferred rbind.io subdomain

ayaowebsite.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Hmm, what's the relationship between this and https://github.com/rbind/support/issues/637? We'd prefer maintain a minimum number of subdomains unless necessary. Do you want us to update or remove certain records?

**Comment by Ayao12** [comment]
> Hmm, what's the relationship between this and #637? We'd prefer maintain a minimum number of subdomains unless necessary. Do you want us to update or remove certain records?


@nanxstats thank you so much. sorry to disturb you. Indeed I have a certain problem concerning the verification on and also I want to change the name of the site. So you can delete all records except the last one I submit. 
I'm a novice and it is my first time doing this one.

**Comment by nanxstats** [comment]
@Ayao12 -no problem, just to double check:

1. remove ayao-nomenyo.rbind.io created in https://github.com/rbind/support/issues/637
2. add ayaowebsite.rbind.io and point it to ayao-nomenyo.netlify.app

is this correct?

**Comment by Ayao12** [comment]
@nanxstats, ok! thank you again. Can you help with this problem :
![gitpict](https://user-images.githubusercontent.com/58120478/84536220-4565a900-ace5-11ea-95f3-3c92c229db36.png)

**Comment by nanxstats** [comment]
I'm not sure what the problem is...

I added `ayaowebsite.rbind.io` and pointed it to `ayao-nomenyo.netlify.app`. Please add this domain to your site following the steps mentioned in https://github.com/rbind/support/issues/637.
