### ISSUE TITLE
subdomain request

### ISSUE THREAD

**Issue by jbintz** [rbind/support#64]
I'd like to request the subdomain:  jasonbintz.rbind.io

My netlify subdomain is https://jasonbintz.netlify.com

**Comment by yihui** [comment]
Done.

**Comment by jbintz** [comment]
<img width="878" alt="screenshot 2017-08-26 21 11 36" src="https://user-images.githubusercontent.com/20375541/29746303-6af013e8-8aa3-11e7-97b0-4dd7d1bd8c3b.png">

**Comment by yihui** [comment]
Please see #42.

**Comment by jbintz** [comment]
For others: After referencing #42, I clicked on contact support and said that my understanding is that this is a known issue and that the issue is with the branch deploy feature and, as a result, you have to set the rbind urls manually at the moment. Within 5 minutes they had addressed the problem.

**Comment by jbintz** [comment]
I'm sorry for the additional question, but now I'm wondering about the https steps...I said "I've done this" to the question about pointing the DNS blah blah--I'm not sure if that was correct, but now I'm wondering if I should go ahead and "Let's encrypt certificate"?

<img width="890" alt="screenshot 2017-08-26 22 22 06" src="https://user-images.githubusercontent.com/20375541/29746586-12d8b962-8aad-11e7-81b9-76ac80601145.png">

**Comment by yihui** [comment]
Yep, please go ahead and hit the button.

**Comment by jbintz** [comment]
all seems well...many thanks
