### ISSUE TITLE
new rbind.io subdomain requests.

### ISSUE THREAD

**Issue by danielleyang** [rbind/support#642]
## Netlify website address

danyangchen.netlify.app

## Preferred rbind.io subdomain

danyangchen.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@danielleyang -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by nanxstats** [comment]
Hey @danielleyang -a reminder to add the subdomain on Netlify.

**Comment by nanxstats** [comment]
Hello @danielleyang -another reminder to add the subdomain on Netlify, please.

**Comment by nanxstats** [comment]
hey @danielleyang -a final reminder to add the subdomain on Netlify, or we will start the subdomain removal process.

**Comment by nanxstats** [comment]
Hi @danielleyang -any chance of adding the subdomain on Netlify?

**Comment by nanxstats** [comment]
@yihui -could you please remove the record `danyangchen.rbind.io`? The requested subdomain has not been added to the site after reaching out for a few times.

@danielleyang If needed, please open another issue to request the subdomain in the future.

**Comment by yihui** [comment]
Done.
