### ISSUE TITLE
New domain request

### ISSUE THREAD

**Issue by davidjohnbaker1** [rbind/support#65]
Hello--

I am requesting for my current domain at https://davidjohnbaker.netlify.com/ to be hosted at davidjohnbaker.rbind.io 

Please let me know if I need to do anything else

Dave

**Comment by yihui** [comment]
Done.

**Comment by davidjohnbaker1** [comment]
Thanks! That was quick! 

Just tried it after updating config.toml baseline to 

baseurl = "https://davidjohnbaker.rbind.io/"

then pushed to my github but I get a "Not Found" message on my browser.

Is there something else I am missing?

**Comment by yihui** [comment]
Did you actually add the subdomain on Netlify and enable HTTPS? If you run into problems, please feel free to contact Netlify support. They are very responsive and helpful.

**Comment by davidjohnbaker1** [comment]
I've contacted the netlify people and will take it from there. Thanks for the help!
