### ISSUE TITLE
Subdomain request

### ISSUE THREAD

**Issue by petrkajzar** [rbind/support#652]
## Netlify website address

petr4rbind.netlify.app

## Preferred rbind.io subdomain

petr.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@petrkajzar We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by petrkajzar** [comment]
Thanks a lot @nanxstats ! It's done and works fine, thanks.

**Comment by petrkajzar** [comment]
@nanxstats After a few tries, I made sure I wouldn't blog anymore. After all, I've realized that it's not my cup of tea. Can you please delete my domain (`petr.rbind.io`)? The site is already down now. I apologize for any inconvenience and thank you very much for all your work!
Thanks
-Petr

**Comment by nanxstats** [comment]
-ok, @yihui -could you please remove the subdomain `petr.rbind.io`? Thanks!

**Comment by yihui** [comment]
Done.
