### ISSUE TITLE
Request invite and sub-domain

### ISSUE THREAD

**Issue by b-rodrigues** [rbind/support#66]
Hi

I'd like to request an invite and the following sub-domain:

brodriguesco.rbind.io

my current website is hosted at b-rodrigues.github.com and I own the domain www.brodrigues.co

Once I get the invite, transferring the repo should be enough, right?

Thanks!

**Comment by yihui** [comment]
Cc @njtierney / @thercast I can set up the subdomain for you after you transfer the repo and deploy it on Netlify (just let me know the Netlify subdomain).

**Comment by b-rodrigues** [comment]
Hi

hum ok, so I need to use netlify? I'll have to read into it then :)

**Comment by yihui** [comment]
You don't have to. If you don't, I'll assume that you know enough about DNS and you will have to tell me how I should create the CNAME record for you. (More info: https://bookdown.org/yihui/blogdown/domain-name.html)

**Comment by b-rodrigues** [comment]
I guess I'll try netlify. I've wanted to switch for some time now, might as well do it.

**Comment by yihui** [comment]
Okay, sounds good. We need to wait for Nick or Eric to invite you and then I'll do the subdomain.

**Comment by njtierney** [comment]
OK done!

![image](https://user-images.githubusercontent.com/6488485/29796826-b1620f44-8c96-11e7-87db-cb31101f9cc6.png)

**Comment by b-rodrigues** [comment]
Hello,

so switching to Netlify has been a very easy and pleasant experience! My blog is live over at:

http://guard-walrus-32111.netlify.com/

**Comment by b-rodrigues** [comment]
however I'm not sure I've done the right steps to use my own domain
I own www.brodrigues.co, registrar gandi.net and I enabled the custom domain on netlify. Then I pointed the domain to the nameservers that I was given, is that enough?

**Comment by b-rodrigues** [comment]
I think something's wrong still on the netlify app it says that the deployment is made from repository:

`https://github.com/b-rodrigues/b-rodrigues.github.com`

but shouldn't it be:

`https://github.com/rbind/b-rodrigues.github.com` ?

If I try to change this, I get the following error:

> Error: We couldn’t set up continuous deployment for this repository. This typically happens when you don’t have admin rights to the repository.

**Comment by yihui** [comment]
@njtierney Could you help @b-rodrigues and grant him admin rights of his repo?

**Comment by b-rodrigues** [comment]
Thanks!

I have another question: the baseurl in config.toml, should it be brodriguesco.rbind.io or the ugly netlify url?

**Comment by njtierney** [comment]
yup done!

**Comment by yihui** [comment]
@b-rodrigues Use the URL that you want other people to visit. Although you have two, I recommend you to stick with one, and 301/302 redirect the other.

**Comment by b-rodrigues** [comment]
Thanks for your help @njtierney and @yihui ! I'll read into these redirects and come back here again if I fail miserably ^^

**Comment by thercast** [comment]
@b-rodrigues looks like your site is working well so I will close for now, but please let us know if you need further assistance.
