### ISSUE TITLE
new rbind.io subdomain requests.

### ISSUE THREAD

**Issue by winniewytse** [rbind/support#660]
## Netlify website address

mmmlab.netlify.app

## Preferred rbind.io subdomain

mmmlab.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@winniewytse We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by winniewytse** [comment]
Hello Nan, 

Thank you very much for your quick help in offering the rbind.io subdomain to me. I have a question regarding redirecting HTTP traffic to HTTPS. The insecure HTTP links worked fine with my site, but I hope to secure them. I followed the post on point 3 and created a `_redirects` plain text file under the `static` folder. The content of it is as below
`http://mmmlab.rbind.io/*      https://mmmlab.rbind.io/:splat  301!`
However, Error 526 has been there since I employed this redirection. 
Did I miss anything in the process? I'd appreciate any help you will offer!

Thank you, 
Winnie

**Comment by nanxstats** [comment]
Ah, my bad.

Hey @yihui could you please update the cname record for mmmlab.rbind.io from `mmmlab.netlify.app` to `mmmlab.netlify.com`?

It should be fixed after this (remove and re-add the custom domain on Netlify if needed).

**Comment by winniewytse** [comment]
Thank you for your help Nan! Much appreciated!

**Comment by yihui** [comment]
Done.

**Comment by winniewytse** [comment]
Thank you very much @yihui!
