### ISSUE TITLE
new rbind.io subdomain requests.

### ISSUE THREAD

**Issue by mstkolf** [rbind/support#661]
## Netlify website address

mstkolf-blog.netlify.app

## Preferred rbind.io subdomain

mstkolf.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by mstkolf** [comment]
Please let me know if there are any errors.
I’ll be waiting for support.

**Comment by nanxstats** [comment]
-ok, I did it again... @yihui could you please update the record for `mstkolf.rbind.io` from `mstkolf-blog.netlify.app` to `mstkolf-blog.netlify.com`? We should probably think about adding logic to automatically replace `.netlify.app` to `.netlify.com` as this is easily prone to human error.

@mstkolf -my apologies for the delay, the subdomain should be ready soon.

**Comment by yihui** [comment]
@nanxstats Done. And I'll update the Shiny app to always use `netlify.com` instead of `.app`.

**Comment by nanxstats** [comment]
-awesome, thanks @yihui !

**Comment by nanxstats** [comment]
@mstkolf We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by mstkolf** [comment]
Thank you for helping me get a rbind.io subdomain. 
[This post](https://yihui.org/en/2017/11/301-redirect/) was very helpful!
I much appreciate the help.

**Comment by yihui** [comment]
@nanxstats I just updated the app, and it will `sub('[.]netlify[.]app$', '.netlify.com', x)`.
