### ISSUE TITLE
new rbind.io subdomain request

### ISSUE THREAD

**Issue by calcita** [rbind/support#664]
## Netlify website address

gabriela-mathieu.netlify.app

## Preferred rbind.io subdomain

gabrielamathieu.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Hey @calcita I see a few resource point to `gabrielamathieu.info` with the requests not coming through so the page rendering is blocked. Could you please fix them first?

**Comment by nanxstats** [comment]
@calcita -any chance of fixing the site?

**Comment by calcita** [comment]
hi! I have it linked to netlify and I can't access my account to change it. I haven't been able to access my netlify account for a few days :(

**Comment by nanxstats** [comment]
No worries - I would recommend contacting Netlify support to resolve the access issue first: https://www.netlify.com/support/.

**Comment by calcita** [comment]
Hi! I solved it and deleted the .info domain address

**Comment by nanxstats** [comment]
Still seeing two render-blocking resources: `main.css` and `logo.png`:

<img width="1359" alt="Screen Shot 2020-08-13 at 11 28 05 AM" src="https://user-images.githubusercontent.com/199363/90154592-4bfdb480-dd58-11ea-9859-186bc1633c0a.png">

**Comment by calcita** [comment]
Hi! I think I solved that problem.

**Comment by nanxstats** [comment]
@calcita -great, we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by calcita** [comment]
Many thanks!
