### ISSUE TITLE
request invite to join rbind + transfer + admin rights to repo + sub-domain

### ISSUE THREAD

**Issue by deepernexus** [rbind/support#67]
desired sub-domain: d.rbind.io
purpose: deep learning for social media analysis

repo: https://github.com/deepernexus/d
netlify: https://deep.netlify.com/

thanks!

**Comment by yihui** [comment]
I have configured the rbind subdomain for you.

@thercast @njtierney Could you take care of the rest of the request?

**Comment by njtierney** [comment]
Hi @deepernexus I've added you to the rbind org, my understanding is that you need to transfer your repo over to rbind as I cannot do that for you, correct @yihui ?

**Comment by yihui** [comment]
Correct.

**Comment by njtierney** [comment]
OK and I've given @deepernexus admin access to his own repo, so I think this is all taken care of now? Sorry it's taking me a few times to get this down pat :)

**Comment by yihui** [comment]
Yes. Thanks @njtierney!

**Comment by deepernexus** [comment]
Is there any page to check the admin status? Everything set up. thanks to both of you.

**Comment by yihui** [comment]
@deepernexus If you can see the Settings tab in your repo, you must be the admin.

**Comment by deepernexus** [comment]
@yihui got it. thanks.
