### ISSUE TITLE
tantely.rbind.io

### ISSUE THREAD

**Issue by athhise** [rbind/support#672]
## Netlify website address

tantely.netlify.app

## Preferred rbind.io subdomain

tantely.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Hey @athhise I see a 404 at the current site. Could you please add some content there first?

**Comment by nanxstats** [comment]
@athhise -any updates?

**Comment by nanxstats** [comment]
@athhise I'm closing this issue for now. Please feel free to create a new issue when your site is ready.
