### ISSUE TITLE
Change of Netlify website address for yufen-chun.rbind.io

### ISSUE THREAD

**Issue by chunyufen** [rbind/support#675]
Previously, I used "https://chunyufen.netlify.com". You have given me "yufen-chun.rbind.io".
I deleted several posts. Netlify gave me another name (see below).
Please refix it for "yufen-chun.rbind.io".
Thanks.

## Netlify website address

https://yufen-chun.netlify.app/

## Preferred rbind.io subdomain

yufen-chun.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
-ok, @yihui could you please update the record for `yufen-chun.rbind.io` to  `yufen-chun.netlify.com`? Thanks!

**Comment by chunyufen** [comment]
I have changed the baseURL to  "yufen-chun.netlify.com"

**Comment by chunyufen** [comment]
This is the current situation:
<img width="922" alt="Screenshot 2020-08-25 at 2 00 45 PM" src="https://user-images.githubusercontent.com/18733971/91128804-6c742a00-e6db-11ea-9d81-66728fe7b62d.png">

**Comment by chunyufen** [comment]
Thanks very much. It works now. Thank you very much. Best wishes.
