### ISSUE TITLE
Request invite

### ISSUE THREAD

**Issue by jsta** [rbind/support#68]
Hi

I'd like to request an invite and the following sub-domain:

`jsta.rbind.io`

my current website is hosted at https://jsta.netlify.com

I think I am ready to transfer after the org invite.

Thanks!

**Comment by yihui** [comment]
I have configured the rbind subdomain for you.

@thercast @njtierney Could you take care of the rest of the request?

**Comment by njtierney** [comment]
Hi @jsta I've added you to the rbind org, my understanding is that you need to transfer your repo over to rbind as I cannot do that for you, correct @yihui ?

**Comment by yihui** [comment]
Correct.

**Comment by jsta** [comment]
@thercast @njtierney I transferred to https://github.com/rbind/jsta.rbind.io

**Comment by njtierney** [comment]
OK awesome! 

Have you got ownership of the repo @jsta ? Otherwise I think from here I transfer it to you.

**Comment by jsta** [comment]
I think I need repo admin access otherwise netlify wont let me adjust the domain redirect to rbind.io.

**Comment by njtierney** [comment]
OK great, I made you an admin - I think that should all be good now :)

Let me know how you go

**Comment by jsta** [comment]
We are live! Thanks.
