### ISSUE TITLE
Request for rbind.io subdomain name

### ISSUE THREAD

**Issue by JoannaProut** [rbind/support#680]
## Netlify website address

happy-colden-7ed7e4.netllify.app

## Preferred rbind.io subdomain

joannaprout.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by JoannaProut** [comment]
totally new to this so let me know if I screwed anything up!  Thanks so much!

**Comment by nanxstats** [comment]
Hey @JoannaProut the netlify url is not accessible right now. Could you please let us know the address to a working site?

**Comment by JoannaProut** [comment]
Thanks so much!  I think this link is working: https://happy-colden-7ed7e4.netlify.app/1/01/01/tidy-tuesday-for-9/1/2020/

**Comment by nanxstats** [comment]
Ah I see, there is an additional `l` in "netlify" from the original request.

**Comment by nanxstats** [comment]
@JoannaProut -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by JoannaProut** [comment]
Thanks so much!  This is amazing. :)
