### ISSUE TITLE
request of an rbind.io subdomain

### ISSUE THREAD

**Issue by cmg777** [rbind/support#683]
## Netlify website address

quarcs-lab.netlify.app

## Preferred rbind.io subdomain

quarcs-lab.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Hey @cmg777, our record shows that `quarcs-lab.rbind.io` already points to `quarcs-lab.netlify.com`.

**Comment by cmg777** [comment]
Hi @nanxstats, below I show the problem that I am facing with the DNS configuration
![Domain management | Settings 2020-09-14 13-08-11](https://user-images.githubusercontent.com/26156651/93042987-7d390f80-f68b-11ea-8a42-ff4187f98e07.jpg)

When I check the DNS configuration, I get

![Domain management | Settings 2020-09-14 13-10-33](https://user-images.githubusercontent.com/26156651/93043090-c1c4ab00-f68b-11ea-92bb-f6a2ce8e20fb.jpg)


When I set up Netlify DNS for rbind.io, I get

![Set up Netlify DNS for your domain | quarcs-lab 2020-09-14 13-12-17](https://user-images.githubusercontent.com/26156651/93043161-f9cbee00-f68b-11ea-8cc0-53b689b10a7d.jpg)

If I ignore these issues, I get the following problem in several pages of the deployed website
![Set up Netlify DNS for your domain | quarcs-lab 2020-09-14 13-12-17](https://user-images.githubusercontent.com/26156651/93043358-7e1e7100-f68c-11ea-95b7-2c94d4de7b04.jpg)

What can I do?

Thank you in advance for your cooperation.

**Comment by nanxstats** [comment]
@cmg777  It looks like `https://quarcs-lab.rbind.io/` already works! So nothing to be done here.

**Comment by cmg777** [comment]
Hi @nanxstats 

I am still having DNS configuration  issues

![Domain management | Settings 2020-09-14 17-37-49](https://user-images.githubusercontent.com/26156651/93063879-d5830800-f6b1-11ea-94ed-c0da6847356d.jpg)

**Comment by nanxstats** [comment]
Hi @cmg777 The message can be safely ignored - this is already managed by our side.

**Comment by cmg777** [comment]
Got it. Thank you very much.

__________________________________________________________

__________________________________________________________

**Comment by nanxstats** [comment]
My pleasure!
