### ISSUE TITLE
Request for a subdomain name

### ISSUE THREAD

**Issue by JobNmadu** [rbind/support#687]
## Netlify website address

jobnmadu.netlify.app

## Preferred rbind.io subdomain

jobnmadu.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Hi @JobNmadu it seems the site shows a soft 404. Could you please make sure there is some content there? Thanks.

**Comment by nanxstats** [comment]
@JobNmadu -still showing a 404 on my side:

<img width="1217" alt="Screen Shot 2020-09-21 at 11 22 16 AM" src="https://user-images.githubusercontent.com/199363/93785988-c1cd2980-fbfc-11ea-8f7c-85e538c2ab29.png">

**Comment by JobNmadu** [comment]
Sorry for the problems I am causing. I need some guide now.

I have used serve_site and tried to link at netlify. That was what I did this morning. I have been following the process step by step. Could you suggest what might be the solution to the  problem?

I have changed my base to jobnmadu.rbind.io before serve_site.

Could it be that I need to open a repo now or what?

I am totally a novice

Thank you.

**Comment by JobNmadu** [comment]
![image](https://user-images.githubusercontent.com/18013355/93792224-24d6b480-fc2d-11ea-9bb0-f97c3236abf8.png)

**Comment by nanxstats** [comment]
@JobNmadu I guess it could be that Netlify doesn't have the access to the repo. For the above screenshot, you could try clicking "Configure Netlify on GitHub" so that their backend can authenticate with GitHub and connect to the repo.

**Comment by nanxstats** [comment]
Hey @JobNmadu I'm closing this issue for now. If you need further help on the subdomain, please feel free to reopen in the future.
