### ISSUE TITLE
Request for rbind.io subdomain

### ISSUE THREAD

**Issue by YoichiMukai** [rbind/support#689]
## Netlify website address

yoichi-mukai.netlify.app

## Preferred rbind.io subdomain

I have a rbind.io subdomain "yoichimukai.rbind.io" associated with "yoichi-mukai-2.netlify.app", but I would like to detouch the rbind.io domain from "yoichi-mukai-2.netlify.app" and newly associate the rbind.io domain with "yoichi-mukai.netlify.app".

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@yihui -could you please help update the cname record for `yoichimukai.rbind.io` to `yoichi-mukai.netlify.com`?

**Comment by YoichiMukai** [comment]
I talked to Netlify as well and they helped me to transfer the domain. So,
it is all done! Thank you.

**Comment by yihui** [comment]
@nanxstats Done.

**Comment by nanxstats** [comment]
-awesome, thank you! Closing the issue.
