### ISSUE TITLE
New website for ellakaye.rbind.io

### ISSUE THREAD

**Issue by EllaKaye** [rbind/support#694]
## Netlify website address

https://gallant-shaw-c70134.netlify.app

## Preferred rbind.io subdomain

ellakaye.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

I already have the ellakaye.rbind.io subdomain, where I hosted a website built with blogdown, which got so out-of-date that I could no longer build/update it. I have recently created a new website with hugodown in a [new git repository](https://github.com/EllaKaye/hugodown-website) that I fully intend to keep up-to-date (I have some draft posts on the go). I tried copying all the files (including the hidden ones) from the new website folder into the current rbind/ellakayewebsite folder that pushes to my ellakaye.rbind.io subdomain, and it mostly worked fine except that my chosen custom font isn't displaying, and I can't figure out why.

I'd really like to keep my current website address and the new font. Would you be able to either help me figure out why the LEMONMILK font isn't showing up, or else to slash and burn the current site and replace it with the one that's at https://gallant-shaw-c70134.netlify.app, or whatever other solution is most appropriate.

Thank you very much!

**Comment by EllaKaye** [comment]
Actually, ignore this for now, please. I've completely messed up something with git and I need to figure it out before swapping over the domain. I'll be back in touch when that's resolved.

**Comment by EllaKaye** [comment]
Sorry, I closed the issue when I was having some git trouble, but I've managed to resolve that and would still like to move [https://gallant-shaw-c70134.netlify.app](https://gallant-shaw-c70134.netlify.app) over to the https://ellakaye.rbind.io address.

Well, I've resolved the git issues with the new site, but I think I've really messed up rbind/ellakayewebsite, so I suspect it's probably best if we completely trash the old site (rather than try to resolve the font and now various other issues) and move the new site over to my old rbind address. Is that something you can help with? I've tried to work out how to do it myself using netlify but couldn't quite figure it out.

**Comment by nanxstats** [comment]
Hey @EllaKaye 

Sorry it took a while for me to understand the situation. Do you want us to point `ellakaye.rbind.io` to the new address `gallant-shaw-c70134.netlify.app` instead of the previous record `ellakaye.netlify.com`? I think that's the easiest way to make this work.

I would say it's probably a good idea NOT to fix the old site, since the hugo-academic theme changed a lot, besides Hugo itself...

We can also help delete the repo `rbind/ellakayewebsite` if you prefer not to use it anymore.

Let me know what you think.

**Comment by EllaKaye** [comment]
Hi @nanxstats 

Thanks for getting back to me. Sorry if my issue wasn't clear.

I think the best is the following:

1. Delete the `rbind/ellakayewebsite` repo and current `ellakaye.rbind.io`/`ellakaye.netlify.app` site.
2. Rename the `gallant-shaw-c70134` site to `ellakaye.netlify.app` (which should be possible after step 1).
3. Point `ellakaye.rbind.io` at the new `ellakaye.netlify.app`

Will the `EllaKaye/hugodown-website` repo be moved over to  `Github/rbind`? I know it used to be the case that rbind GitHub repos were moved, but recently I've seen rbind sites still under the creators' portfolio (e.g. https://github.com/spcanelon/silvia and https://github.com/dcossyleon/blogdown_desiree). 

Thanks for you help!

Best wishes,
Ella

**Comment by EllaKaye** [comment]
Hi @nanxstats,

Following my previous message, I have:

1. deleted the old `ellakaye.rbind.io` from netlify and archived the `rbind/ellakayewebsite` repo.
2. Renamed `gallant-shaw-c70134.netlify.app` to `ellakaye.netlify.app`.

So, if you could help with step 3 (or tell me how to do it myself), pointing `ellakaye.rbind.io` to `ellakaye.netlify.app`, that would be great!

Thanks very much.

**Comment by nanxstats** [comment]
Awesome, thanks @EllaKaye. From our side, I see `ellakaye.rbind.io` already points to `ellakaye.netlify.com` (which automatically redirects to `ellakaye.netlify.app` by Netlify). It's showing a certificate error currently - maybe you need to add the subdomain as a custom domain to the new site on Netlify (as before). Here is how to do it:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

The repo can stay under your account or be moved to the rbind organization account upon your preference.

If there is any more issues, please reach out and we can continue here to figure them out.

**Comment by EllaKaye** [comment]
Hi @nanxstats,

Thanks so much for your help with this! I added the custom domain on Netlify and the new site is all up-and-running now :)

The provision of rbind subdomains is such a great service. I really appreciate all that you and the team do to make that possible.
