### ISSUE TITLE
Page Not Found error

### ISSUE THREAD

**Issue by chunyufen** [rbind/support#697]
## Netlify website address

yufen-chun.netlify.app

## Preferred rbind.io subdomain

yufen-chun.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

### Important History

- I have been using yufen-chun.rbind.io for some times. A few days ago, the link did not work. I created a few new posts and it said "This page cannot be found". But old posts could still be read.

- The repository is bitbucket.org/yufen-chun/southern-bough-ii

- So, I deleted the site at netlify. I reinstalled it from bitbucket.

- NOW, everything cannot be seen.
<img width="504" alt="Screenshot 2020-10-09 at 10 32 01 AM" src="https://user-images.githubusercontent.com/18733971/95535318-b52d3b80-0a1a-11eb-9532-5d40108631a2.png">

- I can read all posts in my local server when I created my posts by Blogdown.

- Please help.

**Comment by chunyufen** [comment]
I show you the setting at Netlify by the diagram below:
<img width="1266" alt="Screenshot 2020-10-09 at 10 56 45 AM" src="https://user-images.githubusercontent.com/18733971/95536758-5cf83880-0a1e-11eb-9305-c217c40ac5fb.png">

**Comment by chunyufen** [comment]
I also show you my baseURL for the static blog written by Rstudio:
<img width="712" alt="Screenshot 2020-10-09 at 10 59 23 AM" src="https://user-images.githubusercontent.com/18733971/95536849-992b9900-0a1e-11eb-999c-bfed9ea93e53.png">

**Comment by nanxstats** [comment]
@chunyufen try set

```
baseurl = "/"
```

**Comment by chunyufen** [comment]
Thanks a lot.
