### ISSUE TITLE
Request for subdomain name

### ISSUE THREAD

**Issue by kortekss** [rbind/support#701]
## Netlify website address

bengukalo.netlify.app

## Preferred rbind.io subdomain

bengukalo.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@kortekss We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by kortekss** [comment]
Many thanks!

**Comment by kortekss** [comment]
Hi! I am unable to open my website, I was wondering if it is related to the domain name issues? On Netlify, ''bengukalo.rbind.io'' is greyed out. Can you help with that?

Many thanks!

**Comment by nanxstats** [comment]
@kortekss I don't see any changes or issues on our side. The upstream url `bengukalo.netlify.app` now shows a 404 though. Do you want us to point the subdomain to a new address if that has been changed?
