### ISSUE TITLE
Need admin rights for rbind/s repo

### ISSUE THREAD

**Issue by vodlomanga** [rbind/support#71]
Need admin rights for rbind/s repo

@njtierney could be please help me?

**Comment by yihui** [comment]
Nick won't be available until a few weeks later. @thercast Could you help?

**Comment by thercast** [comment]
@vodlomanga it looks like you do have admin rights to the repo as far as I can tell: 

![image](https://user-images.githubusercontent.com/1043111/29982972-caf77e52-8f21-11e7-81b8-32cbed5d9bd9.png)

If you are still encountering issues let us know.

**Comment by vodlomanga** [comment]
strange but now it is showing. thanks.
