### ISSUE TITLE
https certificate provided by Cloudflare, not Let's Encrypt

### ISSUE THREAD

**Issue by yea-hung** [rbind/support#718]
Hi all, https is working for my site (covid-19.rbind.io) but I'm seeing that the certificate is provided by Cloudflare, not Let's Encrypt. In Netlify, I see the following error message:

```
DNS verification failed
covid-19.rbind.io doesn't appear to be served by Netlify
```

And, using [the check](https://docs.netlify.com/domains-https/troubleshooting-tips/#https-error-messages) suggested by Netlify's documentation, I see the following:

```
$ curl -s -v http://covid-19.rbind.io 2>&1 | grep Server
< Server: cloudflare
```

Similarly, I checked some sites for other recently closed domain requests (for example: https://shelbybachman.rbind.io/ and https://lauriebaker.rbind.io/ and https://stubbs.rbind.io/) and the certificates for those also show Cloudflare.

On the other hand, the support site (https://support.rbind.io) shows Let's Encrypt.

First, is this in fact an issue? And second, if so, is there anything I should do on my end? Thank you!

**Comment by nanxstats** [comment]
@yea-hung -very good detective work. Nothing to worry about here. All the user requested `rbind.io` subdomain are indeed served by Cloudflare. The message on Netlify can be safely ignored.
