### ISSUE TITLE
Subdomain request

### ISSUE THREAD

**Issue by dhonda** [rbind/support#724]
## Netlify website address

delaniehonda.netlify.app

## Preferred rbind.io subdomain

delaniehonda.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@dhonda We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by earfanfan** [comment]
您好，我在统计之都看到这篇文章https://cosx.org/2018/01/build-blog-with-blogdown-hugo-netlify-github  
其中提到建立博客要注册域名，可以在这里申请一个二级域名。但我看到rbind.io官网上介绍，如果不了解域名的工作原理，会建议用户将Github与netlify连接上。我在中国，无法登陆netlify也无法注册，更不能科学上网。
我打算未来几个月用业余时间搭建自己的个人博客，希望申请的域名是yf.rbind.io，如果已被占用就申请yuanfan.rbind.io，烦请酌情审批。
如果审核人觉得不合适，也没关系，我仍会试着寻找其他注册免费域名的方法。

**Comment by nanxstats** [comment]
@earfanfan Thanks - when your site is ready, please submit the request in a separate issue using the issue template. We will be happy to review it.
