### ISSUE TITLE
need guidance to delete and reupload repo

### ISSUE THREAD

**Issue by fortunewalla** [rbind/support#73]
After experimenting with different repos, created my repo. `rbind/f `. But now noticed that there are 4 contributors. [https://github.com/rbind/f/graphs/contributors](https://github.com/rbind/f/graphs/contributors) . I want to make it single contributor. I have attributed the other contributors in the final website.

I thought of two ways:
1. Delete the `rbind/f` repo, make single contributor (delete and recreate) , upload same repo again to `rbind/f`
2. Transfer `rbind/f` to personal profile `fortunewalla/f`, change to single contributor (delete and recreate), retransfer back to `rbind/f`

Which approach would require least permissions from your side? If a better approach exists, let me know. thanks.

**Comment by yihui** [comment]
`git push --force` to rewrite history

![](https://slides.yihui.name/gif/git-push-force.gif)

**Comment by fortunewalla** [comment]
i like your sense of humor. 😺 thanks.

![tenor.com](https://media.tenor.com/images/b89cdcd2b20fc8e36e6f0b7df140b861/tenor.gif)
