### ISSUE TITLE
Allow authors to add GitHub apps

### ISSUE THREAD

**Issue by Robinlovelace** [rbind/support#730]
This isn't about subdomains. It's about access to repos that have moved to rbind.

Problem: I want to give access to the utterenc.es app to my repo at rbind/robinlovelace, but when I ask it to, I get this message:

>  You do not have permission to modify this app on rbind. Please contact an Organization Owner. 

Proposed solution: find a way to allow authors to add apps to their repos on rbind.

Screenshot of what I see: 

![image](https://user-images.githubusercontent.com/1825120/103387384-50561e80-4afb-11eb-9b47-3dc1b1a2e4ab.png)

Context + motivation: https://mscipio.github.io/post/utterances-comment-engine/

**Comment by nanxstats** [comment]
@Robinlovelace Under the rbind organization account (Settings -> Installed GitHub Apps), it seems utterances was approved three days ago and already has access to all repositories.  It also appears in your rbind repo specifically (Settings -> Integrations). So I'm not sure what can be done here - maybe it already works?

The proposed solution is an interesting one while from [GitHub docs](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/permission-levels-for-an-organization#github-app-managers) it doesn't seem possible to grant app management permission to users on an individual repo level.

**Comment by Robinlovelace** [comment]
You're right, utteranc.es was already there, it just wasn't clear to me. Good news, my posts now have a comments section :tada: https://www.robinlovelace.net/post/new-year-new-site-new-world/
