### ISSUE TITLE
New Subdomain request

### ISSUE THREAD

**Issue by MorgsJohn** [rbind/support#74]
I have set up a github repository with my [blogdown](https://github.com/MorgsJohn/ikhaya_wami) files and linked it to my Netlify profile. 

I would like to use the rbind.io subdomain.

My netlify info:
https://morgsjohn.netlify.com

Thanks

**Comment by yihui** [comment]
What is your preferred rbind.io subdomain?

**Comment by MorgsJohn** [comment]
Confusion from me :/

I meant domain. 

I would very much like to be a morgsjohn.rbind.io kinda blog...

**Comment by yihui** [comment]
Done. If you run into problems, please see #42.

**Comment by MorgsJohn** [comment]
"Must be unique" popping its little head up. I have asked the Netlify guys for help. Seems to be how the other resolved this issue. Will report back when I'm sorted. 

Thanks @yihui

**Comment by MorgsJohn** [comment]
Sorted. Netlify helped out.
