### ISSUE TITLE
Requests for a new rbind.io subdomain. THANKS!

### ISSUE THREAD

**Issue by dryzliang** [rbind/support#741]
## Netlify website address

None

## Preferred rbind.io subdomain

dryezl.rbind.io

### Agreement

- [ ] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Hey @dryzliang we will need the website address to assign a rbind.io subdomain

**Comment by dryzliang** [comment]
> Hey @dryzliang we will need the website address to assign a rbind.io subdomain

So @nanxstats , i need to get my account in netlify firstly, and then tranfer it to rbind subdomain?

**Comment by nanxstats** [comment]
@dryzliang yes, we will need to see a working website.

**Comment by nanxstats** [comment]
Closing for now. Please feel free to open a new issue when you are ready.
