### ISSUE TITLE
Request for a rbind.io subdomain

### ISSUE THREAD

**Issue by baggiponte** [rbind/support#743]
Hello rbind team!

First, thank you for your job. I am working on a university project about sustainable mobility and I was wondering if I coul ask for the following `rbind.io` subdomain.

## Netlify website address

[louisville-dockless-vehicles.netlify.app](https://louisville-dockless-vehicles.netlify.app/)

## Preferred rbind.io subdomain

`louisville-dockless-vehicles.rbind.io`

alternatively:

`escooters-louisville.rbind.io`

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@baggiponte We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by baggiponte** [comment]
Dear Nan,

thank you for your answer! I did not get how to set up the `https` protocol with this new custom domain, given the message 'DNS verification failed'.

Thank you again!

**Comment by nanxstats** [comment]
@baggiponte Looks like https already works: https://louisville-dockless-vehicles.rbind.io/. As mentioned in point 2, the DNS verification message can be safely ignored. See point 3 to redirect http traffic to https.
