### ISSUE TITLE
site not deploying on netlify

### ISSUE THREAD

**Issue by asimumba** [rbind/support#75]
Hi, 
I would like help with my site. I have a problem with the site building and deploying on netlify. 

I take a mini version of the log:
@thercast since you still have access to the site, I would appreciate your assistance.

The repo is here: https://github.com/rbind/asimumba
ERROR: 2017/09/12 21:09:56 hugo.go:421: Current theme does not support Hugo version 0.17. Minimum version required is 0.2
Started building sites ...
ERROR: 2017/09/12 21:09:56 template.go:477: template: partials/footer.html:9: function "now" not defined
ERROR: 2017/09/12 21:09:56 template.go:477: template: theme/partials/footer.html:9: function "now" not defined
ERROR: 2017/09/12 21:09:56 template.go:132: template: "partials/footer.html" is an incomplete or empty template; defined templates are: "partials/article_meta.html", "theme/partials/post-list.html", "_internal/_default/rss.xml", "_internal/schema.html",

**Comment by thercast** [comment]
I will take a look later today when I get back to a computer

**Comment by asimumba** [comment]
I managed to install the right hugo version for the build. Ohh that was easy...

**Comment by thercast** [comment]
Nice job!
