### ISSUE TITLE
rbind.io subdomain requests

### ISSUE THREAD

**Issue by xiaochi-liu** [rbind/support#753]
Hello. I'm [Xiaochi Liu](https://twitter.com/XiaochiLiu), a PhD researcher at Macquarie University, Sydney. My research interest is the application of spatial statistics and machine learning in Environmental and Public Health. And I do all my work using R and RStudio.

After attending the **rstudio::global 2021** online conference, I got a huge motivation to establish my blog website via `blogdown` to record my research life and technical experience. Currently, I'm following the _blogdown_ book to learn how to create it. Although now my website is just a template theme, I will definitely build it into a professional one in the subsequent days and months. 

Really hope to join the family of **Rbind**. Thank you very much!

## Netlify website address

xiaochi.netlify.app

## Preferred rbind.io subdomain

xiaochi.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@xiaochi-liu We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by xiaochi-liu** [comment]
Done. I love it! Thank you very much @nanxstats
