### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by mrsensible** [rbind/support#769]
## Netlify website address

vgi.netlify.app

## Preferred rbind.io subdomain

vgi.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
So `vgi.rbind.io` already points to `vgi.netlify.com` - nothing is changed on this side. Is something changed on your side, @mrsensible?

**Comment by mrsensible** [comment]
> So `vgi.rbind.io` already points to `vgi.netlify.com` - nothing is changed on this side. Is something changed on your side, @mrsensible?

I didn't know I could change the repository in netlify. I accidentally deleted the domain. So would it work if I add the rbind.io as a subdomain inside my new site?

**Comment by mrsensible** [comment]
Oh it was very simple. I added the subdomain and it's working, wala!

**Comment by nanxstats** [comment]
Great! Then I'm closing this issue.
