### ISSUE TITLE
rbind.io subdomain request 

### ISSUE THREAD

**Issue by mrsensible** [rbind/support#771]
Can you redirect vercel websites too?

## Vercel website address

https://hyesop.vercel.app/

## Preferred rbind.io subdomain

rottenapple.rbind.io 

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@mrsensible I'm not really sure if `.app` links will work here, as we have observed [substantial issues](https://github.com/rbind/support/issues/587#issuecomment-609465616) with *.netlify.app domains. We have been using the `.com` version of them (not enforcing https) to redirect.

**Comment by nanxstats** [comment]
I'm closing this now as there is no clear resolution indicated at the moment.
