### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by guang-yu-zhu** [rbind/support#775]
## Netlify website address

https://guang-yu-zhu.github.io/

## Preferred rbind.io subdomain

guangyuzhu.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@guang-yu-zhu We have configured the rbind subdomain you requested. Please put a CNAME file in your repo with one line `guangyuzhu.rbind.io` to make it work.

**Comment by guang-yu-zhu** [comment]
Thanks!
