### ISSUE TITLE
rbind subdomain request

### ISSUE THREAD

**Issue by guang-yu-zhu** [rbind/support#777]
Hi, 
A few days ago,
I required to link `guang-yu-zhu.github.io' to http://guangyuzhu.rbind.io/
I think, what I really want is to link my Netlify website to http://guangyuzhu.rbind.io/

## Netlify website address

https://guangyuzhu.netlify.app/

## Preferred rbind.io subdomain

http://guangyuzhu.rbind.io/

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@yihui -could you please update the record `guangyuzhu.rbind.io` to point it to `guangyuzhu.netlify.com`? Thanks.

**Comment by yihui** [comment]
Done.

**Comment by nanxstats** [comment]
@guang-yu-zhu -please add the custom domain on Netlify, thanks.
