### ISSUE TITLE
add distillery to rbind

### ISSUE THREAD

**Issue by jhelvy** [rbind/support#779]
## website address

This site is hosted on github using github pages, not netlify, hope that is okay. I built it for the community of people building sites with {distill} rather than {blogdown}, and since it's a collection of content by others I felt it should have it's own rbind.io subdomain rather than be a part of my jhelvy.github.io domain:

https://jhelvy.github.io/distillery/

## Preferred rbind.io subdomain

distillery.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by sohelkhanz** [comment]
My netlify address is sohelkhanz.netlify.app 
I want sohelkhan.rbind.io

**Comment by jhelvy** [comment]
> My netlify address is sohelkhanz.netlify.app
> I want sohelkhan.rbind.io

Did you mean to post this as its own issue?

**Comment by nanxstats** [comment]
@jhelvy GitHub Pages is ok but unfortunately a CNAME record can only point to hostname + domain like `jhelvy.github.io` (no path allowed). Do you want to provide another site address that does not include path?

**Comment by nanxstats** [comment]
@sohelkhanz -please create a new issue and follow the template to submit the request. Thanks.

**Comment by jhelvy** [comment]
@nanxstats I was actually trying to transfer the repo to rbind, but I didn't quite understand the instructions on the [support page](https://support.rbind.io/about/). I can't transfer to an organization I'm not a member of, so how do I go about asking to join rbind? Is filing an issue the right way? 

Also, if I were able to transfer the repo, would I then be able to keep hosting the site on Github pages and use the subdomain distillery.rbind.io?

**Comment by nanxstats** [comment]
@jhelvy

Transferring the repo to rbind will not help either, because the purpose was for hosting the **source** of the site. You still need a deployed site address that does not contain any path component, which GitHub Pages will still not be able to offer.

We can send you a member invitation though if you want to transfer the repo.

**Comment by jhelvy** [comment]
Ah I see...okay so I'll have to set this up to build the site with netlify then. If I can get that working, I'll follow up here.

**Comment by nanxstats** [comment]
Great, I'm closing this for now - feel free to open another issue to file the request.
