### ISSUE TITLE
join request from openemr

### ISSUE THREAD

**Issue by johnbwilliams** [rbind/support#78]
Dear rbind support,

Thanks for this support service.  We are excited about creating a blog with blogdown for the [OpenEMR Project](http://www.open-emr.org/) ([GitHub]( https://github.com/openemr))

Blog content will include health data science topics, including shiny apps, and an evolving [microservice analytics platform](https://github.com/openemr/openemr-analytics) including shiny-server & rstudio-server. 

rbind support params: 

- Hosting service:  _rbind.io_
- Subdomain request:  _openemr_
- Hugo theme request:  _same theme used by Rstudio Blog_  (if available?)
- Admin access to repo (by rbind support):   _yes_
- Rstudio version:  _1.0.153_

If the requested Hugo theme is available,  I'd need to know the name of the theme to run:  
`blogdown::new_site(theme = "same theme used by Rstudio blog")`

Thank you!

**Comment by yihui** [comment]
I'm glad that you like the theme of the RStudio blog (I was the designer), but I hope you could consider a different theme. Sorry for being selfish this time. I just want our blog's theme could be unique enough. This theme is actually based on my hugo-xmin theme: https://github.com/yihui/hugo-xmin but apparently I have heavily customized it. Please feel free to use this theme if you like, and customize it if you know CSS/HTML.

I can give you the rbind subdomain once you site is up and running on Netlify, and we have to wait for someone in the rbind team to invite you to be a member of this org first. @thercast? (or @njtierney)

**Comment by njtierney** [comment]
I've just added @johnbwilliams as a vector member, once the repo is migrated to rbind I can give ownership rights, :) 

@yihui let me know if there is anything else I can help with.

**Comment by johnbwilliams** [comment]
hugo-xmin theme sounds good.    the new_site command would then be:
`blogdown::new_site(theme = "https://github.com/yihui/hugo-xmin")` ?

**Comment by yihui** [comment]
@johnbwilliams Once you accept the invite, you can create the repo here by yourself. For the command, please see the R documentation `?blogdown::new_site` and the book section https://bookdown.org/yihui/blogdown/other-themes.html.

**Comment by johnbwilliams** [comment]
https://stackoverflow.com/questions/46232574/blogdownnew-site-bash-not-found-on-win7
