### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by gmoreno001** [rbind/support#782]
## Netlify website address

https://ginam.netlify.app/

## Preferred rbind.io subdomain

gina-m.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@gmoreno001 We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by gmoreno001** [comment]
Hello,

Thank you so much.

This is what I see (screenshot attached). Should I click “yes, add domain”?

Best,
Gina

**Comment by gmoreno001** [comment]
When I clicked “yes, add domain”, this is what I see

***@***.***D720CC.40FEDA20]

From: Gina Moreno
Sent: Wednesday, March 24, 2021 4:38 PM
To: 'rbind/support' ***@***.***>; rbind/support ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [rbind/support] rbind.io subdomain request (#782)

Hello,

Thank you so much.

This is what I see (screenshot attached). Should I click “yes, add domain”?

Best,
Gina

**Comment by gmoreno001** [comment]
![Screenshot (61)](https://user-images.githubusercontent.com/58449564/112380532-dc717f80-8cbf-11eb-9709-0ff31729a137.png)
![Screenshot (61)](https://user-images.githubusercontent.com/58449564/112380623-f90db780-8cbf-11eb-99ea-03a2a6a5e9e6.png)
The site actually does render, thank you. 
But please see the screenshot uploaded. Should I follow any of the steps there to "set up Netlify DNS for rbind.io"?

**Comment by gmoreno001** [comment]
![Screenshot (63)](https://user-images.githubusercontent.com/58449564/112396989-91fbfd00-8cd7-11eb-94e0-1efc41b84db5.png)

II would like to secure my site with HTTPS. But I run into this problem. I have created a _redirects file and placed it in the static folder as outlined in Yihui's blog post. Would greatly appreciate any advice on how to proceed. Thank you

**Comment by nanxstats** [comment]
The DNS stuff and the certificate provision warning can all be ignored.

I see HTTPS is already working, it's just that http traffic is not automatically redirected. The `_redirects` file should contain:

```
http://gina-m.rbind.io/*    https://gina-m.rbind.io/:splat  301!
```

Trigger a build to make it effective.

**Comment by gmoreno001** [comment]
Thank you for clarifying that. 

I have set up my _redirects file as you specified [here](https://github.com/gmoreno001/Test/blob/main/static/_redirects.txt)

Please let me know if you think anything does not look right. 

Thank you so much.

**Comment by nanxstats** [comment]
Two things:

- The file name should be `_redirects`  exactly - without `.txt`.
- The first line is redundant and should be removed.

**Comment by gmoreno001** [comment]
Thank you very much! I implemented your edits and it's looking good.

**Comment by gmoreno001** [comment]
Good morning,

You helped me set up a website on rbind in March. See https://github.com/rbind/support/issues/782

Recently, I keep getting this message on both Chrome and Edge web browsers when I try to visit my site at https://gina-m.rbind.io/

Do you know what the issue might be and how it can be resolved?

Thank you,
Gina

**Comment by gmoreno001** [comment]
Good morning, 

Recently, I keep getting this message on both Chrome and Edge web browsers when I try to visit my site at https://gina-m.rbind.io/ 

Do you know what the issue might be and how it can be resolved?

Thank you, 
Gina  
![rbind connection error](https://user-images.githubusercontent.com/58449564/123811671-72213a00-d8c1-11eb-8f97-28fe39f8e1cf.png)
