### ISSUE TITLE
req

### ISSUE THREAD

**Issue by soooheeel** [rbind/support#784]

**Comment by nanxstats** [comment]
@soooheeel We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by soooheeel** [comment]
**Thanks Nan. but still not working.** 

E11000 duplicate key error collection: bitballoon.projects index: dns_name_1 dup key: { dns_name: "io.rbind.sohelkhan" } (11000) (on db-origin-gc-dsm-2.node.gc-dsm.nf.internal, modern retry, attempt 1)

**How can I fix this error?**

**Comment by soooheeel** [comment]
Thanks  @nanxstats . It's working. But how can I **verify DNS** ?   sohelkhan.rbind.io is still **NOT SECURED** . how can I fix these ?
Thanks again!
-Sohel

**Comment by nanxstats** [comment]
@soooheeel Please see point 2 and 3 above.

**Comment by soooheeel** [comment]
@nanxstats thanks again.
