### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by pyrrhamide** [rbind/support#789]
## Netlify website address

kanto-does-things.netlify.app

## Preferred rbind.io subdomain

kanto.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@pyrrhamide We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by pyrrhamide** [comment]
Thank you very much! I think I'm all set.

**Comment by pyrrhamide** [comment]
Hi @nanxstats,

There seems to be a problem with the SSL certificate of the rbind.io subdomain, **in Europe**. I can't access rbind.io websites without getting an error 526 page: this was already happening on the first few days after I requested the subdomain, and it seems to be getting worse. I'm located in Paris, I apparently depend on the Cloudfare Frankfurt server. Out of curiosity, I checked other European locations using a VPN - same issue. However, when connected to a US location, all is well.

I've had a look at https://geopeeker.com/ and everything looked fine.

I thought I'd let you know. I don't really know what to do.

**Comment by nanxstats** [comment]
@pyrrhamide Thanks for the report. We received a similar report weeks ago and also from Europe: https://github.com/rbind/support/issues/462#issuecomment-818086718

This is not actionable on my side. Maybe talking to Cloudflare support would help? cc @yihui

**Comment by yihui** [comment]
Both https://kanto.rbind.io and https://algunion.rbind.io work fine for me (in the US), which is consistent with what @pyrrhamide said above. I have no idea about what's going on. Sorry. As @nanxstats suggest, perhaps you need to contact Cloudflare.

**Comment by pyrrhamide** [comment]
Alright thank you, I'll contact Cloudfare and see how it goes from here.

**Comment by pyrrhamide** [comment]
No luck on my end, Cloudflare only works with the account holder: https://support.cloudflare.com/hc/fr-fr/requests/2145150

**Comment by yihui** [comment]
https://github.com/rbind/support/issues/797#issuecomment-830434719
