### ISSUE TITLE
new domain request

### ISSUE THREAD

**Issue by mtkent1** [rbind/support#79]
Hi-

I am looking to build up my R web presence starting with learning blogdown / publishing my first site. It would be great to host my current domain mkent.netlify.com at mkent.rbind.io

Let me know if I need to do anything else.

Thanks,
Matt

**Comment by yihui** [comment]
Done. If you run into problems, please see #42.

**Comment by mtkent1** [comment]
Thanks! The only issue I am running into is Netlify stating that another site is already using the domain. I've reached out to their support for more information.

![screen shot 2017-09-15 at 7 49 00 am](https://user-images.githubusercontent.com/2981029/30480990-78ece4fc-99ea-11e7-8631-3c90b6e2e2e5.png)

**Comment by mtkent1** [comment]
This has been resolved. 

Thanks for the help and all the great work!
