### ISSUE TITLE
Error message: Add a CNAME record

### ISSUE THREAD

**Issue by JRatschat** [rbind/support#796]
Hi rbind support team,

I host my website on https://app.netlify.com/ and use the hugo-academic theme in R to make changes to the website.

I have received the following error message:

![Capture](https://user-images.githubusercontent.com/52428132/116386148-cbb1ad80-a819-11eb-8e6e-da90dd8e107f.PNG)

Also, I received the following information:

"Log in to the account you have with your DNS provider, and add a CNAME record for jratschat pointing to "-secret-"."

Could you please help me in figuring out what I have to do?

Thanks!

Best,
Jonathan

**Comment by nanxstats** [comment]
these can be safely ignored as long as the domain is working

**Comment by JRatschat** [comment]
Sadly, it is not working. Maybe you have some more information on how to solve this issue?

![image](https://user-images.githubusercontent.com/52428132/116461416-82d51580-a868-11eb-8beb-67e0b2e872da.png)

**Comment by nanxstats** [comment]
see this thread: https://github.com/rbind/support/issues/789
