### ISSUE TITLE
Error 526 with rbind website and netlify

### ISSUE THREAD

**Issue by jfsantosm** [rbind/support#797]
**Update**: for anyone reading this thread, you may skip the replies below and go to the solution at https://github.com/rbind/support/issues/797#issuecomment-830434719 directly.

---

![image](https://user-images.githubusercontent.com/50062445/116516850-6b307800-a8ce-11eb-9061-18d2c5a4550d.png)
 
![image](https://user-images.githubusercontent.com/50062445/116516911-7f747500-a8ce-11eb-99ba-f58f3f11d6a9.png)

Hello,

I have recently had problems accessing my rbind website, sometimes it works, and sometimes it does not. I have been deploying it with netlify, but as it can be seen in the picture, I get the following error.  

Error 526 Ray ID: 6476e0119b43d6e5 • 2021-04-29 07:39:13 UTC
Invalid SSL certificate

Do you know how to make my website more stable?

Best regards,
Felipe

**Comment by cderv** [comment]
I have seen the same in other website like https://advanced-r-solutions.rbind.io/

@jfsantosm I have seen you've also asked on the Netlify community : https://answers.netlify.com/t/recent-error-526-with-rbind-deployed-with-netlify/36785
This is a good idea ! Do not hesitate to share when you cross post so that we can all follow. 😄 

FWIW there is a guide post about SSL certificate on Netlify and DNS configuration: https://answers.netlify.com/t/support-guide-ssl-tls-certificate-provisioning/1300

@yihui I am not sure yet how rbind is working under the hood. Do you know what is happening ? 
Is this "https" thing new ? Do we need  to take action ? At least check DNS configuration ?

Thanks.

**Comment by cderv** [comment]
In fact looking at other issues, it seems there could be an issue for Europe https://github.com/rbind/support/issues/789#issuecomment-827488131

or Japan for you @jfsantosm ?

It has been encountered more than once recently: https://github.com/rbind/support/issues/462#issuecomment-818086718

Maybe a cloudfare issue ?

**Comment by jfsantosm** [comment]
Hi @cderv, that may explain why that is happening to me now! Because I just recently moved to Europe!

**Comment by yihui** [comment]
I don't know why this problem is specific to site visitors in Europe, and it seems to be relatively new. I'm thinking of a possible workaround right now.

**Comment by cderv** [comment]
Do you think it is rbind specific ? 

There is an answer in netlify community: https://answers.netlify.com/t/support-guide-why-isn-t-my-ssl-certificate-provisioning-automatically-with-cloudflare-netlify-are-there-other-problems-with-using-cloudflare-in-front-of-netlify/138

> Netlify won’t be able to provision an SSL certificate for your hostname(s) when the DNS records for a site point to Cloudflare because Cloudflare - not Netlify - is serving the content.
(...)
> For these reasons, we recommend disabling Cloudflare’s proxying (also known as “Accelerated and protected” on their service) for your site when it is being served/hosted by Netlify.

Could it be related here ?

**Comment by yihui** [comment]
It could be.

I've been thinking of using rewrite for all `*.rbind.io` subdomains (to the desired destination URLs) so that SSL will be irrelevant. Currently this proxy stuff is indeed complicated and unstable.

**Comment by AntoineSir** [comment]
Hi, thank you for opening this issue. I'm having the exact same problem with my domain (antoinesir.rbind.io) and I'm in France!

**Comment by yihui** [comment]
I guess we could resolve this issue in a day or two (or sooner). Sorry about the interruption!

**Comment by spcanelon** [comment]
Hello all -- just here to add that I'm having the same problem (https://silvia.rbind.io) and I'm located in the United States. Thanks for working on this @cderv and @yihui!

**Comment by aayushraman** [comment]
Hello, I am facing the same issue (https://araman.rbind.io) while my website thru netlify is still working (https://aayushraman.netlify.app/). Thanks a lot, @yihui and team! appreciate it.

**Comment by yihui** [comment]
Thanks for letting us know! I've been working on it today, and will let you all know once it's done.

**Comment by yea-hung** [comment]
I'm also seeing this issue (https://covid-19.rbind.io) in the US. Thanks all.

**Comment by AntoineSir** [comment]
> Thanks for letting us know! I've been working on it today, and will let you all know once it's done.
Everything is back to normal for me (and for the other websites mentioned above apparently), thank you very much for your work!

**Comment by jfsantosm** [comment]
Hello, same here. I have checked my website throughout the morning, and it is back to normal. I will keep checking it during the weekend. Thanks!

**Comment by yihui** [comment]
Hmm... That's funny. I was still working on a possible fix and haven't applied it yet. Not sure what happened. Perhaps time cures everything as usual :)

**Comment by aayushraman** [comment]
@yihui Still having some issues (https://araman.rbind.io). I cannot load my pic, and when I refresh the web page a couple of times, it forwards me to https://support.rbind.io/. However, my website thru netlify domain (https://aayushraman.netlify.app/) works fine.

**Comment by cderv** [comment]
It seems some stuff are not yet working well: https://advanced-r-solutions.rbind.io/

Same as above, some resources (JSS, CSS, ...) are not found and you end up on the rbind support website.
Ex: https://advanced-r-solutions.rbind.io/libs/jquery-3.5.1/jquery-3.5.1.min.js

**Comment by yihui** [comment]
@aayushraman Okay. I'm still investigating.

**Comment by aayushraman** [comment]
@yihui thanks a lot. appreciate it.

**Comment by henningsway** [comment]
Thank you so much for looking into this! :)

**Comment by gjmerrin** [comment]
I'm having the same issue in the United States. gabrieljmerrin.rbind.io
Thank you for working on the issue.

**Comment by yihui** [comment]
After spending two days on trying all possible methods to my knowledge, I'm afraid that there isn't a magic solution to fix this issue. Originally I was hoping not to let any of you do anything, but now it seems you'll have to do one thing on Netlify:

- Open https://app.netlify.com and go to your site overview. Click "Domain settings".
![image](https://user-images.githubusercontent.com/163582/116758483-be412280-a9d5-11eb-8483-28e1136b145a.png)

- Remove the `*.rbind.io` domain using the "Options" menu:
![image](https://user-images.githubusercontent.com/163582/116759651-766fca80-a9d8-11eb-9cf3-45ba47e7e662.png)

- Then add your `*.rbind.io` domain again.

- Refresh the page. Scroll to the bottom and find the **HTTPS** section. See if Netlify is able to renew the SSL certificate. If not, there should be a button named "Verify DNS" or "Renew certificate". Click on it. If it shows an error, you may have to wait for some time (perhaps one day) before you retry the certificate renewal.

Unfortunately domain issues often takes time to resolve (often hours or days). If it still doesn't work after two days, please remove the rbind.io domain from your Netlify account and let me know your rbind.io domain, I may have another solution.

**Comment by spcanelon** [comment]
> Refresh the page. Scroll to the bottom and find the **HTTPS** section. See if Netlify is able to renew the SSL certificate. If not, there should be a button named "Verify DNS" or "Renew certificate". Click on it. If it shows an error, you may have to wait for some time (perhaps one day) before you retry the certificate renewal.

Thanks Yihui! I followed the steps you described and had success clicking the "Verify DNS" button ✅ 

![Screenshot from Netlify showing 'DNS verification was successful' under the SSL/TLS certificate header.](https://user-images.githubusercontent.com/49913337/116766809-6ec11d80-a9fa-11eb-81a1-7ebd18ef8333.png)

**Comment by chenchenzi** [comment]
Thanks! I had the same issue and now it worked.

**Comment by henningsway** [comment]
same here, thanks! :)

**Comment by jfsantosm** [comment]
Same here; it is working after following @yihui suggestions.  Thanks!!!!

**Comment by benthecoder** [comment]
@yihui I tried the suggestions but the verification success goes away after I refresh it. Any idea how to make the verification permanent?

**Comment by huttoncp** [comment]
Mine is also working now. Thanks @yihui!!!

**Comment by aayushraman** [comment]
Same here, thanks a lot @yihui!

**Comment by andresrcs** [comment]
I was getting depressed because all of the sudden my blog was hardly getting any hits and it turned out to be because of this certificate issue. I hadn't noticed because I rarely visit my own blog. Thanks for the solution!

**Comment by petetalbert** [comment]
That worked, thanks as always @yihui!
