### ISSUE TITLE
Moving ellakaye.rbind.io to a new site

### ISSUE THREAD

**Issue by EllaKaye** [rbind/support#800]
## Netlify website address

ellakaye.netlify.app

## Preferred rbind.io subdomain

ellakaye.rbind.io

## Note

I already have the ellakaye.rbind.io subdomain attached to ellakaye.netlify.app. I previously had a Hugo website at those addresses. I have now replaced my hugo site with one built with {distill}. On netlify, I have changed my Hugo website to ellakayehugo.netlify.app and set my new distill blog to ellakaye.netlify.app. I was expecting ellakaye.rbind.io to pick up the new {distill} site now at ellakaye.netlify.app. However, ellakaye.rbind.io is still picking up the old hugo site. Is this something I can fix and, if so, how? Or does this require some intervention on your side? 

To make things more complicated, my hugo site is broken (somehow I've managed to uninstall hugo (?!) and am struggling to reinstall it, so it'll be a challenge if I need to push some changes to that to get things working again.

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@EllaKaye The first thing I would try is removing the rbind subdomain from where it is right now using the "Options" menu. Then add the subdomain to the preferred site.

In case there are some DNS related issues, check out [this comment](https://github.com/rbind/support/issues/797#issuecomment-830434719).

**Comment by EllaKaye** [comment]
@nanxstats thanks so much for getting back to me so quickly, and pointing me in the direction of the appropriate netlify settings. Yes, that solved the issue, and DNS seems OK.
