### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by shilaan** [rbind/support#801]
## Netlify website address

shilaan.netlify.app

## Preferred rbind.io subdomain

shilaan.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

I plan to make good use of my website in the future. Thank you so much!

**Comment by jlt10f** [comment]
Current netlify website address: 
tockademic.netlify.app

preferred rbind.io subdomain: 
tockademic.rbind.io

P.S. I am a stats person and learning the programming and website design parts so please let me know if I am not doing this right.

**Comment by nanxstats** [comment]
@shilaan We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by shilaan** [comment]
@nanxstats Thank you so much, Nan!

**Comment by shilaan** [comment]
Hi Nan, I've been running into issues with the DNS configuration for my custom domain. (Error message under Netlify > Domain Management > HTTPS: We could not provision a Let’s Encrypt certificate for your custom domain.) When navigating to my site, users now get a "This Connection is Not Private" notification. 

Any advice here on what to do? I've tried verifying the DNS configuration, but get the same error message.

**Comment by nanxstats** [comment]
Hi @shilaan in case it helps, if you see the "connection is not private" issue again, please try this fix https://github.com/rbind/support/issues/797#issuecomment-830434719 again.

**Comment by shilaan** [comment]
Thank you so much, Nan!
