### ISSUE TITLE
rbind.io error connection is not private

### ISSUE THREAD

**Issue by GiuliaSolinas** [rbind/support#807]
Hi rbind team, 

I have an issue with my website gsolinas.rbind.io. When trying to connect, it displays an error in the certificate and the site is flagged as not secure (see screenshot). A few weeks ago there was another error message that the SSL certificate was invalid, but it disappeared and started working again until today. 

I would love it if you can provide assistance. Thanks!
Giulia
<img width="1187" alt="rbind_insecure_connection" src="https://user-images.githubusercontent.com/39096166/118860421-a9242900-b8db-11eb-900a-105d4b71a1c5.png">

**Comment by yihui** [comment]
https://github.com/rbind/support/issues/797#issuecomment-830434719

**Comment by anishajayadevan** [comment]
Hi rbind team,

I have a similar issue. I tried the fix suggested by @yihui above with no luck.

I used blogdown and Hugo academic to build a new website. It was originally deployed on anishajayadevan.netlify.app and now resides at https://anishajayadevan.rbind.io. I have updated baseURL to point to the latter link in config.toml.

I have also created a _redirects file which I have placed in static/ [here](https://github.com/anishajayadevan/anishajayadevan/blob/main/static/_redirects).

However, http:// does not get redirected to https://. And https://anishajayadevan.netlify.app does not get redirected to rbind.io either.

When I log in to Netlify, I also see this message:
![Screenshot from 2021-07-01 17-46-46](https://user-images.githubusercontent.com/56602403/124193165-5e79fd00-da94-11eb-854b-d24016317f39.png)

I'd appreciate any help!
