### ISSUE TITLE
Deleting issues & blocking users

### ISSUE THREAD

**Issue by apreshill** [rbind/support#808]
Hi- since I transferred my repo here, I am not able to [delete issues](https://docs.github.com/en/github/managing-your-work-on-github/managing-your-work-with-issues-and-pull-requests/deleting-an-issue) in my repo. I'm experiencing spam currently, and would like to delete issues rather than just close them. 

I also attempted to [block](https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-personal-account) the user via GitHub, but I'm not sure if that will work because I was only able to block them from my personal account. What is a good solution here?

**Comment by apreshill** [comment]
Edit: blocking this user personally does not stop them from posting issues to the rbind/apreshill repo

**Comment by nanxstats** [comment]
thanks for the report @apreshill -you are now admin of the repo

**Comment by apreshill** [comment]
Thank you so much @nanxstats! Realizing this was one of the downsides of using utterances with my current setup.
