### ISSUE TITLE
subdomain request

### ISSUE THREAD

**Issue by jessicarose1974** [rbind/support#809]
## Netlify website address

https://goofy-girl-forever.netlify.app

## Preferred rbind.io subdomain

https://goofy-girl-forever.rbind.io

### Jessica Rose

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@jessicarose1974 We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by jessicarose1974** [comment]
hi there, sorry i am VERY new to this. how do i add the rbind subdomain to my account?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by nanxstats** [comment]
@jessicarose1974 -please see the screenshot above, or additionally: https://docs.netlify.com/domains-https/custom-domains/

**Comment by jessicarose1974** [comment]
ah yes i didn't see the screenshot... thank you. mission accomplished :)

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
