### ISSUE TITLE
domain request

### ISSUE THREAD

**Issue by ebologna** [rbind/support#813]
## Netlify website address

https://manualestadistica.netlify.app

## Preferred rbind.io subdomain

manualestadisticabologna.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@ebologna I see a soft 404 at the current site. Could you please deploy some content there first?

**Comment by ebologna** [comment]
I am sorry I don´t know how to solve it. It is linked to my repo ebologna/EstadisticaParaCienciasSocialesConR
I´ll search how to fix it
thank you

**Comment by nanxstats** [comment]
I'm closing this for now - please feel free to create a new request when the site is ready.
