### ISSUE TITLE
requesting a domain name

### ISSUE THREAD

**Issue by maheen** [rbind/support#818]
## Netlify website address

I am not building my site on Netlify. I am building it through WordPress (.org) and it will be hosted through Hostinger. Is that enough information?

## Preferred rbind.io subdomain

wheredmanogo.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by maheen** [comment]
Sorry, I forgot the mention that Hostinger has informed me the following are their DNS nameservers:
ns1.dns-parking.com
ns2.dns-parking.com

**Comment by nanxstats** [comment]
I'm not entirely sure. Any thoughts @yihui?

**Comment by yihui** [comment]
No, we can't support different nameservers. Sorry. We can only support DNS records such as A or CNAME.

**Comment by maheen** [comment]
Thank you for your response! I checked with Hostinger and they said an A record could be created for the domain and pointed to the following IP address: 213.190.6.154

Would this be a feasible alternative?

Thanks again for your help.

**Comment by yihui** [comment]
Yes. We have created the A record.

**Comment by nanxstats** [comment]
I'm closing this as it looks like the subdomain is working.
