### ISSUE TITLE
Mixed content blocking on drewtyre.rbind.io

### ISSUE THREAD

**Issue by atyre2** [rbind/support#82]
I'm seeing
![image](https://user-images.githubusercontent.com/2787883/30521365-146bd966-9b84-11e7-8bee-4f375d5581ec.png)
on Firefox, and a similar "non-secure" message on Chrome. 

It seems to be related to the disqus comments (from web console):
Loading mixed (insecure) display content “http://bcp.crwdcntrl.net/5/c=8879?https%3A%2F%2Flinks.services.disqus.com%2Fapi%2Fsync%2Flot%2Fmatch%3Fuid%3D%24%7Bprofile_id%7D” on a secure page

but it doesn't happen on all the pages that have disqus comment blocks.

A big of digging around lead me to this blog post
https://www.troyhunt.com/disqus-mixed-content-problem-and-fixing-it-with-a-csp/

Copying
```
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
```
into the header.html partial of the hugo template seems to have fixed the problem.

**Comment by yihui** [comment]
Take a look at your HTML source, and you can see there are a few http resources. I don't know why they used the nonsecure protocol, but you can try to force HTTPS on Netlify (https://app.netlify.com Site Settings -> Domain Management -> HTTPS):

![image](https://user-images.githubusercontent.com/163582/30528996-396f2e50-9bfe-11e7-9592-2005c8e4ba5c.png)

**Comment by atyre2** [comment]
Wow! no kidding ... yeesh. OK, thanks for pointing that out. Alot of those are links I inserted, but quite a few from the academic theme and gitbook too. I've got some link checking to do, apparently.
