### ISSUE TITLE
Connecttion error issue with rbind.io

### ISSUE THREAD

**Issue by gmoreno001** [rbind/support#825]
Good afternoon, 

You helped me set up a website on rbind in [March](See https://github.com/rbind/support/issues/782). 

Recently, I keep getting this message on both Chrome and Edge web browsers when I try to visit my [site](https://gina-m.rbind.io/)

Do you know what the issue might be and how it can be resolved?

Thank you,
Gina
![rbind connection error](https://user-images.githubusercontent.com/58449564/123835500-9dfaea80-d8d6-11eb-807c-241561109588.png)

**Comment by nanxstats** [comment]
@gmoreno001 try this: https://github.com/rbind/support/issues/797#issuecomment-830434719

**Comment by gmoreno001** [comment]
Thank you! I believe this worked right away.
