### ISSUE TITLE
rbind.io does not redirect to https://

### ISSUE THREAD

**Issue by anishajayadevan** [rbind/support#826]
Hi rbind team,

I used blogdown and Hugo academic to build a new website. It was originally deployed on anishajayadevan.netlify.app and now resides at https://anishajayadevan.rbind.io. I have updated baseURL to point to the latter link in config.toml.
I have also created a _redirects file which I have placed in static/ [here](https://github.com/anishajayadevan/anishajayadevan/blob/main/static/_redirects).
However, http:// does not get redirected to https://. And https://anishajayadevan.netlify.app does not get redirected to rbind.io either.
When I log in to Netlify, I also see this message:

![Screenshot from 2021-07-01 17-46-46](https://user-images.githubusercontent.com/56602403/124298741-9e8bbf00-db2a-11eb-9a87-6c491b68cc33.png)

I tried the fix suggested by @nanxstats [here](https://github.com/rbind/support/issues/797#issuecomment-830434719), with no luck.

I'd appreciate any help!

**Comment by lilynuraini** [comment]
I also have the same problem with the rbind.io domain. Still facing the issue after trying the fix. Need help from the support team. Thanks.

**Comment by nanxstats** [comment]
Looks like https is working, so the issue is probably about the `_redirects`, other than the domain stuff. Maybe checking whether the rules are successfully processed in the deploys would help?

<img width="1289" alt="Screen Shot 2021-07-05 at 10 40 04 PM" src="https://user-images.githubusercontent.com/199363/124534439-47b00f00-dde2-11eb-9492-a07ab2aa1c09.png">

**Comment by anishajayadevan** [comment]
Thanks @nanxstats ! This helped. The redirect rules were not being processed. There was an index.redirects which was being built into a _redirects file. I copied my redirect rules to that file and that solved it.
