### ISSUE TITLE
rbind.io redirect issue

### ISSUE THREAD

**Issue by lilynuraini** [rbind/support#828]
Hi team,

after trying [the fix](https://github.com/rbind/support/issues/826#issuecomment-874823576), the redirect rules are deployed but I'm still facing the same issue.

![redirects_deployed](https://user-images.githubusercontent.com/65600589/124883071-2d9d4900-dffb-11eb-8540-c9bfd27242d4.JPG)

![certificate_issue](https://user-images.githubusercontent.com/65600589/124883138-3a21a180-dffb-11eb-8153-93e86db61fe0.JPG)

Need help from the team. Thanks.

**Comment by lilynuraini** [comment]
want to add a few things,
when I try opening the old domain (https://lilywrites.netlify.app), it redirects to https://lily.rbind.io just fine with the secure connection.

![image](https://user-images.githubusercontent.com/65600589/124886415-6a1e7400-dffe-11eb-8960-1fe043c3c3da.png)

However, when I visit lily.rbind.io directly, the connection is still not secure

![image](https://user-images.githubusercontent.com/65600589/124886515-81f5f800-dffe-11eb-83f7-9fa55bff806e.png)

or it shows this

![image](https://user-images.githubusercontent.com/65600589/124885943-fed4a200-dffd-11eb-9e4a-d4e0cb02ec3b.png)

**Comment by nanxstats** [comment]
The redirect rules look ok to me. So probably it is not related to the issue in #826.

I wonder if this is related to how the subdomain is added on Netlify. The screenshot in #826 says "We could not provision a Let's Encrypt certificate for your custom domain", which is different from your second screenshot.

Maybe try removing and re-adding the custom domain like this? 👉 https://github.com/rbind/support/issues/797#issuecomment-830434719

**Comment by lilynuraini** [comment]
I've tried [the fix that you mentioned](https://github.com/rbind/support/issues/797#issuecomment-830434719)  several times but the issue is still there.

Here's the screenshot after re-adding the domain, it's the same as issue [#826](https://github.com/rbind/support/issues/826)
![image](https://user-images.githubusercontent.com/65600589/125165761-97b41a80-e1c2-11eb-8868-842b5bde8eb5.png)

And this is after I click 'verify DNS configuration' button
![image](https://user-images.githubusercontent.com/65600589/125165812-caf6a980-e1c2-11eb-960c-14bdc7a8cb51.png)

**Comment by nanxstats** [comment]
Thanks for trying it out. I get random results when accessing the three links:

- `https://lily.rbind.io`: rendering content, or showing err_too_many_redirects
- `http://lily.rbind.io`: redirected to `https://lily.rbind.io` and rendering content, or still `http://lily.rbind.io` and rendering content
- `https://lilywrites.netlify.app`: redirected to `https://lily.rbind.io` and rendering content, or redirected but showing err_too_many_redirects

I would suggest contacting Netlify support since this is probably more related to their infrastructure.

**Comment by lilynuraini** [comment]
I will contact netlify support and close this issue. Thanks for your help.

**Comment by lilynuraini** [comment]
I reopen this issue since I get the reply from netlify support team saying that the subdomain is still not pointing to netlify and also because I don't have access to the cloudflare. Here's the [link of the full conversation](https://answers.netlify.com/t/provision-certificate-error-for-custom-domain/40878). Could the team help me to check from the cloudflare side? thanks

**Comment by nanxstats** [comment]
I'm running out ideas at the moment. Maybe @yihui could take a look at this?

**Comment by yihui** [comment]
@lilynuraini Please retry the fix.

**Comment by lilynuraini** [comment]
It works now. Thank you all for the help.
