### ISSUE TITLE
hugo-lithium-theme: display of tags & categories

### ISSUE THREAD

**Issue by johnbwilliams** [rbind/support#83]
(please let me know if this is not the right forum for these questions, thanks)

- Current phase of learning blogdown: adding features to default theme.
- Added to config.toml:
```
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
```
Is it possible to upgrade the display of categories and tags?   Currently display as:

```
Index of ./categories/
Name	Size	Date Modified
./		2017-09-15 09:55:53
../		2017-09-16 22:03:12
r/		2017-09-15 09:55:53
index.xml	695 B	2017-09-17 14:25:01
```

```
Index of ./tags/
Name	Size	Date Modified
./		2017-09-15 15:31:46
../		2017-09-16 22:03:12
aws/		2017-09-15 15:31:46
openemr/		2017-09-15 15:31:46
plot/		2017-09-15 09:55:53
r-markdown/		2017-09-15 09:55:53
regression/		2017-09-15 09:55:53
index.xml	1,199 B	2017-09-17 14:36:01
```
Thank you!

**Comment by yihui** [comment]
This theme does not have the template for taxonomies (`terms.html`), so the index pages will not be generated (e.g., `tags/index.html`). If you want to add it, you need to spend some time on learning more about Hugo themes and templates: https://bookdown.org/yihui/blogdown/templates.html

**Comment by yihui** [comment]
BTW, as I mentioned in the blogdown announcement, StackOverflow is the best place to ask questions: https://blog.rstudio.com/2017/09/11/announcing-blogdown/

We also mentioned at https://support.rbind.io/about/ that this repo is not the place to ask questions about blogdown.

[More on this if you care...](https://yihui.name/en/2017/08/so-gh-email/)

**Comment by yihui** [comment]
For the record, this issue was also cross-posted on StackOverflow: https://stackoverflow.com/q/46285271/559676
