### ISSUE TITLE
rbind.io 与 netlify.com 解除绑定，然后与 vercel.app 绑定

### ISSUE THREAD

**Issue by chuxinyuan** [rbind/support#839]
益辉、肖楠

向你们问好！首先感谢你们给了我一个免费的域名 cxy.rbind.io , 之前我申请过 cxy.netlify.com 与 cxy.rbind.io 绑定的，但是 netlify.com 目前我登录不上去，没法通过删除域名再重新添加以实现更新 SSL 证书 <https://github.com/rbind/support/issues/797#issuecomment-830434719>，导致我的 cxy.rbind.io 在 Chromium 内核的浏览器上无法访问（Firefox 浏览器可以访问，但是有安全提示），所以我现在想让完成以下操作：

1. 先让 cxy.rbind.io 与 cxy.netlify.com 解除绑定
2. 然后让 cxy.rbind.io 绑定 deepin.vercel.app

同时，我也注意到绑定 `.app` 结尾的域名可能存在潜在的问题 <https://github.com/rbind/support/issues/771>，我可以配合你们进行测试，我想即使有点问题也比不能访问要好的多，因此我很愿意一试。

给你们带来了许多麻烦，实在不好意思，请多多包涵。再次对你们的辛勤付出表示感谢！

楚新元
2021/8/16

**Comment by nanxstats** [comment]
Maybe @yihui can help you here

**Comment by yihui** [comment]
已经修改域名记录。

**Comment by chuxinyuan** [comment]
这下 cxy.rbind.io 又活过来了！感谢 @yihui @nanxstats

**Comment by chuxinyuan** [comment]
这下 cxy.rbind.io 又活过来了！感谢 @yihui @nanxstats
