### ISSUE TITLE
Subdomain for rbind.io

### ISSUE THREAD

**Issue by retaoliveira** [rbind/support#845]
## Preferred rbind.io subdomain

retaoliveira.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

## Current site

https://retaoliveira.space

**Comment by nanxstats** [comment]
@yihui -do we support top level domains?

**Comment by yihui** [comment]
Technically, yes. In practice, if I have a top-level domain, I'd prefer using that domain instead of a subdomain. That said, it's totally up to you @retaoliveira. If you prefer using a subdomain, we can definitely support it.

**Comment by nanxstats** [comment]
-great, just to follow up, what do you think? @retaoliveira

**Comment by nanxstats** [comment]
I'm closing this for now due to inactivity.
