### ISSUE TITLE
Transfering Netlifly to GitHub Pages (keep rbind.io subdomain)

### ISSUE THREAD

**Issue by plbaldoni** [rbind/support#851]
Hi there, 

I own the subdomain plbaldoni.rbind.io, but I have just deleted my Netlify website address.

Would it be possible to have my new Github-hosted website [plbaldoni.github.io](https://plbaldoni.github.io/) linked to the plbaldoni.rbind.io subdomain?

Thanks!
Pedro

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Yes I think so.

@yihui -could you help update the record here?

@plbaldoni -for GitHub Pages, please put a CNAME file in your repo, like in https://github.com/rbind/support/issues/139

**Comment by yihui** [comment]
Done.

**Comment by plbaldoni** [comment]
Thanks both for helping me with this, the plbaldoni.rbind.io subdomain is up again.

Could you tell me how I can have it redirected to use https? I have enforced it on GitHub pages, but it does not seem to be working.

<img width="935" alt="Screen Shot 2021-10-15 at 8 32 06 AM" src="https://user-images.githubusercontent.com/26856909/137398941-04ae97ef-82b2-483a-9386-9726c9360575.png">

**Comment by yihui** [comment]
Perhaps you just need to wait for a while; https works fine to me:

![image](https://user-images.githubusercontent.com/163582/137401892-c21ddb39-f95b-41d6-bae0-ed001ba8ca24.png)

**Comment by plbaldoni** [comment]
Great, thanks!

**Comment by plbaldoni** [comment]
I wasn't sure if I should have opened a new issue for this. 

Could someone help me understand why https://plbaldoni.rbind.io is no longer pointing correctly to my page https://plbaldoni.github.io that is hosted in this repository https://github.com/plbaldoni/plbaldoni.github.io?

**Comment by nanxstats** [comment]
It looks like the `CNAME` file was removed on August 3 and re-added on August 16 in your repo. During that window, on August 6, `plbaldoni.rbind.io` was hijacked to this (untrusted) repo: https://github.com/rajveersen/plbaldoni.rbind.io.

So this might be related to how GitHub Pages custom domain works. The DNS records all seem ok though via `dig` and `nslookup`.

In this case, I will let @yihui take a further look and suggest a solution.

**Comment by yihui** [comment]
I'm afraid I can't do anything about it. You need to contact Github. The user `rajveersen` appears to be a spam account. It also hijacked another domain: https://github.com/rajveersen/amiasi/blob/main/CNAME I suggest you report it to Github. I feel this is a serious security hole of Github.

In future, please be careful when removing CNAME from your repo. When you have to do it, make sure the DNS record is also removed.

**Comment by plbaldoni** [comment]
I have reported this to GitHub and they have put the user `rajveersen` down and consequently https://plbaldoni.rbind.io. 

Thanks for point out the CNAME issue, I missed that when updating the `postcards` package and pushing all the changes without looking carefully which files were being deleted.

Is there any way plbaldoni.rbind.io can be recovered?

**Comment by yihui** [comment]
A quick search reveals that `rajveersen` was not the only one who attempted to hijack your domain name after you accidentally gave it up: https://github.com/search?q=plbaldoni.rbind.io&type=code You need to defeat these spammers before you are able to re-claim this domain. Again, please contact Github. I'm not sure if they could directly assign this domain to your Github pages, instead of letting those obvious spammers abuse it.

> without looking carefully which files were being deleted.

I guess you have learned the lesson: always make sure you know what you are committing in Git.

Or just manage the source instead of output in Git, because output files can be messy (e.g., use Netlify or Vercel, instead of Github pages).

**Comment by plbaldoni** [comment]
Thanks Yihui, I have learned my lesson indeed.

I got a response from GitHub and the user `unamemad` has also been put down. 

> Our review of the content named in your report has concluded. We have determined that one or more violations of GitHub’s Terms of Service have occurred and have taken appropriate action in response, you should now be able to get the CNAME back.

**Comment by yihui** [comment]
The DNS record on our side is still correct, and there isn't anything we need to do. On your side, you may need to set the domain name again in your repo settings.

**Comment by nanxstats** [comment]
Just checked and looks like the problem has been resolved so I'm closing this. Thanks everyone!
