### ISSUE TITLE
feature request:  meme

### ISSUE THREAD

**Issue by johnbwilliams** [rbind/support#87]
http://rpubs.com/johnbwilliams/blogdown_meme

**Comment by yihui** [comment]
This technology is called the Open Graph (OG) Protocol: http://ogp.me

Hugo has some internal templates for OG: https://gohugo.io/templates/internal/ e.g. `_internal/opengraph.html` and `_internal/twitter_cards.html`. But the worst thing about Hugo is its documentation... Again, these templates are not documented, and you must dig the source code to know how to properly use them: 

https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/template_embedded.go

It is more of a Hugo question than blogdown.

I mentioned in #83 but you seem to have ignored it, so once again:

> As I mentioned in the blogdown announcement, StackOverflow is the best place to ask questions: https://blog.rstudio.com/2017/09/11/announcing-blogdown/
>
> We also mentioned at https://support.rbind.io/about/ that this repo is _not the place_ to ask questions about blogdown.
>
> [More on this if you care...](https://yihui.name/en/2017/08/so-gh-email/)

If it is not clear to you, please ask the question on StackOverflow.
