### ISSUE TITLE
New rbind.io subdomain request

### ISSUE THREAD

**Issue by rikudoukarthik** [rbind/support#873]
## Netlify website address

thepageofsixpaths.netlify.app

## Preferred rbind.io subdomain

kartrick.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@rikudoukarthik We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by rikudoukarthik** [comment]
Thank you so much, Nan. I look forward to watching and learning from the rbind community!

**Comment by rikudoukarthik** [comment]
Hi @nanxstats, I am interested in creating sub subdomains for my existing Hugo-blogdown website, where I can host completely independent projects, like Quarto notebooks for instance. So, what I want is something like `newproject.kartrick.rbind.io` which would point to a separate netlify website (as opposed to `kartrick.rbind.io/newproject`.

I know this requires setting the `CNAME`, but I'm unsure where or how. Would you be able to help me out with this, and do I need to ask here each time I want a new sub subdomain? Please let me know, and I can let you know the Netlify address I want to point to (maybe as a new issue).

Thanks!

**Comment by nanxstats** [comment]
@rikudoukarthik Each of them will just be another subdomain (with a character `.` in them) that needs to be added separately, see this previous explanation: https://github.com/rbind/support/issues/149#issuecomment-365345706

From the SEO perspective though, I think it's often better to use a single domain with subdirectories (example.com/project/) instead of using many subdomains (project.example.com), because search engines see subdirectories as part of the main domain while different subdomains are ranked as separate entities.

**Comment by rikudoukarthik** [comment]
@nanxstats Sorry for taking long to get back, and thanks for the help! I am not too concerned about SEO for these cases, since they are open-notebook type sites that I just want linked to my personal website.

I have two requests this time:

1. Netlify: `https://kartrix-travel-log.netlify.app/`. Preferred subdomain name: `https://travels.kartrick.rbind.io`.
2. Netlify: `https://kartrix-phd-notebook.netlify.app/`. Preferred subdomain name: `https://phdnotebook.kartrick.rbind.io`.

You will find a 404 error on the second Netlify link; this seems to be a build issue which I am trying to fix on my end. I hope you will still be able to configure the subdomain though.

Thanks!

**Comment by nanxstats** [comment]
@rikudoukarthik Great, we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by rikudoukarthik** [comment]
@nanxstats Thanks! I'm having trouble adding the custom domains. It tells me:

> Domain rbind.io is already registered and not owned by your account. Before clicking Add subdomain, add the following TXT record to your DNS provider so we can verify your domain.

Do you need me to paste the codes here for both sites?

![Image](https://github.com/user-attachments/assets/decd537a-2e22-4fe7-925f-0ffbcafbeec6)

**Comment by nanxstats** [comment]
I'm copying @yihui for awareness. This seems to be a recent change from Netlify. I think it would be the best to reach out to Netlify support to see why is this needed. If it continues, we might need to change the recommended site hosting provider.

**Comment by yihui** [comment]
If the TXT record is required now, I feel we will have to stop providing more rbind.io subdomains (existing subdomains will continue to work), since we can't afford the time to set up this record for everyone...

**Comment by nanxstats** [comment]
I agree, it will also be too many TXT records to maintain even if it can be automated. To minimize the impact, updating all relevant documentation to specifically exclude Netlify is also a possibility.

**Comment by yihui** [comment]
I think the only place where I mentioned the rbind.io subdomain is the blogdown book, and I just deleted that paragraph from the book.

I'll sunset this subdomain service if we run into the TXT record problem again. Over the 8 years, we as volunteers have offered 800+ subdomains to the community. I guess it's time for us to stop here. One future alternative to the subdomain service is the `rbind.io/repo` subpath service. That is, I can bind `rbind.github.io` to `rbind.io`, then users can publish to Github Pages in their rbind repo, and their sites can be accessed via `https://rbind.io/repo-name/`. In this case, we no longer need to set up the subdomain one by one, and only need to invite users to the Github rbind organization.

**Comment by drjoseluisheram** [comment]
Very sad that my first approach to rbind would finish like this. Thank you.

**Comment by yihui** [comment]
@drjoseluisheram Since you use Quarto, Quarto also provides `*.quarto.pub` domains: https://quarto.org/docs/publishing/quarto-pub.html

**Comment by rikudoukarthik** [comment]
It's been a while, but I just wanted to thank you folks for supporting this subdomain service for as long as you did. The sunset is sad, but completely understandable as the best way forward.
