### ISSUE TITLE
Requesting subdomain for chester.rbind.io

### ISSUE THREAD

**Issue by ismayc** [rbind/support#88]
Hello,

I'd like to request an rbind.io subdomain for my personal page. The site is deployed through Netlify and currently lives at: http://chester.netlify.com.

Can I have chester.rbind.io?

Thanks!
Chester

PS If this is a hugo+blogdown specific thing, I'll convert everything over to blogdown and repost as needed.

**Comment by yihui** [comment]
Done on my side. You need to contact Netlify support (#42).

There is no need or hurry to switch to blogdown.
