### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by guang-yu-zhu** [rbind/support#881]
I've been using the subdomain guangyuzhu.rbind.io for my website and just started seeing the error

> The SSL certificate presented by the server did not pass validation. This could indicate an expired SSL certificate or a certificate that does not include the requested domain name. Please contact your hosting provider to ensure that an up-to-date and valid SSL certificate issued by a Certificate Authority is configured for this domain name on the origin server. Additional troubleshooting information here.

Any ideas? Thanks!

**Comment by nanxstats** [comment]
am forwarding this to @yihui

**Comment by yihui** [comment]
Does this work? https://github.com/rbind/support/issues/797#issuecomment-830434719

**Comment by guang-yu-zhu** [comment]
It somehow worked. Thanks!

**Comment by guang-yu-zhu** [comment]
After I renewed the certificate. I got this result:
[image: image.png]
Does this mean the problem is solved?

In the meantime, if I open with chrome, it says the website is not secure:
[image: image.png]

**Comment by guang-yu-zhu** [comment]
After I renewed the certificate. I got this result:
![image](https://user-images.githubusercontent.com/7520628/153117096-40a6fbd5-baa8-47f4-892e-862635a1625a.png)
Does this mean the problem is solved?

In the meantime, if I open with chrome, it says the website is not secure:
![image](https://user-images.githubusercontent.com/7520628/153117115-be227118-9c28-4ca2-a971-9cf3c8a641ce.png)

**Comment by yihui** [comment]
I just checked it and it was okay in my Chrome:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/163582/153890800-2b2c033a-6fd1-43a6-badf-ff154671f0ce.png">

I think this issue has been resolved so I'll close it. We can re-open it if the issue still exists.

**Comment by guang-yu-zhu** [comment]
Thanks!
