### ISSUE TITLE
rbind subdomain request

### ISSUE THREAD

**Issue by nBhabish** [rbind/support#884]
## Netlify website address

https://nbhabish.netlify.app/

## Preferred rbind.io subdomain

nbhabish.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@nBhabish I see `nbhabish.rbind.io` already points to `nbhabish.netlify.app` (https://github.com/rbind/support/issues/794). Do you want us to update the record or else?

**Comment by nanxstats** [comment]
@nBhabish Just a reminder to add the subdomain to your website.

**Comment by nanxstats** [comment]
@nBhabish Another reminder to add the subdomain to your website, please. Otherwise we will start removing the subdomain.

**Comment by nanxstats** [comment]
@yihui could you please remove the subdomain `nbhabish.rbind.io` as the requester hasn't responded in quite a while. Thanks!

**Comment by yihui** [comment]
Done.
