### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by johnbwilliams** [rbind/support#89]
Hi,

My blogdown site is living at www.openemr.blog.    Netlify supports domain aliases, so I'd like to support the blogdown communty with an rbind.io domain alias.

Is  openemr.rbind.io  available? 

Thanks

**Comment by yihui** [comment]
It is. How do you want me to set the CNAME record?

**Comment by johnbwilliams** [comment]
please set the CNAME record for `openemr.rbind.io` to `openemr.netlify.com`

thanks for the excellent blogdown book appendix on DNS records

**Comment by yihui** [comment]
I have configured the rbind subdomain you requested, but you have to contact Netlify support and they will configure it on their side (#42).

**Comment by johnbwilliams** [comment]
Thanks Yihui!

From Netlify Support:
Got that domain alias in place for you, John.  Should be working already :)  We call those "domain aliases" in case you want to add one in the future: https://app.netlify.com/sites/openemr/settings/domain#domain-aliases
