### ISSUE TITLE
Domain name request

### ISSUE THREAD

**Issue by chunjiw** [rbind/support#90]
Hi,

I am requesting for the chunjiw.rbind.io domain name for my new netlify website chunjiw.netlify.com. Please let me know whether I'm doing it right. Thank you!!

Chunji

**Comment by yihui** [comment]
I have configured the rbind subdomain you requested, but you have to contact Netlify support and they will configure it on their side (#42).

**Comment by chunjiw** [comment]
Thank you! chunjiw.rbind.io now works smoothly. People at Netlify are very helpful.

**Comment by yihui** [comment]
Yes, indeed they are.
