### ISSUE TITLE
rbind.io domain request

### ISSUE THREAD

**Issue by jackmurtagh** [rbind/support#905]
## Netlify website address

I am not building my site on Netlify. I am building it through WordPress (.org) and it will be hosted through Hostinger. The people at Hostinger said an A record could be created for the domain and pointed to the following IP address: 213.190.6.154

## Preferred rbind.io subdomain

jackmurtagh.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Let me ask @yihui to help you here, as there was a similar case in https://github.com/rbind/support/issues/818.

**Comment by yihui** [comment]
Done.
