### ISSUE TITLE
rbind.io subdomian request

### ISSUE THREAD

**Issue by earfanfan** [rbind/support#906]
## Netlify website address

I have a Vercel blog, the website address is "yuanfan.vercel.app" . But,  yesterday, i can not visit my blog(PS.I live in China), because of [some reason](https://github.com/vercel/community/discussions/803). So, i make this submit.

## Preferred rbind.io subdomain

yuanfan.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@earfanfan We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Vercel account as the custom domain to your site: https://vercel.com/docs/concepts/projects/custom-domains. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

2. There might be messages saying "DNS verification failed" or "check DNS configuration" after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by earfanfan** [comment]
@yihui
原来那个在中国大陆不能访问的博客我没动，搭了个[新的](https://resplendent-basbousa-abbd94.netlify.app/)，新博客是用netlify部署的，现在我要将它重定向到我已经申请的[rbind二级域名](https://yuanfan.rbind.io/)上面去，但我现在到不了重定向那一步。

![image](https://user-images.githubusercontent.com/29876335/187947173-fd5a34b2-ac1e-4e95-b152-67a23ae1cd0c.png)

![image](https://user-images.githubusercontent.com/29876335/187946656-1f60413f-cfdd-4705-bc32-be783584f1d0.png)

这里我只需要等24小时么？

**Comment by yihui** [comment]
不是要等，而是我们把 `yuanfan.rbind.io` 指向了 `yuanfan.vercel.app`。我刚给你换到 netlify.app 域名上了。你再点一下 Check DNS configuration。

**Comment by earfanfan** [comment]
哦，明白了。是因为我变卦了，所以原先Nan帮忙配置的就失效了。

**Comment by yihui** [comment]
是的。

现在我看已经绑好了。你可以把 yuanfan.rbind.io 设置为主域名，然后把那一串又臭又长的 netlify.app 域名重定向到主域名上。
