### ISSUE TITLE
rbind.io 与 vercel.com 解除绑定，然后与 netlify.app 绑定

### ISSUE THREAD

**Issue by chuxinyuan** [rbind/support#907]
益辉、肖楠

向你们问好！因为 vercel 国内貌似被墙了，具体可以看看统计之都的帖子[https://*.vercel.app/ 貌似都打不开了啊](https://d.cosx.org/d/423443-httpsvercelapp-mao-si-du-da-bu-kai-liao-a)，本来打算用 gitlab pages，但是部署的速度实在是太慢，docker 里需要安装一堆东西，推送过去大概需要5分钟才能部署好，暂时打算还是netlify吧，所以我现在想让完成以下操作：

1. **先让 cxy.rbind.io 与 deepin.vercel.app 解除绑定**
2. **然后让 cxy.rbind.io 绑定 cxy.netlify.app**

来来回回的折腾了好几次了，给你们带来了许多麻烦，实在不好意思，请多多包涵。再次对你们的辛勤付出表示感谢！

楚新元
2022年8月28日

**Comment by nanxstats** [comment]
@yihui can probably help you here.

**Comment by yihui** [comment]
搞定。

**Comment by chuxinyuan** [comment]
@yihui @nanxstats  辛苦了，十分感谢！
