### ISSUE TITLE
 rbind.io subdomain request

### ISSUE THREAD

**Issue by DallasNovakowski** [rbind/support#908]
## Netlify website address

dallasnova.netlify.app

## Preferred rbind.io subdomain

dallasnova.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@DallasNovakowski We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by DallasNovakowski** [comment]
Thank you. Just to confirm, would this be the appropriate syntax for redirecting?:

https://dallasnova.netlify.app/*  https://dallasnova.rbind.io/:splat  301!
http://dallasnova.netlify.app/*   https://dallasnova.rbind.io/:splat  301!
http://dallasnova.rbind.io/*      https://dallasnova.rbind.io/:splat  301!

**Comment by nanxstats** [comment]
If it's already working, then there is need to do any of the 301 redirects.

**Comment by DallasNovakowski** [comment]
Excellent. Thank you for being so quick and helpful!
