### ISSUE TITLE
new rbind subdomain request

### ISSUE THREAD

**Issue by asolisc** [rbind/support#909]
## Netlify website address

https://quantamental.netlify.app/

## Preferred rbind.io subdomain

quanto.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@asolisc We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by nanxstats** [comment]
@asolisc This is a gentle reminder to add the subdomain, please.

**Comment by asolisc** [comment]
Hi @nanxstats I have already added the domain to netlify, as instructed.
![image](https://user-images.githubusercontent.com/40329639/194789733-c2dbb353-c280-41be-a4fc-e360d00740af.png)

However, the site does not render properly. I'm working on this to check why the site does not render.

Maybe the problem was that I did not give you the correct netlify domain? The correct domain is: https://deluxe-marshmallow-defe7b.netlify.app/

**Comment by nanxstats** [comment]
Sure. @yihui could you please update `quanto.rbind.io` to point it to `deluxe-marshmallow-defe7b.netlify.app`? Thanks.

**Comment by yihui** [comment]
Done.

**Comment by nanxstats** [comment]
@asolisc I see quanto.rbind.io is now working as expected - please start deploying content to your website.
