### ISSUE TITLE
Requesting New Subdomain

### ISSUE THREAD

**Issue by rahulxc** [rbind/support#91]
I am a newbie but would love to try rbind out! My subdomain preference would be 
rahulxc.rbind.io 

Thank you!

**Comment by yihui** [comment]
Please let me know your Netlify subdomain first.

**Comment by rahulxc** [comment]
That'd be https://rahulxc.netlify.com/

**Comment by yihui** [comment]
I have configured the rbind subdomain you requested, but you have to contact Netlify support and they will configure it on their side (#42).
