### ISSUE TITLE
change my previous domain 

### ISSUE THREAD

**Issue by sohelkhanzz** [rbind/support#919]
## Netlify website address

previous :  sohelkhan.netlify.app
new github : sohelkhanz.github.io

## Preferred rbind.io subdomain

sohelkhan.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@yihui Could you please update the CNAME record for `sohelkhan.rbind.io` to `sohelkhanz.github.io`?

@sohelkhanz Please put a `CNAME` file in your GitHub repo to make it work: https://github.com/rbind/support/issues/139

**Comment by yihui** [comment]
Done.

**Comment by nanxstats** [comment]
Hey @sohelkhanz Please set up the `CNAME` in your GitHub Pages repo to make this work.
