### ISSUE TITLE
Request for subdomain for dataland.netlify.com

### ISSUE THREAD

**Issue by filipwastberg** [rbind/support#93]
Hi!

I would like to request a subdomain for my site at Netlify, [dataland.netlify.com](https://dataland.netlify.com/), to dataland.rbind.io.

Thanks in advance and thank you for the amazing work with book/blogdown. 

/ Filip

**Comment by yihui** [comment]
I have configured the rbind subdomain you requested, but you have to contact Netlify support and they will configure it on their side (#42).
