### ISSUE TITLE
change sub domain

### ISSUE THREAD

**Issue by boucp** [rbind/support#931]
## Netlify website address
previous:
boucp.netlify.app
new: 
boucp.github.io

## Preferred rbind.io subdomain

boucp.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@yihui Could you please update the CNAME record for `boucp.rbind.io` to `boucp.github.io`?

@boucp To make this work, please put a `CNAME` file in your GitHub repo: #139.

**Comment by yihui** [comment]
Done.

**Comment by boucp** [comment]
thanks
