### ISSUE TITLE
Requesting new site

### ISSUE THREAD

**Issue by ruaridhw** [rbind/support#94]
Hi,

I would like to setup a new site using the [Identity](https://themes.gohugo.io/hugo-identity-theme/) Hugo theme with blogdown. Preferable DNS would be ruaridhw.rbind.io if possible.

Thank you!

**Comment by yihui** [comment]
Cc @rbind/matrix 

I'll set up the rbind.io domain once the Netlify subdomain is ready.

**Comment by ruaridhw** [comment]
@rbind/matrix I've setup the repo and site at https://ruaridhw.netlify.com/
Let me know if you need anything else before configuring http://ruaridhw.rbind.io on your end. 

Thanks!

**Comment by road2stat** [comment]
@ruaridhw I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!

**Comment by road2stat** [comment]
Hi @ruaridhw - just a reminder -- please add ruaridhw.rbind.io as the custom domain for your Netlify site. Also, please remember to enable the automatic TLS certificates for the custom domain (Domain management -> HTTPS).
