### ISSUE TITLE
Supporting a server change for an existing subdomain

### ISSUE THREAD

**Issue by maheen** [rbind/support#946]
Hello, I have a website using an rbind.io subdomain (wheredmanogo.rbind.io) and the host has moved it to a different server. For the previous server, we had an A record pointed to the following IP address: 213.190.6.154. Can we switch this to a new IP address? This is the new IP address: 195.35.39.105

Thank you so much! I use my site all the time and really appreciate this service.

P.S. I share a server with another GitHub user, so once this is sorted you will see the same request come in for that account / subdomain.

**Comment by nanxstats** [comment]
@yihui You might be able to help here. Original request: https://github.com/rbind/support/issues/818

**Comment by yihui** [comment]
Done.

**Comment by maheen** [comment]
Thank you!
