### ISSUE TITLE
Changing the server for a subdomain

### ISSUE THREAD

**Issue by jackmurtagh** [rbind/support#947]
Hello, I have a website using an [rbind.io](http://rbind.io/) subdomain ([jackmurtagh.rbind.io](http://jackmurtagh.rbind.io/) - original request #905) and the host has moved it to a different server. For the previous server, we had an A record pointed to the following IP address: 213.190.6.154. Can we switch this to a new IP address? This is the new IP address: 195.35.39.105

I share a server with another GitHub user, so you just saw and addressed a similar request recently. 

Thank you so much!

**Comment by nanxstats** [comment]
@yihui another request for you today.

**Comment by yihui** [comment]
Done.
