### ISSUE TITLE
peteraungle.rbind.io

### ISSUE THREAD

**Issue by paungle** [rbind/support#949]
how do I verify this site with google?

## Netlify website address

example.netlify.app

## Preferred rbind.io subdomain

example.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Hi @paungle please include both of your Netlify website and rbind subdomain in the issue instead of "example".

On site ownership verification, see <https://support.google.com/webmasters/answer/9008080>. You can use any HTML-based method such as HTML file upload, HTML tag, Google Analytics tracking code, or Google Tag Manager.

**Comment by paungle** [comment]
Sure it’s peteraungle.netlify.app and the rbind subdomain is peteraungle.rbind.io

**Comment by nanxstats** [comment]
It looks like you already requested the subdomain in #421. Let's update the record then.

@yihui do you mind updating `peteraungle.rbind.io` to point it to `peteraungle.netlify.app`? Thanks.

**Comment by yihui** [comment]
Done.

**Comment by nanxstats** [comment]
Great, thanks. I'm closing the issue for now as nslookup shows the record has been updated and it's working.

```
➜ nslookup peteraungle.rbind.io
Server:		2600:4040:7635:5000::1
Address:	2600:4040:7635:5000::1#53

Non-authoritative answer:
peteraungle.rbind.io	canonical name = peteraungle.netlify.app.
Name:	peteraungle.netlify.app
Address: 54.84.236.175
Name:	peteraungle.netlify.app
Address: 44.219.53.183
```

**Comment by paungle** [comment]
Thank you for your help!


From: Nan Xiao ***@***.***>
Date: Wednesday, November 15, 2023 at 7:00 PM
To: rbind/support ***@***.***>
Cc: Aungle, Peter ***@***.***>, Mention ***@***.***>
Subject: Re: [rbind/support] peteraungle.rbind.io (Issue #949)

Great, thanks. I'm closing the issue for now as nslookup shows the record has been updated and it's working.

➜ nslookup peteraungle.rbind.io

Server:        2600:4040:7635:5000::1

Address:       2600:4040:7635:5000::1#53



Non-authoritative answer:

peteraungle.rbind.io   canonical name = peteraungle.netlify.app.

Name:   peteraungle.netlify.app

Address: 54.84.236.175

Name:   peteraungle.netlify.app

Address: 44.219.53.183
