### ISSUE TITLE
Requesting subdomain for dkim

### ISSUE THREAD

**Issue by akustika** [rbind/support#95]
Hi,

I’d like to request an rbind.io subdomain for dkim. This site is deployed through Netlify and currently lives at: https://dkim.netlify.com

Do you mind if I have dkim.rbind.io?

Thanks,
Don

**Comment by yihui** [comment]
I have configured the rbind subdomain you requested, but you have to contact Netlify support and they will configure it on their side (#42).

**Comment by akustika** [comment]
Thanks a lot, and thanks for blogdown!

**Comment by yihui** [comment]
My pleasure!
