### ISSUE TITLE
Request for rbind.io subdomain

### ISSUE THREAD

**Issue by vjjan91** [rbind/support#950]
Thank you for processing this request for a subdomain in rbind.io
I am a postdoctoral research fellow at the Cornell Lab of Ornithology & my primary research is in using quantitative analyses tools to monitor biodiversity responses to climate change. I am hoping to use this website to showcase current work & a blog featuring the usage of `sf` and spatial analyses tools in R.

Please note that I had an rbind.io domain before but I deleted it because I am redoing the website creation using the `distill` package in R. 

## Preferred rbind.io subdomain

vijayramesh.rbind.io

I would like to directly connect my github pages deployment to this subdomain requested. Would that be possible? I am not planning to use netlify.

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by vjjan91** [comment]
The associated git repo for the website is here: https://github.com/vjjan91/vijayramesh & I am hoping to transfer domain by going to settings > pages > custom domain

**Comment by nanxstats** [comment]
@vjjan91 Sure thing, what's you new Netlify site address?

**Comment by vjjan91** [comment]
@nanxstats Do you need a netlify address? I am not hoping to deploy my website via netlify & rather git pages. Please let me know!

**Comment by nanxstats** [comment]
@vjjan91 Not really - if you want to deploy via GitHub Pages, please let us know the `github.io` address instead.

**Comment by vjjan91** [comment]
Here's my github.io address where the website is currently being deployed:

https://vjjan91.github.io/vijayramesh/

**Comment by nanxstats** [comment]
Great - one more thing: Is it possible to host your website at `vjjan91.github.io`? I'm asking because we can only point the subdomain to another domain but not an address with a path component. With GitHub Pages, this can be done by using a [repo with a special name](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site#creating-a-repository-for-your-site).

**Comment by vjjan91** [comment]
I decided to go ahead and use netlify (since it was easier). My netlify address is:

vijayramesh.netlify.app

My subdomain requested is:

vijayramesh.rbind.io

**Comment by nanxstats** [comment]
@vjjan91 Cool. The record shows `vijayramesh.rbind.io` already points to `vijayramesh.netlify.app`.

It's currently showing a soft 404 though. It's unclear to me why, but you probably want to double check if the rbind subdomain is correctly set in your Netlify site configuration:

You can add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

**Comment by vjjan91** [comment]
Thanks! That works - is there a reason why it says this website is not secure? 
"Your connection is not secure:" message shows up in the top left corner next to the address

**Comment by nanxstats** [comment]
> Thanks! That works - is there a reason why it says this website is not secure? "Your connection is not secure:" message shows up in the top left corner next to the address

It works on my side on computer and phone networks - could be cache. Try connect from another computer.

**Comment by vjjan91** [comment]
Thanks again Nan for your quick response! I am going to close this as resolved. Appreciate the help!
