### ISSUE TITLE
Requesting new *.rbind.io subdomain

### ISSUE THREAD

**Issue by ampatzia** [rbind/support#96]
I would like to be assigned the ampatziakas.rbind.io subdomain, currently using https://ampatziakas.netlify.com/ .

**Comment by yihui** [comment]
I have configured the rbind subdomain you requested, but you have to contact Netlify support and they will configure it on their side (#42).

**Comment by ampatzia** [comment]
Done from both sides, subdomain active.
Thanks you for your time and effort :)
