### ISSUE TITLE
Transferring from Netlify to GitHub Pages

### ISSUE THREAD

**Issue by nrennie** [rbind/support#964]
I'm currently deploying to nrennie.rbind.io (created in #865) via Netlify but I'd like to switch to GitHub Pages (deployed via GitHub Actions). Would it be possible to have [nrennie.github.io](https://nrennie.github.io/) linked instead?

Do you need me to delete the netlify site first?

Thanks,
Nicola

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@yihui could you please help update the CNAME record for `nrennie.rbind.io` to `nrennie.github.io`?

@nrennie please put a `CNAME` file in your GitHub repo to make this work: https://github.com/rbind/support/issues/139. If you use Hugo, this should be put under `static/` so it can be copied to the site root as-is when rendering the site.

**Comment by nrennie** [comment]
@nanxstats Thanks! Added `CNAME` to `static/`

**Comment by yihui** [comment]
Done.

**Comment by nrennie** [comment]
Thanks!
