### ISSUE TITLE
Requesting new subdomain

### ISSUE THREAD

**Issue by DrJohan** [rbind/support#965]
## Netlify website address

drjohan.netlify.app

## Preferred rbind.io subdomain

drjohan.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
Hi @DrJohan `drjohan.rbind.io` has already been requested before and is pointing to the same address `drjohan.netlify.app` in https://github.com/rbind/support/issues/695.

Since it's showing a soft 404, maybe check if the subdomain was added as the custom domain to your Netlify site.

**Comment by DrJohan** [comment]
> Hi @DrJohan `drjohan.rbind.io` has already been requested before and is pointing to the same address `drjohan.netlify.app` in #695.
> 
> Since it's showing a soft 404, maybe check if the subdomain was added as the custom domain to your Netlify site.

Hi @nanxstats , the issue has been resolved now. Many thanks for your help.
