### ISSUE TITLE
subdomain request

### ISSUE THREAD

**Issue by shryshs** [rbind/support#967]
## Netlify website address

shreyash-web.netlify.app

## Preferred rbind.io subdomain

shreyash.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@ShreyashSomvanshi We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by shryshs** [comment]
Hi @nanxstats, I have encountered an issue that aligns with your expertise. Could you please take a look and offer your insights on resolving it? The link to the issue is [https://stackoverflow.com/questions/78130361/about-page-not-working-when-using-a-fresh-hugo-apero-build](https://stackoverflow.com/questions/78130361/about-page-not-working-when-using-a-fresh-hugo-apero-build). 

Thanks!

**Comment by nanxstats** [comment]
@ShreyashSomvanshi Just tested and the following works for me out of the box, say `~/zzz/` is the site directory:

```r
library(blogdown)

new_site(
  "~/zzz/",
  theme = "hugo-apero/hugo-apero",
  format = "toml",
  sample = FALSE,
  empty_dirs = TRUE
)
```

**Comment by shryshs** [comment]
Thank you @nanxstats for your time in addressing this issue. However, the fix seems to be working on your end but not on mine. I am still getting 404 Page not found in `About` section. Could you please assist me further in resolving this? My hugo-apero repository: [https://github.com/ShreyashSomvanshi/apero](https://github.com/ShreyashSomvanshi/apero)

**Comment by nanxstats** [comment]
Hey @ShreyashSomvanshi -sorry to hear that but it's not entirely clear to me what could be the issue - I think it would be productive if you can ask the original author of the blog post or the theme author.

**Comment by shryshs** [comment]
@nanxstats Thanks for your help and suggestion!
