### ISSUE TITLE
Rbind.io domain name

### ISSUE THREAD

**Issue by desautm** [rbind/support#97]
Hi, can I have madesautels.rbind.io domain name. I currently have madesautels.netlify.com name. Thanks in advance!

**Comment by yihui** [comment]
Done. Please set this domain for your website on Netlify and let me know if you run into any problems:

![image](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

**Comment by desautm** [comment]
Just done and my site is already live. Thanks, no problems on my end. Thank you for the speed of your response.

**Comment by yihui** [comment]
Very glad to hear that it worked well!
