### ISSUE TITLE
rbind subdomain request

### ISSUE THREAD

**Issue by rasenior** [rbind/support#972]
## Netlify website address

rasenior.netlify.app

## Preferred rbind.io subdomain

rasenior.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@yihui could you please help update the record for `rasenior.rbind.io` from `rebeccasenior.netlify.app` to `rasenior.netlify.app`? Thanks!

**Comment by yihui** [comment]
Done.
