### ISSUE TITLE
rbind.io subdomain request

### ISSUE THREAD

**Issue by RayonVina** [rbind/support#976]
Good day, 
I just created a personal webpage using rstudio quarto and I would like to request a subdomain of yours. I is not deployed with netlify but with github pages, I do no know if it is an issue or so.

Many thanks for your work

## ~~Netlify~~ Github pages website address

https://rayonvina.github.io/rayonvina/

## Preferred rbind.io subdomain

rayonvina.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@RayonVina We do support pointing subdomains to GitHub Pages. However, we can only redirect it to `rayonvina.github.io` without any path components like in `rayonvina.github.io/rayonvina/`. Do you want to move the website to `rayonvina.github.io` first? Check out [GitHub Pages documentation](https://docs.github.com/en/pages/quickstart) on how to create this "user site" at username.github.io.

**Comment by RayonVina** [comment]
Hi! I didn't know, sorry. 
It is alreay in rayonvina.github.io

Thanks.

**Comment by nanxstats** [comment]
@RayonVina We have configured the rbind subdomain you requested. Please put a `CNAME` file in your GitHub repo to make this work. Example: #139.

If you use Hugo, the `CNAME` file should be put under `static/` so it can be copied to the site root as-is when rendering. If you use Quarto, [add a `resources` entry](https://quarto.org/docs/websites/website-tools.html#site-resources) to your configuration so the `CNAME` file can be copied to the site root as-is when rendering the site.

**Comment by RayonVina** [comment]
It all went smoothly. 
Thank you again for your help :smile:
