### ISSUE TITLE
Requesting subdomain

### ISSUE THREAD

**Issue by asimumba** [rbind/support#98]
Hi, 

Kindly assist setting up the subdomain for the zedr blog. Desired subdomain is:  zedr.rbind.io.

**Comment by yihui** [comment]
Please tell us your Netlify subdomain first.

**Comment by asimumba** [comment]
https://minister-wolf-23726.netlify.com/.

**Comment by yihui** [comment]
Done. Please [configure the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

**Comment by asimumba** [comment]
Thank you @yihui

**Comment by asimumba** [comment]
I have gone through [#42](https://github.com/rbind/support/issues/42). I do not have that issue. My worry is that I managed to set up everything and the site was live. After setting up https, I am having broken links. Would you know the cause?

**Comment by yihui** [comment]
You must have changed your Netlify subdomain: https://minister-wolf-23726.netlify.com is no longer accessible.

**Comment by asimumba** [comment]
Ohh yes I did.

**Comment by asimumba** [comment]
Do I revert back?

**Comment by yihui** [comment]
Yes. Don't change your Netlify subdomain, because your rbind subdomain points to it.

**Comment by asimumba** [comment]
I have changed my theme to casper on the other site and I am getting the same error.

**Comment by asimumba** [comment]
I did change back but to no avail. Now I am suspecting the theme I am using,

**Comment by yihui** [comment]
I don't have time to help you with blogdown/Hugo/template issues. I can only afford the time to set up the domain for you. For all other issues, please [post to StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead (with reproducible examples). Thanks!

**Comment by asimumba** [comment]
@thercast maybe if you have time you can step in. For my personal blog: https://asimumba.rbind.io/ it is loading as an empty site. Plus you still have admin privileges on netlify. I have setup the same site at https://aaronsimumba.netlify.com/ and everything seem to work just fine. For the other blog http://zedr.rbind.io/ I can add you on netlify for a look.

**Comment by thercast** [comment]
Just to clarify was everything working before the switch to casper theme?  I took a look in the netlify deploy logs and nothing appeared out of the ordinary

**Comment by asimumba** [comment]
Everything was working. On the zedr.rbind.io i made the mistake of renaming it after @yihui had configured the .rbind.io subdomain. Despite reverting back to the randomly generated name on netlify, I still do seem to get the sites loading. On the deploy part, everything seem fine.
